# Modelo

In [28]:
import numpy as np
import pandas as pd
import joblib
import os
from PIL import Image

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import randint, uniform, norm, loguniform

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report

from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, GridSearchCV

from config import SEED, N_MELS

Elegimos dataset

In [2]:
dataset = 'ciclos_hl256_peak_t_aug_padmin_wd'

## Espectrogramas

Se suelen usar Mel espectrogramas

In [3]:
train_data = np.load(f'./dataset/{dataset}/train_melspectrogram.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_melspectrogram.npz')
X_test = test_data['X']
y_test = test_data['y']

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((11915, 47616), (11915,), (2850, 47616), (2850,))

### Random Forest

#### Entrenamiento

In [14]:
rf = RandomForestClassifier(random_state=SEED, n_jobs=-1, max_features='sqrt')
param_distributions = {
    'max_depth': randint(5, 15),
    'min_samples_split': randint(15, 30),
    'min_samples_leaf': randint(10, 20)
}

In [16]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=10,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END max_depth=11, min_samples_leaf=13, min_samples_split=27;, score=0.683 total time= 1.1min
[CV 2/5] END max_depth=11, min_samples_leaf=13, min_samples_split=27;, score=0.675 total time= 1.2min
[CV 3/5] END max_depth=11, min_samples_leaf=13, min_samples_split=27;, score=0.664 total time=  59.2s
[CV 4/5] END max_depth=11, min_samples_leaf=13, min_samples_split=27;, score=0.684 total time=  42.6s
[CV 5/5] END max_depth=11, min_samples_leaf=13, min_samples_split=27;, score=0.673 total time=  58.8s
[CV 1/5] END max_depth=12, min_samples_leaf=14, min_samples_split=21;, score=0.684 total time= 1.0min
[CV 2/5] END max_depth=12, min_samples_leaf=14, min_samples_split=21;, score=0.679 total time=  54.0s
[CV 3/5] END max_depth=12, min_samples_leaf=14, min_samples_split=21;, score=0.661 total time=  49.2s
[CV 4/5] END max_depth=12, min_samples_leaf=14, min_samples_split=21;, score=0.677 total time=  33.1s
[CV 5/5] END max_depth=12, min_samples_leaf=14, min_samples_split=21;, score=0.675 total time=  25.3s
[CV 1/5] END max_depth=14, min_samples_leaf=12, min_samples_split=21;, score=0.688 total time=  27.6s
[CV 2/5] END max_depth=14, min_samples_leaf=12, min_samples_split=21;, score=0.681 total time=  27.7s
[CV 3/5] END max_depth=14, min_samples_leaf=12, min_samples_split=21;, score=0.656 total time=  52.1s
[CV 4/5] END max_depth=14, min_samples_leaf=12, min_samples_split=21;, score=0.682 total time= 1.1min
[CV 5/5] END max_depth=14, min_samples_leaf=12, min_samples_split=21;, score=0.678 total time= 1.1min
[CV 1/5] END max_depth=12, min_samples_leaf=14, min_samples_split=18;, score=0.684 total time=  52.2s
[CV 2/5] END max_depth=12, min_samples_leaf=14, min_samples_split=18;, score=0.679 total time=  27.6s
[CV 3/5] END max_depth=12, min_samples_leaf=14, min_samples_split=18;, score=0.661 total time=  53.9s
[CV 4/5] END max_depth=12, min_samples_leaf=14, min_samples_split=18;, score=0.677 total time=  51.9s
[CV 5/5] END max_depth=12, min_samples_leaf=14, min_samples_split=18;, score=0.675 total time= 1.0min
[CV 1/5] END max_depth=12, min_samples_leaf=17, min_samples_split=17;, score=0.681 total time=  59.6s
[CV 2/5] END max_depth=12, min_samples_leaf=17, min_samples_split=17;, score=0.676 total time=  59.6s
[CV 3/5] END max_depth=12, min_samples_leaf=17, min_samples_split=17;, score=0.659 total time=  59.2s
[CV 4/5] END max_depth=12, min_samples_leaf=17, min_samples_split=17;, score=0.680 total time=  59.9s
[CV 5/5] END max_depth=12, min_samples_leaf=17, min_samples_split=17;, score=0.676 total time=  59.3s
[CV 1/5] END max_depth=10, min_samples_leaf=14, min_samples_split=16;, score=0.681 total time=  55.6s
[CV 2/5] END max_depth=10, min_samples_leaf=14, min_samples_split=16;, score=0.669 total time=  55.4s
[CV 3/5] END max_depth=10, min_samples_leaf=14, min_samples_split=16;, score=0.656 total time=  54.0s
[CV 4/5] END max_depth=10, min_samples_leaf=14, min_samples_split=16;, score=0.675 total time=  55.2s
[CV 5/5] END max_depth=10, min_samples_leaf=14, min_samples_split=16;, score=0.673 total time=  56.0s
[CV 1/5] END max_depth=12, min_samples_leaf=15, min_samples_split=16;, score=0.679 total time= 1.0min
[CV 2/5] END max_depth=12, min_samples_leaf=15, min_samples_split=16;, score=0.676 total time= 1.0min
[CV 3/5] END max_depth=12, min_samples_leaf=15, min_samples_split=16;, score=0.657 total time=  59.0s
[CV 4/5] END max_depth=12, min_samples_leaf=15, min_samples_split=16;, score=0.679 total time=  59.3s
[CV 5/5] END max_depth=12, min_samples_leaf=15, min_samples_split=16;, score=0.673 total time=  50.8s
[CV 1/5] END max_depth=9, min_samples_leaf=10, min_samples_split=26;, score=0.677 total time=  46.0s
[CV 2/5] END max_depth=9, min_samples_leaf=10, min_samples_split=26;, score=0.662 total time=  51.2s
[CV 3/5] END max_depth=9, min_samples_leaf=10, min_samples_split=26;, score=0.655 total time=  51.3s
[CV 4/5] END max_depth=9, min_samples_leaf=10, min_samples_split=26;, score=0.670 total time=  43.7s
[CV 5/5] END max_depth=9, min_samples_leaf=10, min_samples_split=26;, score=0.668 total time=  51.7s
[CV 1/5] END max_depth=14, min_samples_leaf=15, min_samples_split=27;, score=0.682 total time= 1.0min
[CV 2/5] END max_depth=14, min_samples_leaf=15, min_samples_split=27;, score=0.679 total time= 1.0min
[CV 3/5] END max_depth=14, min_samples_leaf=15, min_samples_split=27;, score=0.662 total time= 1.1min
[CV 4/5] END max_depth=14, min_samples_leaf=15, min_samples_split=27;, score=0.680 total time= 1.2min
[CV 5/5] END max_depth=14, min_samples_leaf=15, min_samples_split=27;, score=0.674 total time= 1.1min
[CV 1/5] END max_depth=13, min_samples_leaf=10, min_samples_split=25;, score=0.686 total time=  58.5s
[CV 2/5] END max_depth=13, min_samples_leaf=10, min_samples_split=25;, score=0.675 total time=  44.8s
[CV 3/5] END max_depth=13, min_samples_leaf=10, min_samples_split=25;, score=0.656 total time=  43.3s
[CV 4/5] END max_depth=13, min_samples_leaf=10, min_samples_split=25;, score=0.676 total time=  43.6s
[CV 5/5] END max_depth=13, min_samples_leaf=10, min_samples_split=25;, score=0.669 total time=  43.3s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002770552F950>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000277055A32F0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002770552ED70>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [17]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(10)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
2,14,12,21,0.676935
0,11,13,27,0.675707
8,14,15,27,0.675439
1,12,14,21,0.675148
3,12,14,18,0.675148
4,12,17,17,0.674225
6,12,15,16,0.672746
9,13,10,25,0.672598
5,10,14,16,0.670882
7,9,10,26,0.666472

In [18]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 14, 'min_samples_leaf': 12, 'min_samples_split': 21}
Best CV score: 0.6769346886796356

In [19]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.94      6046
           1       0.93      0.94      0.94      5869

    accuracy                           0.94     11915
   macro avg       0.94      0.94      0.94     11915
weighted avg       0.94      0.94      0.94     11915

#### Evaluación

In [20]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.58      0.64      0.61      1452
           1       0.59      0.52      0.55      1398

    accuracy                           0.58      2850
   macro avg       0.59      0.58      0.58      2850
weighted avg       0.59      0.58      0.58      2850

#### Guardado

In [21]:
os.makedirs(f'./modelos/{dataset}', exist_ok=True)

joblib.dump(best_model, f'./modelos/{dataset}/melspec_rf.pkl')

['./modelos/ciclos_hl256_peak_t_aug_padmin_wd/melspec_rf.pkl']

### Gradient Boost

In [28]:
gbc = HistGradientBoostingClassifier(
    max_iter=100,
    random_state=SEED,
    early_stopping=True,
    n_iter_no_change=10,
    learning_rate=0.2,
    l2_regularization=0.5
    )

In [29]:
gbc.fit(X_train, y_train)

HistGradientBoostingClassifier(early_stopping=True, l2_regularization=0.5,
                               learning_rate=0.2, random_state=42)

In [30]:
predict_train = gbc.predict(X_train)
print(classification_report(y_train, predict_train))

              precision    recall  f1-score   support

           0       0.87      0.88      0.88      6046
           1       0.88      0.87      0.87      5869

    accuracy                           0.88     11915
   macro avg       0.88      0.88      0.88     11915
weighted avg       0.88      0.88      0.88     11915

In [31]:
predict_test = gbc.predict(X_test)
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.60      0.65      0.62      1452
           1       0.60      0.54      0.57      1398

    accuracy                           0.60      2850
   macro avg       0.60      0.60      0.60      2850
weighted avg       0.60      0.60      0.60      2850

In [34]:
joblib.dump(gbc, f'./modelos/{dataset}/melspec_gbc.pkl')

['./modelos/ciclos_hl256_peak_t_aug_padmin_wd/melspec_gbc.pkl']

## Features de Audio

In [35]:
train_data = np.load(f'./dataset/{dataset}/train_features.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_features.npz')
X_test = test_data['X']
y_test = test_data['y']

In [36]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((11915, 46), (11915,), (2850, 46), (2850,))

### Random Forest

#### Entrenamiento

In [37]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

param_distributions = {
    'max_depth': randint(13, 20),
    'min_samples_split': randint(15, 30),
    'min_samples_leaf': randint(5, 15),
    'max_features': ['sqrt', 'log2', None]
}

In [38]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.713 total time=   1.4s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.698 total time=   1.2s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.705 total time=   1.2s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.713 total time=   1.2s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.714 total time=   1.3s
[CV 1/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.723 total time=   8.5s
[CV 2/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.699 total time=   8.0s
[CV 3/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.709 total time=   8.2s
[CV 4/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.711 total time=   9.8s
[CV 5/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.716 total time=  14.6s
[CV 1/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.725 total time=  15.3s
[CV 2/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.699 total time=  14.7s
[CV 3/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.711 total time=  15.1s
[CV 4/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.715 total time=  15.1s
[CV 5/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.717 total time=  15.2s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.726 total time=  12.5s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.702 total time=   8.9s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.712 total time=  14.4s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.715 total time=  14.7s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.720 total time=  14.6s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.717 total time=   1.9s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.701 total time=   1.9s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.702 total time=   1.8s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.705 total time=   1.8s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.707 total time=   1.8s
[CV 1/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.727 total time=   2.3s
[CV 2/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.706 total time=   2.4s
[CV 3/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.708 total time=   2.3s
[CV 4/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.710 total time=   2.4s
[CV 5/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.714 total time=   2.4s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.713 total time=   1.8s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.698 total time=   1.8s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.695 total time=   1.7s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.706 total time=   1.8s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.711 total time=   1.8s
[CV 1/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.723 total time=  14.1s
[CV 2/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.699 total time=  14.0s
[CV 3/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.709 total time=  14.1s
[CV 4/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.710 total time=  14.1s
[CV 5/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.714 total time=  14.2s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.724 total time=  15.1s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.702 total time=   8.6s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.706 total time=   9.4s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.711 total time=  14.5s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.719 total time=  15.0s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.724 total time=   2.4s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.715 total time=   2.5s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.711 total time=   2.4s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.712 total time=   2.4s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.720 total time=   2.5s
[CV 1/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.726 total time=  14.7s
[CV 2/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.703 total time=  14.4s
[CV 3/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.709 total time=  14.5s
[CV 4/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.712 total time=  14.7s
[CV 5/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.718 total time=  14.6s
[CV 1/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.723 total time=   2.0s
[CV 2/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.710 total time=   2.0s
[CV 3/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.710 total time=   2.0s
[CV 4/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.714 total time=   2.0s
[CV 5/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.715 total time=   2.1s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.723 total time=   2.0s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.711 total time=   2.1s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.709 total time=   2.0s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.710 total time=   2.0s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.721 total time=   2.0s
[CV 1/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.717 total time=   1.8s
[CV 2/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.702 total time=   1.8s
[CV 3/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.692 total time=   1.7s
[CV 4/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.703 total time=   1.7s
[CV 5/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.710 total time=   1.8s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.726 total time=  14.7s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.698 total time=  14.2s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.709 total time=  14.9s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.712 total time=  14.9s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.716 total time=  14.6s
[CV 1/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.723 total time=  15.2s
[CV 2/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.704 total time=  15.3s
[CV 3/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.707 total time=  15.8s
[CV 4/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.712 total time=  15.4s
[CV 5/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.717 total time=  15.7s
[CV 1/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.721 total time=   1.9s
[CV 2/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.697 total time=   1.7s
[CV 3/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.697 total time=   1.8s
[CV 4/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.702 total time=   1.8s
[CV 5/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.706 total time=   1.7s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.717 total time=   1.8s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.701 total time=   1.8s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.702 total time=   2.0s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.705 total time=   1.9s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.707 total time=   1.8s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.717 total time=   1.8s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.702 total time=   1.9s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.703 total time=   1.9s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.710 total time=   1.8s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.710 total time=   1.9s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.714 total time=   1.9s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.700 total time=   1.9s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.700 total time=   1.8s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.704 total time=   1.8s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.710 total time=   1.9s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.716 total time=   1.9s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.701 total time=   1.9s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.702 total time=   1.9s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.702 total time=   1.9s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.706 total time=   2.1s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.717 total time=   2.3s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.705 total time=   2.3s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.705 total time=   2.3s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.705 total time=   2.3s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.715 total time=   2.3s
[CV 1/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.716 total time=   2.0s
[CV 2/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.707 total time=   2.1s
[CV 3/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.709 total time=   2.0s
[CV 4/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.715 total time=   1.9s
[CV 5/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.717 total time=   1.9s
[CV 1/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.714 total time=   2.1s
[CV 2/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.696 total time=   2.1s
[CV 3/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.698 total time=   2.0s
[CV 4/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.702 total time=   2.0s
[CV 5/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.705 total time=   2.2s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.727 total time=   2.4s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.707 total time=   2.5s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.709 total time=   2.4s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.713 total time=   2.2s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.717 total time=   1.9s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.717 total time=   1.7s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.705 total time=   1.6s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.705 total time=   1.7s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.705 total time=   1.6s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.715 total time=   1.6s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.729 total time=  11.1s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.705 total time=  11.0s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.712 total time=  10.8s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.715 total time=  10.9s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.724 total time=  10.7s
[CV 1/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.727 total time=   8.2s
[CV 2/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.703 total time=   9.8s
[CV 3/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.710 total time=  10.4s
[CV 4/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.711 total time=  10.6s
[CV 5/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.721 total time=  10.5s
[CV 1/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.717 total time=   1.3s
[CV 2/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.704 total time=   1.4s
[CV 3/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.702 total time=   1.3s
[CV 4/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.708 total time=   1.4s
[CV 5/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.715 total time=   1.4s
[CV 1/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.722 total time=   9.3s
[CV 2/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.697 total time=   9.2s
[CV 3/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.706 total time=   9.2s
[CV 4/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.708 total time=   9.3s
[CV 5/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.711 total time=   9.3s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.718 total time=   1.4s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.710 total time=   1.3s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.709 total time=   1.4s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.711 total time=   1.4s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.721 total time=   1.4s
[CV 1/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.722 total time=   1.4s
[CV 2/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.699 total time=   1.4s
[CV 3/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.706 total time=   1.3s
[CV 4/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.709 total time=   1.4s
[CV 5/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.715 total time=   1.3s
[CV 1/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.719 total time=   1.3s
[CV 2/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.714 total time=   1.4s
[CV 3/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.703 total time=   1.3s
[CV 4/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.716 total time=   1.3s
[CV 5/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.718 total time=   1.3s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=50,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000027915CB7130>,
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002790E166D50>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002790E167550>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [40]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'param_max_features', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_max_features,mean_test_score
26,16,7,15,None,0.716945
9,19,7,19,sqrt,0.716469
41,19,7,20,None,0.716033
3,16,10,19,None,0.715332
43,18,9,20,sqrt,0.714909
24,19,5,23,sqrt,0.714752
12,16,6,24,log2,0.714675
27,15,5,25,None,0.714601
11,19,8,23,log2,0.714466
32,15,7,15,log2,0.714249
40,19,8,27,None,0.713837
33,15,7,15,sqrt,0.713785
30,16,5,21,log2,0.713697
37,17,11,15,None,0.713613
10,15,9,23,None,0.713470
2,19,12,19,None,0.713431
5,16,5,26,sqrt,0.712937
22,17,9,22,log2,0.712714
8,16,7,26,None,0.712399
15,17,7,28,None,0.712374
14,16,11,26,None,0.712004
39,17,11,27,None,0.711853
49,15,9,15,sqrt,0.711843
47,18,8,27,sqrt,0.711779
1,17,14,17,None,0.711733
35,18,13,29,None,0.711133
7,15,14,26,None,0.710867
31,19,12,19,log2,0.710430
48,13,11,20,None,0.710360
38,16,8,28,sqrt,0.710032
21,19,12,19,sqrt,0.709340
25,19,12,15,sqrt,0.709340
28,17,11,24,log2,0.709204
29,13,13,22,None,0.708922
0,19,12,27,sqrt,0.708479
18,14,6,24,log2,0.708349
34,17,11,29,log2,0.707984
45,16,11,28,sqrt,0.707976
4,14,10,16,log2,0.706422
17,14,10,20,log2,0.706422
36,19,14,26,log2,0.706389
19,16,14,28,log2,0.705468
44,16,14,21,log2,0.705468
42,16,14,27,log2,0.705468
20,16,12,28,log2,0.705317
13,13,9,16,log2,0.704924
16,13,12,18,log2,0.704517
6,14,13,15,log2,0.704441
23,14,13,27,sqrt,0.702811
46,13,13,25,sqrt,0.702439

In [41]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 16, 'max_features': None, 'min_samples_leaf': 7, 'min_samples_split': 15}
Best CV score: 0.7169454611069874

In [42]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94      6046
           1       0.93      0.95      0.94      5869

    accuracy                           0.94     11915
   macro avg       0.94      0.94      0.94     11915
weighted avg       0.94      0.94      0.94     11915

#### Evaluación

In [43]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.59      0.86      0.70      1452
           1       0.72      0.36      0.48      1398

    accuracy                           0.62      2850
   macro avg       0.65      0.61      0.59      2850
weighted avg       0.65      0.62      0.59      2850

#### Guardado

In [44]:
joblib.dump(best_model, f'./modelos/{dataset}/features_rf.pkl')

['./modelos/ciclos_hl256_peak_t_aug_padmin_wd/features_rf.pkl']

### Gradient Boosting

In [45]:
gbc = HistGradientBoostingClassifier(
    max_iter=100,
    random_state=SEED,
    early_stopping=True,
    n_iter_no_change=10
    )

In [55]:
param_grid = {
    'learning_rate': [0.05, 0.1, 0.2],
    'l2_regularization': [0, 0.1, 0.3, 0.5, 0.7, 0.9]
}

rnd_search = GridSearchCV(
    estimator=gbc,
    param_grid=param_grid,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END l2_regularization=0, learning_rate=0.05;, score=0.709 total time=   0.5s
[CV 2/5] END l2_regularization=0, learning_rate=0.05;, score=0.690 total time=   0.4s
[CV 3/5] END l2_regularization=0, learning_rate=0.05;, score=0.697 total time=   0.5s
[CV 4/5] END l2_regularization=0, learning_rate=0.05;, score=0.707 total time=   0.5s
[CV 5/5] END l2_regularization=0, learning_rate=0.05;, score=0.705 total time=   0.6s
[CV 1/5] END l2_regularization=0, learning_rate=0.1;, score=0.713 total time=   0.5s
[CV 2/5] END l2_regularization=0, learning_rate=0.1;, score=0.695 total time=   0.4s
[CV 3/5] END l2_regularization=0, learning_rate=0.1;, score=0.705 total time=   0.4s
[CV 4/5] END l2_regularization=0, learning_rate=0.1;, score=0.701 total time=   0.4s
[CV 5/5] END l2_regularization=0, learning_rate=0.1;, score=0.703 total time=   0.5s
[CV 1/5] END l2_regularization=0, learning_rate=0.2;, score=0.708 total time=   0.3s
[CV 2/5] END l2_regularization=0, learning_rate=0.2;, score=0.690 total time=   0.2s
[CV 3/5] END l2_regularization=0, learning_rate=0.2;, score=0.693 total time=   0.3s
[CV 4/5] END l2_regularization=0, learning_rate=0.2;, score=0.708 total time=   0.4s
[CV 5/5] END l2_regularization=0, learning_rate=0.2;, score=0.700 total time=   0.2s
[CV 1/5] END l2_regularization=0.1, learning_rate=0.05;, score=0.706 total time=   0.5s
[CV 2/5] END l2_regularization=0.1, learning_rate=0.05;, score=0.689 total time=   0.7s
[CV 3/5] END l2_regularization=0.1, learning_rate=0.05;, score=0.694 total time=   0.6s
[CV 4/5] END l2_regularization=0.1, learning_rate=0.05;, score=0.703 total time=   1.3s
[CV 5/5] END l2_regularization=0.1, learning_rate=0.05;, score=0.703 total time=   1.3s
[CV 1/5] END l2_regularization=0.1, learning_rate=0.1;, score=0.712 total time=   0.9s
[CV 2/5] END l2_regularization=0.1, learning_rate=0.1;, score=0.692 total time=   1.3s
[CV 3/5] END l2_regularization=0.1, learning_rate=0.1;, score=0.710 total time=   1.0s
[CV 4/5] END l2_regularization=0.1, learning_rate=0.1;, score=0.710 total time=   1.2s
[CV 5/5] END l2_regularization=0.1, learning_rate=0.1;, score=0.708 total time=   1.1s
[CV 1/5] END l2_regularization=0.1, learning_rate=0.2;, score=0.713 total time=   0.8s
[CV 2/5] END l2_regularization=0.1, learning_rate=0.2;, score=0.703 total time=   1.2s
[CV 3/5] END l2_regularization=0.1, learning_rate=0.2;, score=0.687 total time=   0.4s
[CV 4/5] END l2_regularization=0.1, learning_rate=0.2;, score=0.705 total time=   0.7s
[CV 5/5] END l2_regularization=0.1, learning_rate=0.2;, score=0.700 total time=   0.7s
[CV 1/5] END l2_regularization=0.3, learning_rate=0.05;, score=0.708 total time=   1.3s
[CV 2/5] END l2_regularization=0.3, learning_rate=0.05;, score=0.694 total time=   1.3s
[CV 3/5] END l2_regularization=0.3, learning_rate=0.05;, score=0.696 total time=   1.4s
[CV 4/5] END l2_regularization=0.3, learning_rate=0.05;, score=0.701 total time=   1.3s
[CV 5/5] END l2_regularization=0.3, learning_rate=0.05;, score=0.707 total time=   1.4s
[CV 1/5] END l2_regularization=0.3, learning_rate=0.1;, score=0.716 total time=   1.3s
[CV 2/5] END l2_regularization=0.3, learning_rate=0.1;, score=0.701 total time=   1.0s
[CV 3/5] END l2_regularization=0.3, learning_rate=0.1;, score=0.700 total time=   1.3s
[CV 4/5] END l2_regularization=0.3, learning_rate=0.1;, score=0.705 total time=   1.4s
[CV 5/5] END l2_regularization=0.3, learning_rate=0.1;, score=0.708 total time=   1.3s
[CV 1/5] END l2_regularization=0.3, learning_rate=0.2;, score=0.715 total time=   0.8s
[CV 2/5] END l2_regularization=0.3, learning_rate=0.2;, score=0.688 total time=   0.4s
[CV 3/5] END l2_regularization=0.3, learning_rate=0.2;, score=0.695 total time=   0.7s
[CV 4/5] END l2_regularization=0.3, learning_rate=0.2;, score=0.702 total time=   0.5s
[CV 5/5] END l2_regularization=0.3, learning_rate=0.2;, score=0.688 total time=   0.6s
[CV 1/5] END l2_regularization=0.5, learning_rate=0.05;, score=0.707 total time=   1.3s
[CV 2/5] END l2_regularization=0.5, learning_rate=0.05;, score=0.691 total time=   1.3s
[CV 3/5] END l2_regularization=0.5, learning_rate=0.05;, score=0.699 total time=   1.4s
[CV 4/5] END l2_regularization=0.5, learning_rate=0.05;, score=0.703 total time=   1.3s
[CV 5/5] END l2_regularization=0.5, learning_rate=0.05;, score=0.706 total time=   1.4s
[CV 1/5] END l2_regularization=0.5, learning_rate=0.1;, score=0.713 total time=   1.3s
[CV 2/5] END l2_regularization=0.5, learning_rate=0.1;, score=0.699 total time=   1.3s
[CV 3/5] END l2_regularization=0.5, learning_rate=0.1;, score=0.702 total time=   1.3s
[CV 4/5] END l2_regularization=0.5, learning_rate=0.1;, score=0.710 total time=   1.3s
[CV 5/5] END l2_regularization=0.5, learning_rate=0.1;, score=0.705 total time=   1.3s
[CV 1/5] END l2_regularization=0.5, learning_rate=0.2;, score=0.720 total time=   0.7s
[CV 2/5] END l2_regularization=0.5, learning_rate=0.2;, score=0.701 total time=   0.9s
[CV 3/5] END l2_regularization=0.5, learning_rate=0.2;, score=0.695 total time=   0.8s
[CV 4/5] END l2_regularization=0.5, learning_rate=0.2;, score=0.712 total time=   0.8s
[CV 5/5] END l2_regularization=0.5, learning_rate=0.2;, score=0.698 total time=   0.6s
[CV 1/5] END l2_regularization=0.7, learning_rate=0.05;, score=0.708 total time=   1.4s
[CV 2/5] END l2_regularization=0.7, learning_rate=0.05;, score=0.692 total time=   1.4s
[CV 3/5] END l2_regularization=0.7, learning_rate=0.05;, score=0.692 total time=   1.4s
[CV 4/5] END l2_regularization=0.7, learning_rate=0.05;, score=0.708 total time=   1.4s
[CV 5/5] END l2_regularization=0.7, learning_rate=0.05;, score=0.703 total time=   1.4s
[CV 1/5] END l2_regularization=0.7, learning_rate=0.1;, score=0.717 total time=   1.4s
[CV 2/5] END l2_regularization=0.7, learning_rate=0.1;, score=0.706 total time=   1.4s
[CV 3/5] END l2_regularization=0.7, learning_rate=0.1;, score=0.709 total time=   1.4s
[CV 4/5] END l2_regularization=0.7, learning_rate=0.1;, score=0.705 total time=   1.2s
[CV 5/5] END l2_regularization=0.7, learning_rate=0.1;, score=0.716 total time=   1.3s
[CV 1/5] END l2_regularization=0.7, learning_rate=0.2;, score=0.712 total time=   0.9s
[CV 2/5] END l2_regularization=0.7, learning_rate=0.2;, score=0.693 total time=   0.9s
[CV 3/5] END l2_regularization=0.7, learning_rate=0.2;, score=0.691 total time=   0.6s
[CV 4/5] END l2_regularization=0.7, learning_rate=0.2;, score=0.706 total time=   0.7s
[CV 5/5] END l2_regularization=0.7, learning_rate=0.2;, score=0.701 total time=   0.5s
[CV 1/5] END l2_regularization=0.9, learning_rate=0.05;, score=0.711 total time=   1.4s
[CV 2/5] END l2_regularization=0.9, learning_rate=0.05;, score=0.689 total time=   1.4s
[CV 3/5] END l2_regularization=0.9, learning_rate=0.05;, score=0.695 total time=   1.4s
[CV 4/5] END l2_regularization=0.9, learning_rate=0.05;, score=0.705 total time=   1.4s
[CV 5/5] END l2_regularization=0.9, learning_rate=0.05;, score=0.704 total time=   1.4s
[CV 1/5] END l2_regularization=0.9, learning_rate=0.1;, score=0.719 total time=   1.1s
[CV 2/5] END l2_regularization=0.9, learning_rate=0.1;, score=0.701 total time=   1.4s
[CV 3/5] END l2_regularization=0.9, learning_rate=0.1;, score=0.702 total time=   1.4s
[CV 4/5] END l2_regularization=0.9, learning_rate=0.1;, score=0.702 total time=   1.2s
[CV 5/5] END l2_regularization=0.9, learning_rate=0.1;, score=0.697 total time=   1.4s
[CV 1/5] END l2_regularization=0.9, learning_rate=0.2;, score=0.705 total time=   0.6s
[CV 2/5] END l2_regularization=0.9, learning_rate=0.2;, score=0.688 total time=   0.8s
[CV 3/5] END l2_regularization=0.9, learning_rate=0.2;, score=0.692 total time=   0.6s
[CV 4/5] END l2_regularization=0.9, learning_rate=0.2;, score=0.690 total time=   0.5s
[CV 5/5] END l2_regularization=0.9, learning_rate=0.2;, score=0.709 total time=   0.9s

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=HistGradientBoostingClassifier(early_stopping=True,
                                                      random_state=42),
             param_grid={'l2_regularization': [0, 0.1, 0.3, 0.5, 0.7, 0.9],
                         'learning_rate': [0.05, 0.1, 0.2]},
             scoring='roc_auc', verbose=3)

In [56]:
pd.DataFrame(rnd_search.cv_results_)[['param_learning_rate', 'param_l2_regularization', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

    param_learning_rate  param_l2_regularization  mean_test_score
13                 0.10                      0.7         0.710430
4                  0.10                      0.1         0.706303
7                  0.10                      0.3         0.705903
10                 0.10                      0.5         0.705798
11                 0.20                      0.5         0.705068
16                 0.10                      0.9         0.704179
1                  0.10                      0.0         0.703394
0                  0.05                      0.0         0.701807
5                  0.20                      0.1         0.701605
6                  0.05                      0.3         0.701191
9                  0.05                      0.5         0.701011
15                 0.05                      0.9         0.700915
14                 0.20                      0.7         0.700656
12                 0.05                      0.7         0.700532
2                  0.20                      0.0         0.699718
3                  0.05                      0.1         0.699044
8                  0.20                      0.3         0.697848
17                 0.20                      0.9         0.696496

In [57]:
best_model = rnd_search.best_estimator_

In [59]:
predict_train = best_model.predict(X_train)
print(classification_report(y_train, predict_train))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84      6046
           1       0.83      0.85      0.84      5869

    accuracy                           0.84     11915
   macro avg       0.84      0.84      0.84     11915
weighted avg       0.84      0.84      0.84     11915

In [60]:
predict_test = best_model.predict(X_test)
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.58      0.85      0.69      1452
           1       0.70      0.37      0.48      1398

    accuracy                           0.61      2850
   macro avg       0.64      0.61      0.59      2850
weighted avg       0.64      0.61      0.59      2850

In [61]:
joblib.dump(best_model, f'./modelos/{dataset}/features_gbc.pkl')

['./modelos/ciclos_hl256_peak_t_aug_padmin_wd/features_gbc.pkl']

## Imagenes de Mel Espectrogramas

In [ ]:
train_dir = f'./dataset/{dataset}/mel_images/train'
test_dir = f'./dataset/{dataset}/mel_images/test'

In [30]:
def load_image_dataset_pil(img_dir, to_gray=True, flatten=False, target_size=None):
    df = pd.read_csv(os.path.join(img_dir, 'labels.csv'))
    X, y = [], []
    for _, row in df.iterrows():
        path = os.path.join(img_dir, row['filename'])
        img = Image.open(path)
        
        if to_gray:
            img = img.convert('L')  # convierte a escala de grises (1 canal)
        
        if target_size:
            img = img.resize(target_size, Image.BICUBIC)
        
        img = np.array(img, dtype=np.float32)
        
        if flatten:
            img = img.flatten()
        
        X.append(img)
        y.append(row['label'])
    
    return np.array(X), np.array(y)

In [31]:
X_train, y_train = load_image_dataset_pil(train_dir, to_gray=True, flatten=True, target_size=(256, N_MELS))
X_test, y_test = load_image_dataset_pil(test_dir, to_gray=True, flatten=True, target_size=(256, N_MELS))

### Random Forest

In [48]:
rf = RandomForestClassifier(random_state=SEED, n_jobs=-1, max_features='sqrt')

param_distributions = {
    'max_depth': randint(5, 15),
    'min_samples_split': randint(10, 20),
    'min_samples_leaf': randint(5, 10)
}

In [49]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=10,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END max_depth=11, min_samples_leaf=8, min_samples_split=17;, score=0.680 total time=  18.0s
[CV 2/5] END max_depth=11, min_samples_leaf=8, min_samples_split=17;, score=0.674 total time=  23.7s
[CV 3/5] END max_depth=11, min_samples_leaf=8, min_samples_split=17;, score=0.659 total time=  39.8s
[CV 4/5] END max_depth=11, min_samples_leaf=8, min_samples_split=17;, score=0.666 total time=  39.0s
[CV 5/5] END max_depth=11, min_samples_leaf=8, min_samples_split=17;, score=0.676 total time=  38.7s
[CV 1/5] END max_depth=9, min_samples_leaf=6, min_samples_split=12;, score=0.674 total time=  34.3s
[CV 2/5] END max_depth=9, min_samples_leaf=6, min_samples_split=12;, score=0.666 total time=  33.1s
[CV 3/5] END max_depth=9, min_samples_leaf=6, min_samples_split=12;, score=0.654 total time=  34.5s
[CV 4/5] END max_depth=9, min_samples_leaf=6, min_samples_split=12;, score=0.659 total time=  15.1s
[CV 5/5] END max_depth=9, min_samples_leaf=6, min_samples_split=12;, score=0.670 total time=  15.6s
[CV 1/5] END max_depth=11, min_samples_leaf=7, min_samples_split=17;, score=0.680 total time=  38.2s
[CV 2/5] END max_depth=11, min_samples_leaf=7, min_samples_split=17;, score=0.670 total time=  39.0s
[CV 3/5] END max_depth=11, min_samples_leaf=7, min_samples_split=17;, score=0.659 total time=  38.7s
[CV 4/5] END max_depth=11, min_samples_leaf=7, min_samples_split=17;, score=0.660 total time=  38.2s
[CV 5/5] END max_depth=11, min_samples_leaf=7, min_samples_split=17;, score=0.667 total time=  39.1s
[CV 1/5] END max_depth=9, min_samples_leaf=8, min_samples_split=17;, score=0.673 total time=  32.6s
[CV 2/5] END max_depth=9, min_samples_leaf=8, min_samples_split=17;, score=0.662 total time=  33.2s
[CV 3/5] END max_depth=9, min_samples_leaf=8, min_samples_split=17;, score=0.653 total time=  26.8s
[CV 4/5] END max_depth=9, min_samples_leaf=8, min_samples_split=17;, score=0.665 total time=  19.8s
[CV 5/5] END max_depth=9, min_samples_leaf=8, min_samples_split=17;, score=0.666 total time=  25.0s
[CV 1/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.677 total time=  20.0s
[CV 2/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.669 total time=  15.7s
[CV 3/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.665 total time=  17.8s
[CV 4/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.671 total time=  27.6s
[CV 5/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.680 total time=  28.5s
[CV 1/5] END max_depth=9, min_samples_leaf=6, min_samples_split=17;, score=0.674 total time=  22.5s
[CV 2/5] END max_depth=9, min_samples_leaf=6, min_samples_split=17;, score=0.662 total time=  22.3s
[CV 3/5] END max_depth=9, min_samples_leaf=6, min_samples_split=17;, score=0.656 total time=  22.8s
[CV 4/5] END max_depth=9, min_samples_leaf=6, min_samples_split=17;, score=0.660 total time=  23.1s
[CV 5/5] END max_depth=9, min_samples_leaf=6, min_samples_split=17;, score=0.667 total time=  22.5s
[CV 1/5] END max_depth=10, min_samples_leaf=6, min_samples_split=14;, score=0.672 total time=  24.6s
[CV 2/5] END max_depth=10, min_samples_leaf=6, min_samples_split=14;, score=0.671 total time=  24.5s
[CV 3/5] END max_depth=10, min_samples_leaf=6, min_samples_split=14;, score=0.650 total time=  24.4s
[CV 4/5] END max_depth=10, min_samples_leaf=6, min_samples_split=14;, score=0.663 total time=  22.9s
[CV 5/5] END max_depth=10, min_samples_leaf=6, min_samples_split=14;, score=0.669 total time=  22.3s
[CV 1/5] END max_depth=5, min_samples_leaf=8, min_samples_split=19;, score=0.651 total time=  13.8s
[CV 2/5] END max_depth=5, min_samples_leaf=8, min_samples_split=19;, score=0.644 total time=   9.1s
[CV 3/5] END max_depth=5, min_samples_leaf=8, min_samples_split=19;, score=0.634 total time=   7.8s
[CV 4/5] END max_depth=5, min_samples_leaf=8, min_samples_split=19;, score=0.640 total time=   6.9s
[CV 5/5] END max_depth=5, min_samples_leaf=8, min_samples_split=19;, score=0.648 total time=   6.9s
[CV 1/5] END max_depth=10, min_samples_leaf=9, min_samples_split=18;, score=0.670 total time=  14.2s
[CV 2/5] END max_depth=10, min_samples_leaf=9, min_samples_split=18;, score=0.664 total time=  24.2s
[CV 3/5] END max_depth=10, min_samples_leaf=9, min_samples_split=18;, score=0.657 total time=  25.3s
[CV 4/5] END max_depth=10, min_samples_leaf=9, min_samples_split=18;, score=0.661 total time=  24.5s
[CV 5/5] END max_depth=10, min_samples_leaf=9, min_samples_split=18;, score=0.669 total time=  17.6s
[CV 1/5] END max_depth=5, min_samples_leaf=7, min_samples_split=19;, score=0.650 total time=  14.3s
[CV 2/5] END max_depth=5, min_samples_leaf=7, min_samples_split=19;, score=0.644 total time=  13.7s
[CV 3/5] END max_depth=5, min_samples_leaf=7, min_samples_split=19;, score=0.635 total time=  13.6s
[CV 4/5] END max_depth=5, min_samples_leaf=7, min_samples_split=19;, score=0.640 total time=  13.9s
[CV 5/5] END max_depth=5, min_samples_leaf=7, min_samples_split=19;, score=0.648 total time=  13.8s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F6952207C0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F6950B7550>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F6952209E0>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [50]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
4,12,7,15,0.672478
0,11,8,17,0.671235
2,11,7,17,0.667070
6,10,6,14,0.664937
1,9,6,12,0.664492
8,10,9,18,0.664443
3,9,8,17,0.664030
5,9,6,17,0.663687
9,5,7,19,0.643356
7,5,8,19,0.643218

In [59]:
best_model = rnd_search.best_estimator_

In [60]:
predict_train = best_model.predict(X_train)
print(classification_report(y_train, predict_train))

              precision    recall  f1-score   support

           0       0.98      0.93      0.95      6046
           1       0.93      0.98      0.96      5869

    accuracy                           0.96     11915
   macro avg       0.96      0.96      0.96     11915
weighted avg       0.96      0.96      0.96     11915

In [61]:
predict_test = best_model.predict(X_test)
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.70      0.65      0.68       663
           1       0.66      0.71      0.69       633

    accuracy                           0.68      1296
   macro avg       0.68      0.68      0.68      1296
weighted avg       0.68      0.68      0.68      1296

In [62]:
joblib.dump(best_model, f'./modelos/{dataset}/melspec_img_rf.pkl')

['./modelos/ciclos_hl256_peak_t_aug_padmin_wd/melspec_img_rf.pkl']