# Modelo

In [28]:
import numpy as np
import pandas as pd
import joblib
import os

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import randint, uniform, norm, loguniform

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report

from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, GridSearchCV

from config import SEED

Elegimos dataset

In [8]:
dataset = 'ciclos_c_r2'

## Espectrogramas

Se suelen usar Mel espectrogramas

Traigo los consjuntos de entrenamiento y testeo. (TODO: buscar una manera más eficiente de guardarlos)

In [9]:
train_data = np.load(f'./dataset/{dataset}/train_melspectrogram.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_melspectrogram.npz')
X_test = test_data['X']
y_test = test_data['y']

In [10]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((8289, 23808), (8289,), (1296, 23808), (1296,))

### Random Forest

#### Entrenamiento

In [20]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_features='log2')

param_distributions = {
    'max_depth': randint(8, 15),
    'min_samples_split': randint(5, 10),
    'min_samples_leaf': randint(7, 15)
}

In [21]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='recall',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END max_depth=14, min_samples_leaf=10, min_samples_split=9;, score=0.660 total time=   2.7s
[CV 2/5] END max_depth=14, min_samples_leaf=10, min_samples_split=9;, score=0.642 total time=   2.4s
[CV 3/5] END max_depth=14, min_samples_leaf=10, min_samples_split=9;, score=0.590 total time=   3.2s
[CV 4/5] END max_depth=14, min_samples_leaf=10, min_samples_split=9;, score=0.595 total time=   4.5s
[CV 5/5] END max_depth=14, min_samples_leaf=10, min_samples_split=9;, score=0.601 total time=   4.6s
[CV 1/5] END max_depth=14, min_samples_leaf=9, min_samples_split=9;, score=0.658 total time=   4.6s
[CV 2/5] END max_depth=14, min_samples_leaf=9, min_samples_split=9;, score=0.640 total time=   4.5s
[CV 3/5] END max_depth=14, min_samples_leaf=9, min_samples_split=9;, score=0.604 total time=   4.6s
[CV 4/5] END max_depth=14, min_samples_leaf=9, min_samples_split=9;, score=0.608 total time=   4.8s
[CV 5/5] END max_depth=14, min_samples_leaf=9, min_samples_split=9;, score=0.601 total time=   4.9s
[CV 1/5] END max_depth=12, min_samples_leaf=13, min_samples_split=6;, score=0.657 total time=   4.6s
[CV 2/5] END max_depth=12, min_samples_leaf=13, min_samples_split=6;, score=0.647 total time=   4.7s
[CV 3/5] END max_depth=12, min_samples_leaf=13, min_samples_split=6;, score=0.593 total time=   4.7s
[CV 4/5] END max_depth=12, min_samples_leaf=13, min_samples_split=6;, score=0.604 total time=   4.5s
[CV 5/5] END max_depth=12, min_samples_leaf=13, min_samples_split=6;, score=0.606 total time=   4.7s
[CV 1/5] END max_depth=10, min_samples_leaf=13, min_samples_split=7;, score=0.653 total time=   4.3s
[CV 2/5] END max_depth=10, min_samples_leaf=13, min_samples_split=7;, score=0.646 total time=   4.5s
[CV 3/5] END max_depth=10, min_samples_leaf=13, min_samples_split=7;, score=0.600 total time=   4.4s
[CV 4/5] END max_depth=10, min_samples_leaf=13, min_samples_split=7;, score=0.586 total time=   4.4s
[CV 5/5] END max_depth=10, min_samples_leaf=13, min_samples_split=7;, score=0.608 total time=   4.3s
[CV 1/5] END max_depth=10, min_samples_leaf=14, min_samples_split=9;, score=0.665 total time=   4.3s
[CV 2/5] END max_depth=10, min_samples_leaf=14, min_samples_split=9;, score=0.642 total time=   4.2s
[CV 3/5] END max_depth=10, min_samples_leaf=14, min_samples_split=9;, score=0.606 total time=   4.4s
[CV 4/5] END max_depth=10, min_samples_leaf=14, min_samples_split=9;, score=0.591 total time=   4.3s
[CV 5/5] END max_depth=10, min_samples_leaf=14, min_samples_split=9;, score=0.604 total time=   4.3s
[CV 1/5] END max_depth=11, min_samples_leaf=14, min_samples_split=7;, score=0.654 total time=   4.3s
[CV 2/5] END max_depth=11, min_samples_leaf=14, min_samples_split=7;, score=0.644 total time=   4.4s
[CV 3/5] END max_depth=11, min_samples_leaf=14, min_samples_split=7;, score=0.615 total time=   4.4s
[CV 4/5] END max_depth=11, min_samples_leaf=14, min_samples_split=7;, score=0.575 total time=   3.1s
[CV 5/5] END max_depth=11, min_samples_leaf=14, min_samples_split=7;, score=0.605 total time=   2.3s
[CV 1/5] END max_depth=13, min_samples_leaf=11, min_samples_split=6;, score=0.650 total time=   2.6s
[CV 2/5] END max_depth=13, min_samples_leaf=11, min_samples_split=6;, score=0.630 total time=   2.4s
[CV 3/5] END max_depth=13, min_samples_leaf=11, min_samples_split=6;, score=0.590 total time=   2.3s
[CV 4/5] END max_depth=13, min_samples_leaf=11, min_samples_split=6;, score=0.588 total time=   2.3s
[CV 5/5] END max_depth=13, min_samples_leaf=11, min_samples_split=6;, score=0.606 total time=   2.4s
[CV 1/5] END max_depth=11, min_samples_leaf=12, min_samples_split=6;, score=0.657 total time=   2.1s
[CV 2/5] END max_depth=11, min_samples_leaf=12, min_samples_split=6;, score=0.646 total time=   2.2s
[CV 3/5] END max_depth=11, min_samples_leaf=12, min_samples_split=6;, score=0.606 total time=   2.4s
[CV 4/5] END max_depth=11, min_samples_leaf=12, min_samples_split=6;, score=0.594 total time=   2.6s
[CV 5/5] END max_depth=11, min_samples_leaf=12, min_samples_split=6;, score=0.604 total time=   2.3s
[CV 1/5] END max_depth=11, min_samples_leaf=11, min_samples_split=5;, score=0.648 total time=   2.7s
[CV 2/5] END max_depth=11, min_samples_leaf=11, min_samples_split=5;, score=0.651 total time=   2.4s
[CV 3/5] END max_depth=11, min_samples_leaf=11, min_samples_split=5;, score=0.600 total time=   2.5s
[CV 4/5] END max_depth=11, min_samples_leaf=11, min_samples_split=5;, score=0.601 total time=   2.4s
[CV 5/5] END max_depth=11, min_samples_leaf=11, min_samples_split=5;, score=0.614 total time=   2.6s
[CV 1/5] END max_depth=11, min_samples_leaf=8, min_samples_split=9;, score=0.657 total time=   2.5s
[CV 2/5] END max_depth=11, min_samples_leaf=8, min_samples_split=9;, score=0.642 total time=   2.3s
[CV 3/5] END max_depth=11, min_samples_leaf=8, min_samples_split=9;, score=0.614 total time=   2.5s
[CV 4/5] END max_depth=11, min_samples_leaf=8, min_samples_split=9;, score=0.608 total time=   2.4s
[CV 5/5] END max_depth=11, min_samples_leaf=8, min_samples_split=9;, score=0.609 total time=   4.1s
[CV 1/5] END max_depth=11, min_samples_leaf=7, min_samples_split=5;, score=0.665 total time=   4.5s
[CV 2/5] END max_depth=11, min_samples_leaf=7, min_samples_split=5;, score=0.661 total time=   6.5s
[CV 3/5] END max_depth=11, min_samples_leaf=7, min_samples_split=5;, score=0.620 total time=   4.6s
[CV 4/5] END max_depth=11, min_samples_leaf=7, min_samples_split=5;, score=0.598 total time=   4.5s
[CV 5/5] END max_depth=11, min_samples_leaf=7, min_samples_split=5;, score=0.640 total time=   4.7s
[CV 1/5] END max_depth=10, min_samples_leaf=9, min_samples_split=6;, score=0.655 total time=   4.5s
[CV 2/5] END max_depth=10, min_samples_leaf=9, min_samples_split=6;, score=0.644 total time=   4.5s
[CV 3/5] END max_depth=10, min_samples_leaf=9, min_samples_split=6;, score=0.610 total time=   4.4s
[CV 4/5] END max_depth=10, min_samples_leaf=9, min_samples_split=6;, score=0.588 total time=   4.7s
[CV 5/5] END max_depth=10, min_samples_leaf=9, min_samples_split=6;, score=0.609 total time=   4.6s
[CV 1/5] END max_depth=11, min_samples_leaf=10, min_samples_split=7;, score=0.664 total time=   4.5s
[CV 2/5] END max_depth=11, min_samples_leaf=10, min_samples_split=7;, score=0.645 total time=   4.5s
[CV 3/5] END max_depth=11, min_samples_leaf=10, min_samples_split=7;, score=0.603 total time=   4.7s
[CV 4/5] END max_depth=11, min_samples_leaf=10, min_samples_split=7;, score=0.596 total time=   4.6s
[CV 5/5] END max_depth=11, min_samples_leaf=10, min_samples_split=7;, score=0.614 total time=   4.7s
[CV 1/5] END max_depth=11, min_samples_leaf=13, min_samples_split=8;, score=0.652 total time=   4.6s
[CV 2/5] END max_depth=11, min_samples_leaf=13, min_samples_split=8;, score=0.656 total time=   3.8s
[CV 3/5] END max_depth=11, min_samples_leaf=13, min_samples_split=8;, score=0.596 total time=   2.2s
[CV 4/5] END max_depth=11, min_samples_leaf=13, min_samples_split=8;, score=0.605 total time=   2.2s
[CV 5/5] END max_depth=11, min_samples_leaf=13, min_samples_split=8;, score=0.603 total time=   2.2s
[CV 1/5] END max_depth=8, min_samples_leaf=9, min_samples_split=9;, score=0.642 total time=   2.1s
[CV 2/5] END max_depth=8, min_samples_leaf=9, min_samples_split=9;, score=0.630 total time=   2.1s
[CV 3/5] END max_depth=8, min_samples_leaf=9, min_samples_split=9;, score=0.618 total time=   2.1s
[CV 4/5] END max_depth=8, min_samples_leaf=9, min_samples_split=9;, score=0.570 total time=   2.2s
[CV 5/5] END max_depth=8, min_samples_leaf=9, min_samples_split=9;, score=0.608 total time=   2.1s
[CV 1/5] END max_depth=10, min_samples_leaf=13, min_samples_split=9;, score=0.653 total time=   2.2s
[CV 2/5] END max_depth=10, min_samples_leaf=13, min_samples_split=9;, score=0.646 total time=   2.2s
[CV 3/5] END max_depth=10, min_samples_leaf=13, min_samples_split=9;, score=0.600 total time=   2.1s
[CV 4/5] END max_depth=10, min_samples_leaf=13, min_samples_split=9;, score=0.586 total time=   2.2s
[CV 5/5] END max_depth=10, min_samples_leaf=13, min_samples_split=9;, score=0.608 total time=   2.2s
[CV 1/5] END max_depth=8, min_samples_leaf=13, min_samples_split=6;, score=0.653 total time=   2.0s
[CV 2/5] END max_depth=8, min_samples_leaf=13, min_samples_split=6;, score=0.640 total time=   2.2s
[CV 3/5] END max_depth=8, min_samples_leaf=13, min_samples_split=6;, score=0.611 total time=   2.1s
[CV 4/5] END max_depth=8, min_samples_leaf=13, min_samples_split=6;, score=0.590 total time=   2.2s
[CV 5/5] END max_depth=8, min_samples_leaf=13, min_samples_split=6;, score=0.599 total time=   2.0s
[CV 1/5] END max_depth=11, min_samples_leaf=7, min_samples_split=8;, score=0.665 total time=   2.3s
[CV 2/5] END max_depth=11, min_samples_leaf=7, min_samples_split=8;, score=0.661 total time=   2.2s
[CV 3/5] END max_depth=11, min_samples_leaf=7, min_samples_split=8;, score=0.620 total time=   2.3s
[CV 4/5] END max_depth=11, min_samples_leaf=7, min_samples_split=8;, score=0.598 total time=   2.2s
[CV 5/5] END max_depth=11, min_samples_leaf=7, min_samples_split=8;, score=0.640 total time=   2.2s
[CV 1/5] END max_depth=13, min_samples_leaf=8, min_samples_split=6;, score=0.663 total time=   2.4s
[CV 2/5] END max_depth=13, min_samples_leaf=8, min_samples_split=6;, score=0.640 total time=   2.4s
[CV 3/5] END max_depth=13, min_samples_leaf=8, min_samples_split=6;, score=0.594 total time=   2.3s
[CV 4/5] END max_depth=13, min_samples_leaf=8, min_samples_split=6;, score=0.593 total time=   2.4s
[CV 5/5] END max_depth=13, min_samples_leaf=8, min_samples_split=6;, score=0.605 total time=   2.3s
[CV 1/5] END max_depth=8, min_samples_leaf=8, min_samples_split=9;, score=0.658 total time=   2.0s
[CV 2/5] END max_depth=8, min_samples_leaf=8, min_samples_split=9;, score=0.649 total time=   2.1s
[CV 3/5] END max_depth=8, min_samples_leaf=8, min_samples_split=9;, score=0.621 total time=   2.1s
[CV 4/5] END max_depth=8, min_samples_leaf=8, min_samples_split=9;, score=0.581 total time=   2.1s
[CV 5/5] END max_depth=8, min_samples_leaf=8, min_samples_split=9;, score=0.595 total time=   2.2s
[CV 1/5] END max_depth=9, min_samples_leaf=10, min_samples_split=8;, score=0.658 total time=   2.1s
[CV 2/5] END max_depth=9, min_samples_leaf=10, min_samples_split=8;, score=0.631 total time=   2.2s
[CV 3/5] END max_depth=9, min_samples_leaf=10, min_samples_split=8;, score=0.605 total time=   2.1s
[CV 4/5] END max_depth=9, min_samples_leaf=10, min_samples_split=8;, score=0.590 total time=   2.1s
[CV 5/5] END max_depth=9, min_samples_leaf=10, min_samples_split=8;, score=0.605 total time=   2.1s
[CV 1/5] END max_depth=14, min_samples_leaf=10, min_samples_split=8;, score=0.660 total time=   2.3s
[CV 2/5] END max_depth=14, min_samples_leaf=10, min_samples_split=8;, score=0.642 total time=   2.3s
[CV 3/5] END max_depth=14, min_samples_leaf=10, min_samples_split=8;, score=0.590 total time=   2.3s
[CV 4/5] END max_depth=14, min_samples_leaf=10, min_samples_split=8;, score=0.595 total time=   2.3s
[CV 5/5] END max_depth=14, min_samples_leaf=10, min_samples_split=8;, score=0.601 total time=   2.3s
[CV 1/5] END max_depth=12, min_samples_leaf=14, min_samples_split=7;, score=0.659 total time=   2.3s
[CV 2/5] END max_depth=12, min_samples_leaf=14, min_samples_split=7;, score=0.641 total time=   2.3s
[CV 3/5] END max_depth=12, min_samples_leaf=14, min_samples_split=7;, score=0.603 total time=   2.3s
[CV 4/5] END max_depth=12, min_samples_leaf=14, min_samples_split=7;, score=0.591 total time=   2.6s
[CV 5/5] END max_depth=12, min_samples_leaf=14, min_samples_split=7;, score=0.610 total time=   2.5s
[CV 1/5] END max_depth=13, min_samples_leaf=7, min_samples_split=8;, score=0.669 total time=   2.7s
[CV 2/5] END max_depth=13, min_samples_leaf=7, min_samples_split=8;, score=0.660 total time=   2.5s
[CV 3/5] END max_depth=13, min_samples_leaf=7, min_samples_split=8;, score=0.619 total time=   2.8s
[CV 4/5] END max_depth=13, min_samples_leaf=7, min_samples_split=8;, score=0.601 total time=   2.5s
[CV 5/5] END max_depth=13, min_samples_leaf=7, min_samples_split=8;, score=0.623 total time=   4.6s
[CV 1/5] END max_depth=9, min_samples_leaf=14, min_samples_split=8;, score=0.652 total time=   4.1s
[CV 2/5] END max_depth=9, min_samples_leaf=14, min_samples_split=8;, score=0.630 total time=   4.1s
[CV 3/5] END max_depth=9, min_samples_leaf=14, min_samples_split=8;, score=0.611 total time=   4.1s
[CV 4/5] END max_depth=9, min_samples_leaf=14, min_samples_split=8;, score=0.589 total time=   4.1s
[CV 5/5] END max_depth=9, min_samples_leaf=14, min_samples_split=8;, score=0.598 total time=   4.0s
[CV 1/5] END max_depth=9, min_samples_leaf=12, min_samples_split=6;, score=0.665 total time=   4.1s
[CV 2/5] END max_depth=9, min_samples_leaf=12, min_samples_split=6;, score=0.646 total time=   4.3s
[CV 3/5] END max_depth=9, min_samples_leaf=12, min_samples_split=6;, score=0.601 total time=   4.2s
[CV 4/5] END max_depth=9, min_samples_leaf=12, min_samples_split=6;, score=0.585 total time=   4.0s
[CV 5/5] END max_depth=9, min_samples_leaf=12, min_samples_split=6;, score=0.609 total time=   4.1s
[CV 1/5] END max_depth=11, min_samples_leaf=12, min_samples_split=9;, score=0.657 total time=   4.3s
[CV 2/5] END max_depth=11, min_samples_leaf=12, min_samples_split=9;, score=0.646 total time=   4.3s
[CV 3/5] END max_depth=11, min_samples_leaf=12, min_samples_split=9;, score=0.606 total time=   4.4s
[CV 4/5] END max_depth=11, min_samples_leaf=12, min_samples_split=9;, score=0.594 total time=   4.3s
[CV 5/5] END max_depth=11, min_samples_leaf=12, min_samples_split=9;, score=0.604 total time=   4.3s
[CV 1/5] END max_depth=14, min_samples_leaf=8, min_samples_split=6;, score=0.655 total time=   4.6s
[CV 2/5] END max_depth=14, min_samples_leaf=8, min_samples_split=6;, score=0.649 total time=   4.6s
[CV 3/5] END max_depth=14, min_samples_leaf=8, min_samples_split=6;, score=0.594 total time=   4.4s
[CV 4/5] END max_depth=14, min_samples_leaf=8, min_samples_split=6;, score=0.589 total time=   4.7s
[CV 5/5] END max_depth=14, min_samples_leaf=8, min_samples_split=6;, score=0.621 total time=   4.5s
[CV 1/5] END max_depth=11, min_samples_leaf=8, min_samples_split=6;, score=0.657 total time=   4.5s
[CV 2/5] END max_depth=11, min_samples_leaf=8, min_samples_split=6;, score=0.642 total time=   4.4s
[CV 3/5] END max_depth=11, min_samples_leaf=8, min_samples_split=6;, score=0.614 total time=   4.5s
[CV 4/5] END max_depth=11, min_samples_leaf=8, min_samples_split=6;, score=0.608 total time=   4.7s
[CV 5/5] END max_depth=11, min_samples_leaf=8, min_samples_split=6;, score=0.609 total time=   4.4s
[CV 1/5] END max_depth=13, min_samples_leaf=10, min_samples_split=8;, score=0.668 total time=   4.5s
[CV 2/5] END max_depth=13, min_samples_leaf=10, min_samples_split=8;, score=0.654 total time=   4.5s
[CV 3/5] END max_depth=13, min_samples_leaf=10, min_samples_split=8;, score=0.604 total time=   4.5s
[CV 4/5] END max_depth=13, min_samples_leaf=10, min_samples_split=8;, score=0.581 total time=   4.5s
[CV 5/5] END max_depth=13, min_samples_leaf=10, min_samples_split=8;, score=0.614 total time=   4.5s
[CV 1/5] END max_depth=8, min_samples_leaf=12, min_samples_split=9;, score=0.658 total time=   4.0s
[CV 2/5] END max_depth=8, min_samples_leaf=12, min_samples_split=9;, score=0.654 total time=   4.1s
[CV 3/5] END max_depth=8, min_samples_leaf=12, min_samples_split=9;, score=0.611 total time=   4.3s
[CV 4/5] END max_depth=8, min_samples_leaf=12, min_samples_split=9;, score=0.599 total time=   4.0s
[CV 5/5] END max_depth=8, min_samples_leaf=12, min_samples_split=9;, score=0.604 total time=   4.1s
[CV 1/5] END max_depth=12, min_samples_leaf=8, min_samples_split=9;, score=0.657 total time=   4.5s
[CV 2/5] END max_depth=12, min_samples_leaf=8, min_samples_split=9;, score=0.656 total time=   4.4s
[CV 3/5] END max_depth=12, min_samples_leaf=8, min_samples_split=9;, score=0.596 total time=   4.8s
[CV 4/5] END max_depth=12, min_samples_leaf=8, min_samples_split=9;, score=0.575 total time=   4.5s
[CV 5/5] END max_depth=12, min_samples_leaf=8, min_samples_split=9;, score=0.620 total time=   4.5s
[CV 1/5] END max_depth=9, min_samples_leaf=7, min_samples_split=8;, score=0.644 total time=   4.1s
[CV 2/5] END max_depth=9, min_samples_leaf=7, min_samples_split=8;, score=0.646 total time=   4.4s
[CV 3/5] END max_depth=9, min_samples_leaf=7, min_samples_split=8;, score=0.605 total time=   4.3s
[CV 4/5] END max_depth=9, min_samples_leaf=7, min_samples_split=8;, score=0.586 total time=   4.4s
[CV 5/5] END max_depth=9, min_samples_leaf=7, min_samples_split=8;, score=0.616 total time=   4.4s
[CV 1/5] END max_depth=11, min_samples_leaf=10, min_samples_split=9;, score=0.664 total time=   4.5s
[CV 2/5] END max_depth=11, min_samples_leaf=10, min_samples_split=9;, score=0.645 total time=   4.6s
[CV 3/5] END max_depth=11, min_samples_leaf=10, min_samples_split=9;, score=0.603 total time=   4.4s
[CV 4/5] END max_depth=11, min_samples_leaf=10, min_samples_split=9;, score=0.596 total time=   4.5s
[CV 5/5] END max_depth=11, min_samples_leaf=10, min_samples_split=9;, score=0.614 total time=   4.0s
[CV 1/5] END max_depth=8, min_samples_leaf=11, min_samples_split=9;, score=0.643 total time=   2.2s
[CV 2/5] END max_depth=8, min_samples_leaf=11, min_samples_split=9;, score=0.641 total time=   2.0s
[CV 3/5] END max_depth=8, min_samples_leaf=11, min_samples_split=9;, score=0.618 total time=   2.1s
[CV 4/5] END max_depth=8, min_samples_leaf=11, min_samples_split=9;, score=0.595 total time=   2.3s
[CV 5/5] END max_depth=8, min_samples_leaf=11, min_samples_split=9;, score=0.604 total time=   2.1s
[CV 1/5] END max_depth=8, min_samples_leaf=7, min_samples_split=5;, score=0.660 total time=   2.1s
[CV 2/5] END max_depth=8, min_samples_leaf=7, min_samples_split=5;, score=0.647 total time=   2.1s
[CV 3/5] END max_depth=8, min_samples_leaf=7, min_samples_split=5;, score=0.615 total time=   2.1s
[CV 4/5] END max_depth=8, min_samples_leaf=7, min_samples_split=5;, score=0.591 total time=   2.1s
[CV 5/5] END max_depth=8, min_samples_leaf=7, min_samples_split=5;, score=0.604 total time=   2.2s
[CV 1/5] END max_depth=8, min_samples_leaf=10, min_samples_split=7;, score=0.647 total time=   2.1s
[CV 2/5] END max_depth=8, min_samples_leaf=10, min_samples_split=7;, score=0.642 total time=   2.2s
[CV 3/5] END max_depth=8, min_samples_leaf=10, min_samples_split=7;, score=0.603 total time=   2.1s
[CV 4/5] END max_depth=8, min_samples_leaf=10, min_samples_split=7;, score=0.588 total time=   2.3s
[CV 5/5] END max_depth=8, min_samples_leaf=10, min_samples_split=7;, score=0.599 total time=   2.1s
[CV 1/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.653 total time=   2.2s
[CV 2/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.647 total time=   2.2s
[CV 3/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.609 total time=   2.3s
[CV 4/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.589 total time=   2.3s
[CV 5/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.623 total time=   2.5s
[CV 1/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.653 total time=   2.2s
[CV 2/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.647 total time=   2.2s
[CV 3/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.609 total time=   2.2s
[CV 4/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.589 total time=   2.2s
[CV 5/5] END max_depth=10, min_samples_leaf=7, min_samples_split=7;, score=0.623 total time=   2.2s
[CV 1/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.657 total time=   2.3s
[CV 2/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.656 total time=   2.2s
[CV 3/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.596 total time=   2.3s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(max_features='log2',
                                                    n_jobs=-1,
                                                    random_state=42),
                   n_iter=50,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002373F3E9B50>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002373F4426C0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002373F440D70>},
                   random_state=42, scoring='recall', verbose=3)

In [22]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(20)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
10,11,7,5,0.636834
17,11,7,8,0.636834
23,13,7,8,0.634333
9,11,8,9,0.625836
28,11,8,6,0.625836
41,11,8,5,0.625836
30,8,12,9,0.625086
12,11,10,7,0.624334
33,11,10,9,0.624334
44,10,7,7,0.624087
38,10,7,7,0.624087
37,10,7,7,0.624087
43,10,10,7,0.624086
29,13,10,8,0.624083
35,8,7,5,0.623585
8,11,11,5,0.622838
13,11,13,8,0.622337
1,14,9,9,0.622086
4,10,14,9,0.621834
27,14,8,6,0.621586

In [23]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = RandomForestClassifier(max_depth=11, min_samples_leaf=7, min_samples_split=8, n_jobs=-1, random_state=SEED)
best_model.fit(X_train, y_train)

Best params: {'max_depth': 11, 'min_samples_leaf': 7, 'min_samples_split': 5}
Best CV score: 0.6368336454431961

RandomForestClassifier(max_depth=11, min_samples_leaf=7, min_samples_split=8,
                       n_jobs=-1, random_state=42)

In [24]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91      4288
           1       0.90      0.92      0.91      4001

    accuracy                           0.91      8289
   macro avg       0.91      0.91      0.91      8289
weighted avg       0.91      0.91      0.91      8289

#### Evaluación

In [25]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.64      0.66       663
           1       0.64      0.69      0.67       633

    accuracy                           0.66      1296
   macro avg       0.66      0.66      0.66      1296
weighted avg       0.66      0.66      0.66      1296

#### Guardado

In [29]:
os.makedirs(f'./modelos/{dataset}', exist_ok=True)

joblib.dump(best_model, f'./modelos/{dataset}/melspec_rf.pkl')

['./modelos/ciclos_c_r2/melspec_rf.pkl']

## Atributos de Audio

1. Resample y Filtro pasa bajos
2. Feature Extractor
    + MFCC (13)
    + ZCR
    + Short-Time Energy
    + SC
    + Spectral Roll-off
    + BER
    + Spectral Flatness

In [30]:
train_data = np.load(f'./dataset/{dataset}/train_features.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_features.npz')
X_test = test_data['X']
y_test = test_data['y']

In [31]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((8289, 19), (8289,), (1296, 19), (1296,))

### Random Forest

#### Entrenamiento

In [32]:
rf = RandomForestClassifier(random_state=42, max_features=None, n_jobs=-1)

param_distributions = {
    'max_depth': randint(8, 15),
    'min_samples_split': randint(10, 25),
    'min_samples_leaf': randint(10, 25)
}

In [33]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='recall',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END max_depth=14, min_samples_leaf=13, min_samples_split=22;, score=0.670 total time=   1.9s
[CV 2/5] END max_depth=14, min_samples_leaf=13, min_samples_split=22;, score=0.662 total time=   1.9s
[CV 3/5] END max_depth=14, min_samples_leaf=13, min_samples_split=22;, score=0.649 total time=   1.8s
[CV 4/5] END max_depth=14, min_samples_leaf=13, min_samples_split=22;, score=0.641 total time=   1.8s
[CV 5/5] END max_depth=14, min_samples_leaf=13, min_samples_split=22;, score=0.667 total time=   1.8s
[CV 1/5] END max_depth=14, min_samples_leaf=20, min_samples_split=17;, score=0.664 total time=   1.7s
[CV 2/5] END max_depth=14, min_samples_leaf=20, min_samples_split=17;, score=0.640 total time=   1.8s
[CV 3/5] END max_depth=14, min_samples_leaf=20, min_samples_split=17;, score=0.627 total time=   1.7s
[CV 4/5] END max_depth=14, min_samples_leaf=20, min_samples_split=17;, score=0.627 total time=   1.7s
[CV 5/5] END max_depth=14, min_samples_leaf=20, min_samples_split=17;, score=0.652 total time=   1.6s
[CV 1/5] END max_depth=12, min_samples_leaf=14, min_samples_split=16;, score=0.674 total time=   1.7s
[CV 2/5] END max_depth=12, min_samples_leaf=14, min_samples_split=16;, score=0.644 total time=   1.8s
[CV 3/5] END max_depth=12, min_samples_leaf=14, min_samples_split=16;, score=0.646 total time=   1.8s
[CV 4/5] END max_depth=12, min_samples_leaf=14, min_samples_split=16;, score=0.639 total time=   1.8s
[CV 5/5] END max_depth=12, min_samples_leaf=14, min_samples_split=16;, score=0.662 total time=   1.7s
[CV 1/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.663 total time=   1.6s
[CV 2/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.630 total time=   1.6s
[CV 3/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.623 total time=   1.6s
[CV 4/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.616 total time=   1.6s
[CV 5/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.644 total time=   1.6s
[CV 1/5] END max_depth=10, min_samples_leaf=20, min_samples_split=17;, score=0.665 total time=   1.7s
[CV 2/5] END max_depth=10, min_samples_leaf=20, min_samples_split=17;, score=0.629 total time=   1.7s
[CV 3/5] END max_depth=10, min_samples_leaf=20, min_samples_split=17;, score=0.626 total time=   1.6s
[CV 4/5] END max_depth=10, min_samples_leaf=20, min_samples_split=17;, score=0.623 total time=   1.7s
[CV 5/5] END max_depth=10, min_samples_leaf=20, min_samples_split=17;, score=0.639 total time=   1.6s
[CV 1/5] END max_depth=12, min_samples_leaf=13, min_samples_split=17;, score=0.669 total time=   1.8s
[CV 2/5] END max_depth=12, min_samples_leaf=13, min_samples_split=17;, score=0.659 total time=   1.8s
[CV 3/5] END max_depth=12, min_samples_leaf=13, min_samples_split=17;, score=0.647 total time=   1.8s
[CV 4/5] END max_depth=12, min_samples_leaf=13, min_samples_split=17;, score=0.636 total time=   1.8s
[CV 5/5] END max_depth=12, min_samples_leaf=13, min_samples_split=17;, score=0.660 total time=   1.8s
[CV 1/5] END max_depth=10, min_samples_leaf=15, min_samples_split=14;, score=0.668 total time=   1.7s
[CV 2/5] END max_depth=10, min_samples_leaf=15, min_samples_split=14;, score=0.637 total time=   1.7s
[CV 3/5] END max_depth=10, min_samples_leaf=15, min_samples_split=14;, score=0.642 total time=   1.7s
[CV 4/5] END max_depth=10, min_samples_leaf=15, min_samples_split=14;, score=0.629 total time=   1.6s
[CV 5/5] END max_depth=10, min_samples_leaf=15, min_samples_split=14;, score=0.645 total time=   1.7s
[CV 1/5] END max_depth=9, min_samples_leaf=17, min_samples_split=21;, score=0.669 total time=   1.5s
[CV 2/5] END max_depth=9, min_samples_leaf=17, min_samples_split=21;, score=0.624 total time=   1.6s
[CV 3/5] END max_depth=9, min_samples_leaf=17, min_samples_split=21;, score=0.632 total time=   1.6s
[CV 4/5] END max_depth=9, min_samples_leaf=17, min_samples_split=21;, score=0.625 total time=   1.6s
[CV 5/5] END max_depth=9, min_samples_leaf=17, min_samples_split=21;, score=0.634 total time=   1.6s
[CV 1/5] END max_depth=13, min_samples_leaf=15, min_samples_split=11;, score=0.669 total time=   1.8s
[CV 2/5] END max_depth=13, min_samples_leaf=15, min_samples_split=11;, score=0.647 total time=   1.8s
[CV 3/5] END max_depth=13, min_samples_leaf=15, min_samples_split=11;, score=0.652 total time=   1.8s
[CV 4/5] END max_depth=13, min_samples_leaf=15, min_samples_split=11;, score=0.636 total time=   1.8s
[CV 5/5] END max_depth=13, min_samples_leaf=15, min_samples_split=11;, score=0.654 total time=   1.8s
[CV 1/5] END max_depth=11, min_samples_leaf=14, min_samples_split=10;, score=0.678 total time=   1.8s
[CV 2/5] END max_depth=11, min_samples_leaf=14, min_samples_split=10;, score=0.642 total time=   1.8s
[CV 3/5] END max_depth=11, min_samples_leaf=14, min_samples_split=10;, score=0.645 total time=   1.7s
[CV 4/5] END max_depth=11, min_samples_leaf=14, min_samples_split=10;, score=0.634 total time=   1.8s
[CV 5/5] END max_depth=11, min_samples_leaf=14, min_samples_split=10;, score=0.654 total time=   1.7s
[CV 1/5] END max_depth=11, min_samples_leaf=19, min_samples_split=15;, score=0.674 total time=   1.7s
[CV 2/5] END max_depth=11, min_samples_leaf=19, min_samples_split=15;, score=0.632 total time=   1.7s
[CV 3/5] END max_depth=11, min_samples_leaf=19, min_samples_split=15;, score=0.634 total time=   1.7s
[CV 4/5] END max_depth=11, min_samples_leaf=19, min_samples_split=15;, score=0.627 total time=   1.8s
[CV 5/5] END max_depth=11, min_samples_leaf=19, min_samples_split=15;, score=0.644 total time=   2.2s
[CV 1/5] END max_depth=12, min_samples_leaf=21, min_samples_split=18;, score=0.668 total time=   2.2s
[CV 2/5] END max_depth=12, min_samples_leaf=21, min_samples_split=18;, score=0.634 total time=   2.3s
[CV 3/5] END max_depth=12, min_samples_leaf=21, min_samples_split=18;, score=0.631 total time=   2.1s
[CV 4/5] END max_depth=12, min_samples_leaf=21, min_samples_split=18;, score=0.630 total time=   2.1s
[CV 5/5] END max_depth=12, min_samples_leaf=21, min_samples_split=18;, score=0.647 total time=   2.1s
[CV 1/5] END max_depth=8, min_samples_leaf=20, min_samples_split=20;, score=0.657 total time=   1.9s
[CV 2/5] END max_depth=8, min_samples_leaf=20, min_samples_split=20;, score=0.621 total time=   1.8s
[CV 3/5] END max_depth=8, min_samples_leaf=20, min_samples_split=20;, score=0.615 total time=   1.8s
[CV 4/5] END max_depth=8, min_samples_leaf=20, min_samples_split=20;, score=0.600 total time=   1.9s
[CV 5/5] END max_depth=8, min_samples_leaf=20, min_samples_split=20;, score=0.618 total time=   1.9s
[CV 1/5] END max_depth=14, min_samples_leaf=19, min_samples_split=21;, score=0.667 total time=   2.2s
[CV 2/5] END max_depth=14, min_samples_leaf=19, min_samples_split=21;, score=0.639 total time=   2.2s
[CV 3/5] END max_depth=14, min_samples_leaf=19, min_samples_split=21;, score=0.637 total time=   2.1s
[CV 4/5] END max_depth=14, min_samples_leaf=19, min_samples_split=21;, score=0.634 total time=   2.1s
[CV 5/5] END max_depth=14, min_samples_leaf=19, min_samples_split=21;, score=0.647 total time=   2.2s
[CV 1/5] END max_depth=11, min_samples_leaf=24, min_samples_split=23;, score=0.672 total time=   2.0s
[CV 2/5] END max_depth=11, min_samples_leaf=24, min_samples_split=23;, score=0.637 total time=   2.0s
[CV 3/5] END max_depth=11, min_samples_leaf=24, min_samples_split=23;, score=0.625 total time=   2.0s
[CV 4/5] END max_depth=11, min_samples_leaf=24, min_samples_split=23;, score=0.625 total time=   2.0s
[CV 5/5] END max_depth=11, min_samples_leaf=24, min_samples_split=23;, score=0.635 total time=   2.0s
[CV 1/5] END max_depth=13, min_samples_leaf=24, min_samples_split=23;, score=0.674 total time=   2.0s
[CV 2/5] END max_depth=13, min_samples_leaf=24, min_samples_split=23;, score=0.631 total time=   2.0s
[CV 3/5] END max_depth=13, min_samples_leaf=24, min_samples_split=23;, score=0.629 total time=   2.0s
[CV 4/5] END max_depth=13, min_samples_leaf=24, min_samples_split=23;, score=0.627 total time=   2.0s
[CV 5/5] END max_depth=13, min_samples_leaf=24, min_samples_split=23;, score=0.649 total time=   2.0s
[CV 1/5] END max_depth=10, min_samples_leaf=21, min_samples_split=16;, score=0.673 total time=   2.0s
[CV 2/5] END max_depth=10, min_samples_leaf=21, min_samples_split=16;, score=0.632 total time=   2.0s
[CV 3/5] END max_depth=10, min_samples_leaf=21, min_samples_split=16;, score=0.630 total time=   2.1s
[CV 4/5] END max_depth=10, min_samples_leaf=21, min_samples_split=16;, score=0.619 total time=   2.0s
[CV 5/5] END max_depth=10, min_samples_leaf=21, min_samples_split=16;, score=0.634 total time=   2.1s
[CV 1/5] END max_depth=11, min_samples_leaf=18, min_samples_split=12;, score=0.674 total time=   2.1s
[CV 2/5] END max_depth=11, min_samples_leaf=18, min_samples_split=12;, score=0.630 total time=   2.1s
[CV 3/5] END max_depth=11, min_samples_leaf=18, min_samples_split=12;, score=0.634 total time=   2.1s
[CV 4/5] END max_depth=11, min_samples_leaf=18, min_samples_split=12;, score=0.630 total time=   2.2s
[CV 5/5] END max_depth=11, min_samples_leaf=18, min_samples_split=12;, score=0.644 total time=   2.1s
[CV 1/5] END max_depth=12, min_samples_leaf=12, min_samples_split=16;, score=0.668 total time=   2.3s
[CV 2/5] END max_depth=12, min_samples_leaf=12, min_samples_split=16;, score=0.661 total time=   2.3s
[CV 3/5] END max_depth=12, min_samples_leaf=12, min_samples_split=16;, score=0.647 total time=   2.2s
[CV 4/5] END max_depth=12, min_samples_leaf=12, min_samples_split=16;, score=0.640 total time=   2.3s
[CV 5/5] END max_depth=12, min_samples_leaf=12, min_samples_split=16;, score=0.665 total time=   2.2s
[CV 1/5] END max_depth=12, min_samples_leaf=18, min_samples_split=16;, score=0.670 total time=   2.1s
[CV 2/5] END max_depth=12, min_samples_leaf=18, min_samples_split=16;, score=0.635 total time=   2.2s
[CV 3/5] END max_depth=12, min_samples_leaf=18, min_samples_split=16;, score=0.635 total time=   2.1s
[CV 4/5] END max_depth=12, min_samples_leaf=18, min_samples_split=16;, score=0.632 total time=   2.1s
[CV 5/5] END max_depth=12, min_samples_leaf=18, min_samples_split=16;, score=0.651 total time=   2.1s
[CV 1/5] END max_depth=9, min_samples_leaf=13, min_samples_split=18;, score=0.670 total time=   2.1s
[CV 2/5] END max_depth=9, min_samples_leaf=13, min_samples_split=18;, score=0.630 total time=   2.0s
[CV 3/5] END max_depth=9, min_samples_leaf=13, min_samples_split=18;, score=0.621 total time=   2.0s
[CV 4/5] END max_depth=9, min_samples_leaf=13, min_samples_split=18;, score=0.625 total time=   2.0s
[CV 5/5] END max_depth=9, min_samples_leaf=13, min_samples_split=18;, score=0.640 total time=   2.0s
[CV 1/5] END max_depth=11, min_samples_leaf=23, min_samples_split=11;, score=0.674 total time=   2.1s
[CV 2/5] END max_depth=11, min_samples_leaf=23, min_samples_split=11;, score=0.630 total time=   2.2s
[CV 3/5] END max_depth=11, min_samples_leaf=23, min_samples_split=11;, score=0.627 total time=   2.0s
[CV 4/5] END max_depth=11, min_samples_leaf=23, min_samples_split=11;, score=0.627 total time=   2.0s
[CV 5/5] END max_depth=11, min_samples_leaf=23, min_samples_split=11;, score=0.642 total time=   2.0s
[CV 1/5] END max_depth=9, min_samples_leaf=18, min_samples_split=19;, score=0.667 total time=   2.1s
[CV 2/5] END max_depth=9, min_samples_leaf=18, min_samples_split=19;, score=0.624 total time=   2.1s
[CV 3/5] END max_depth=9, min_samples_leaf=18, min_samples_split=19;, score=0.626 total time=   1.9s
[CV 4/5] END max_depth=9, min_samples_leaf=18, min_samples_split=19;, score=0.619 total time=   1.9s
[CV 5/5] END max_depth=9, min_samples_leaf=18, min_samples_split=19;, score=0.630 total time=   2.0s
[CV 1/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.675 total time=   2.3s
[CV 2/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.662 total time=   2.4s
[CV 3/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.649 total time=   2.3s
[CV 4/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.637 total time=   2.4s
[CV 5/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.656 total time=   2.3s
[CV 1/5] END max_depth=11, min_samples_leaf=24, min_samples_split=21;, score=0.672 total time=   2.0s
[CV 2/5] END max_depth=11, min_samples_leaf=24, min_samples_split=21;, score=0.637 total time=   2.0s
[CV 3/5] END max_depth=11, min_samples_leaf=24, min_samples_split=21;, score=0.625 total time=   2.0s
[CV 4/5] END max_depth=11, min_samples_leaf=24, min_samples_split=21;, score=0.625 total time=   2.0s
[CV 5/5] END max_depth=11, min_samples_leaf=24, min_samples_split=21;, score=0.635 total time=   2.0s
[CV 1/5] END max_depth=14, min_samples_leaf=21, min_samples_split=22;, score=0.665 total time=   2.1s
[CV 2/5] END max_depth=14, min_samples_leaf=21, min_samples_split=22;, score=0.637 total time=   2.2s
[CV 3/5] END max_depth=14, min_samples_leaf=21, min_samples_split=22;, score=0.632 total time=   2.1s
[CV 4/5] END max_depth=14, min_samples_leaf=21, min_samples_split=22;, score=0.630 total time=   2.1s
[CV 5/5] END max_depth=14, min_samples_leaf=21, min_samples_split=22;, score=0.651 total time=   2.1s
[CV 1/5] END max_depth=14, min_samples_leaf=12, min_samples_split=23;, score=0.670 total time=   3.4s
[CV 2/5] END max_depth=14, min_samples_leaf=12, min_samples_split=23;, score=0.661 total time=   2.7s
[CV 3/5] END max_depth=14, min_samples_leaf=12, min_samples_split=23;, score=0.651 total time=   2.5s
[CV 4/5] END max_depth=14, min_samples_leaf=12, min_samples_split=23;, score=0.640 total time=   2.4s
[CV 5/5] END max_depth=14, min_samples_leaf=12, min_samples_split=23;, score=0.670 total time=   2.5s
[CV 1/5] END max_depth=8, min_samples_leaf=13, min_samples_split=11;, score=0.657 total time=   2.0s
[CV 2/5] END max_depth=8, min_samples_leaf=13, min_samples_split=11;, score=0.623 total time=   2.0s
[CV 3/5] END max_depth=8, min_samples_leaf=13, min_samples_split=11;, score=0.619 total time=   2.0s
[CV 4/5] END max_depth=8, min_samples_leaf=13, min_samples_split=11;, score=0.610 total time=   2.0s
[CV 5/5] END max_depth=8, min_samples_leaf=13, min_samples_split=11;, score=0.625 total time=   2.1s
[CV 1/5] END max_depth=11, min_samples_leaf=11, min_samples_split=23;, score=0.679 total time=   2.4s
[CV 2/5] END max_depth=11, min_samples_leaf=11, min_samples_split=23;, score=0.666 total time=   2.4s
[CV 3/5] END max_depth=11, min_samples_leaf=11, min_samples_split=23;, score=0.645 total time=   2.3s
[CV 4/5] END max_depth=11, min_samples_leaf=11, min_samples_split=23;, score=0.631 total time=   2.4s
[CV 5/5] END max_depth=11, min_samples_leaf=11, min_samples_split=23;, score=0.659 total time=   2.4s
[CV 1/5] END max_depth=13, min_samples_leaf=15, min_samples_split=19;, score=0.669 total time=   2.5s
[CV 2/5] END max_depth=13, min_samples_leaf=15, min_samples_split=19;, score=0.647 total time=   2.5s
[CV 3/5] END max_depth=13, min_samples_leaf=15, min_samples_split=19;, score=0.652 total time=   2.3s
[CV 4/5] END max_depth=13, min_samples_leaf=15, min_samples_split=19;, score=0.636 total time=   2.3s
[CV 5/5] END max_depth=13, min_samples_leaf=15, min_samples_split=19;, score=0.654 total time=   2.4s
[CV 1/5] END max_depth=11, min_samples_leaf=15, min_samples_split=22;, score=0.670 total time=   2.4s
[CV 2/5] END max_depth=11, min_samples_leaf=15, min_samples_split=22;, score=0.640 total time=   2.4s
[CV 3/5] END max_depth=11, min_samples_leaf=15, min_samples_split=22;, score=0.644 total time=   2.4s
[CV 4/5] END max_depth=11, min_samples_leaf=15, min_samples_split=22;, score=0.636 total time=   2.4s
[CV 5/5] END max_depth=11, min_samples_leaf=15, min_samples_split=22;, score=0.646 total time=   2.3s
[CV 1/5] END max_depth=14, min_samples_leaf=11, min_samples_split=19;, score=0.677 total time=   2.8s
[CV 2/5] END max_depth=14, min_samples_leaf=11, min_samples_split=19;, score=0.666 total time=   2.6s
[CV 3/5] END max_depth=14, min_samples_leaf=11, min_samples_split=19;, score=0.642 total time=   2.5s
[CV 4/5] END max_depth=14, min_samples_leaf=11, min_samples_split=19;, score=0.645 total time=   2.5s
[CV 5/5] END max_depth=14, min_samples_leaf=11, min_samples_split=19;, score=0.662 total time=   2.5s
[CV 1/5] END max_depth=11, min_samples_leaf=11, min_samples_split=19;, score=0.682 total time=   2.4s
[CV 2/5] END max_depth=11, min_samples_leaf=11, min_samples_split=19;, score=0.666 total time=   2.4s
[CV 3/5] END max_depth=11, min_samples_leaf=11, min_samples_split=19;, score=0.649 total time=   2.4s
[CV 4/5] END max_depth=11, min_samples_leaf=11, min_samples_split=19;, score=0.630 total time=   2.4s
[CV 5/5] END max_depth=11, min_samples_leaf=11, min_samples_split=19;, score=0.655 total time=   2.4s
[CV 1/5] END max_depth=13, min_samples_leaf=13, min_samples_split=23;, score=0.668 total time=   2.4s
[CV 2/5] END max_depth=13, min_samples_leaf=13, min_samples_split=23;, score=0.659 total time=   2.4s
[CV 3/5] END max_depth=13, min_samples_leaf=13, min_samples_split=23;, score=0.649 total time=   2.4s
[CV 4/5] END max_depth=13, min_samples_leaf=13, min_samples_split=23;, score=0.640 total time=   2.4s
[CV 5/5] END max_depth=13, min_samples_leaf=13, min_samples_split=23;, score=0.661 total time=   2.5s
[CV 1/5] END max_depth=14, min_samples_leaf=24, min_samples_split=17;, score=0.670 total time=   2.2s
[CV 2/5] END max_depth=14, min_samples_leaf=24, min_samples_split=17;, score=0.637 total time=   2.3s
[CV 3/5] END max_depth=14, min_samples_leaf=24, min_samples_split=17;, score=0.626 total time=   2.2s
[CV 4/5] END max_depth=14, min_samples_leaf=24, min_samples_split=17;, score=0.627 total time=   2.3s
[CV 5/5] END max_depth=14, min_samples_leaf=24, min_samples_split=17;, score=0.649 total time=   2.3s
[CV 1/5] END max_depth=13, min_samples_leaf=16, min_samples_split=21;, score=0.670 total time=   2.4s
[CV 2/5] END max_depth=13, min_samples_leaf=16, min_samples_split=21;, score=0.642 total time=   2.5s
[CV 3/5] END max_depth=13, min_samples_leaf=16, min_samples_split=21;, score=0.642 total time=   2.3s
[CV 4/5] END max_depth=13, min_samples_leaf=16, min_samples_split=21;, score=0.636 total time=   2.4s
[CV 5/5] END max_depth=13, min_samples_leaf=16, min_samples_split=21;, score=0.654 total time=   2.4s
[CV 1/5] END max_depth=8, min_samples_leaf=23, min_samples_split=17;, score=0.655 total time=   1.9s
[CV 2/5] END max_depth=8, min_samples_leaf=23, min_samples_split=17;, score=0.623 total time=   2.0s
[CV 3/5] END max_depth=8, min_samples_leaf=23, min_samples_split=17;, score=0.605 total time=   1.9s
[CV 4/5] END max_depth=8, min_samples_leaf=23, min_samples_split=17;, score=0.601 total time=   1.9s
[CV 5/5] END max_depth=8, min_samples_leaf=23, min_samples_split=17;, score=0.618 total time=   2.0s
[CV 1/5] END max_depth=12, min_samples_leaf=22, min_samples_split=11;, score=0.663 total time=   2.3s
[CV 2/5] END max_depth=12, min_samples_leaf=22, min_samples_split=11;, score=0.640 total time=   2.3s
[CV 3/5] END max_depth=12, min_samples_leaf=22, min_samples_split=11;, score=0.635 total time=   2.4s
[CV 4/5] END max_depth=12, min_samples_leaf=22, min_samples_split=11;, score=0.630 total time=   2.3s
[CV 5/5] END max_depth=12, min_samples_leaf=22, min_samples_split=11;, score=0.647 total time=   2.2s
[CV 1/5] END max_depth=14, min_samples_leaf=14, min_samples_split=17;, score=0.679 total time=   2.4s
[CV 2/5] END max_depth=14, min_samples_leaf=14, min_samples_split=17;, score=0.649 total time=   2.6s
[CV 3/5] END max_depth=14, min_samples_leaf=14, min_samples_split=17;, score=0.651 total time=   2.4s
[CV 4/5] END max_depth=14, min_samples_leaf=14, min_samples_split=17;, score=0.640 total time=   2.4s
[CV 5/5] END max_depth=14, min_samples_leaf=14, min_samples_split=17;, score=0.661 total time=   2.5s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(max_features=None,
                                                    n_jobs=-1,
                                                    random_state=42),
                   n_iter=50,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002373F2CD0F0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002373F49AA90>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002373F2CD710>},
                   random_state=42, scoring='recall', verbose=3)

In [34]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
26,14,12,23,0.658582
31,14,11,19,0.658581
0,14,13,22,0.658082
18,12,12,16,0.656333
32,11,11,19,0.656330
23,12,11,13,0.656081
28,11,11,23,0.656080
38,14,14,17,0.656080
33,13,13,23,0.655333
42,12,10,18,0.654833
5,12,13,17,0.654333
2,12,14,16,0.653081
29,13,15,19,0.651833
8,13,15,11,0.651833
9,11,14,10,0.650581
35,13,16,21,0.649082
43,14,18,17,0.648832
30,11,15,22,0.647332
47,10,10,20,0.646582
13,14,19,21,0.644833
19,12,18,16,0.644832
6,10,15,14,0.644333
25,14,21,22,0.643334
37,12,22,11,0.643084
48,12,19,16,0.642583
45,14,20,12,0.642334
1,14,20,17,0.642334
17,11,18,12,0.642331
10,11,19,15,0.642331
11,12,21,18,0.642083
34,14,24,17,0.642082
15,13,24,23,0.642081
21,11,23,11,0.640331
40,11,21,22,0.639582
24,11,24,21,0.638832
14,11,24,23,0.638832
16,10,21,16,0.637582
20,9,13,18,0.637332
7,9,17,21,0.636833
4,10,20,17,0.636334
3,9,12,16,0.635084
39,9,18,21,0.633083
49,9,18,21,0.633083
22,9,18,19,0.633083
46,8,17,12,0.626835
27,8,13,11,0.626586
44,8,21,17,0.624086
12,8,20,20,0.622086
41,8,22,24,0.620587
36,8,23,17,0.620336

In [35]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 14, 'min_samples_leaf': 12, 'min_samples_split': 23}
Best CV score: 0.6585823970037453

In [36]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.90      0.88      4288
           1       0.89      0.86      0.87      4001

    accuracy                           0.88      8289
   macro avg       0.88      0.88      0.88      8289
weighted avg       0.88      0.88      0.88      8289

#### Evaluación

In [37]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.79      0.78       663
           1       0.77      0.74      0.76       633

    accuracy                           0.77      1296
   macro avg       0.77      0.77      0.77      1296
weighted avg       0.77      0.77      0.77      1296

#### Guardado

In [38]:
joblib.dump(best_model, f'./modelos/{dataset}/features_rf.pkl')

['./modelos/ciclos_c_r2/features_rf.pkl']