# Modelo

In [1]:
import numpy as np
import pandas as pd
import joblib

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import randint, uniform, norm, loguniform

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report, confusion_matrix

from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, GridSearchCV

from config import SEED

Elegimos dataset

In [2]:
dataset = 'ciclos_f2_r'

## Espectrogramas

Se suelen usar Mel espectrogramas

Traigo los consjuntos de entrenamiento y testeo. (TODO: buscar una manera más eficiente de guardarlos)

In [3]:
train_data = np.load(f'./dataset/{dataset}/train_melspectrogram.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_melspectrogram.npz')
X_test = test_data['X']
y_test = test_data['y']

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2642, 23808), (2642,), (303, 23808), (303,))

### Random Forest

#### Entrenamiento

In [5]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

param_distributions = {
    'max_depth': randint(8, 20),
    'min_samples_split': randint(5, 25),
    'min_samples_leaf': randint(5, 25)
}

In [6]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=20,
    scoring='recall',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END max_depth=14, min_samples_leaf=24, min_samples_split=19;, score=0.533 total time=   2.1s
[CV 2/5] END max_depth=14, min_samples_leaf=24, min_samples_split=19;, score=0.566 total time=   1.9s
[CV 3/5] END max_depth=14, min_samples_leaf=24, min_samples_split=19;, score=0.577 total time=   1.8s
[CV 4/5] END max_depth=14, min_samples_leaf=24, min_samples_split=19;, score=0.593 total time=   1.8s
[CV 5/5] END max_depth=14, min_samples_leaf=24, min_samples_split=19;, score=0.632 total time=   1.7s
[CV 1/5] END max_depth=18, min_samples_leaf=12, min_samples_split=11;, score=0.545 total time=   2.0s
[CV 2/5] END max_depth=18, min_samples_leaf=12, min_samples_split=11;, score=0.620 total time=   2.4s
[CV 3/5] END max_depth=18, min_samples_leaf=12, min_samples_split=11;, score=0.627 total time=   3.2s
[CV 4/5] END max_depth=18, min_samples_leaf=12, min_samples_split=11;, score=0.593 total time=   3.4s
[CV 5/5] END max_depth=18, min_samples_leaf=12, min_samples_split=11;, score=0.628 total time=   3.3s
[CV 1/5] END max_depth=17, min_samples_leaf=23, min_samples_split=15;, score=0.541 total time=   2.6s
[CV 2/5] END max_depth=17, min_samples_leaf=23, min_samples_split=15;, score=0.566 total time=   2.6s
[CV 3/5] END max_depth=17, min_samples_leaf=23, min_samples_split=15;, score=0.602 total time=   2.6s
[CV 4/5] END max_depth=17, min_samples_leaf=23, min_samples_split=15;, score=0.602 total time=   2.6s
[CV 5/5] END max_depth=17, min_samples_leaf=23, min_samples_split=15;, score=0.636 total time=   2.6s
[CV 1/5] END max_depth=18, min_samples_leaf=8, min_samples_split=12;, score=0.566 total time=   3.3s
[CV 2/5] END max_depth=18, min_samples_leaf=8, min_samples_split=12;, score=0.599 total time=   3.3s
[CV 3/5] END max_depth=18, min_samples_leaf=8, min_samples_split=12;, score=0.647 total time=   3.3s
[CV 4/5] END max_depth=18, min_samples_leaf=8, min_samples_split=12;, score=0.560 total time=   3.9s
[CV 5/5] END max_depth=18, min_samples_leaf=8, min_samples_split=12;, score=0.653 total time=   3.9s
[CV 1/5] END max_depth=15, min_samples_leaf=7, min_samples_split=6;, score=0.570 total time=   3.4s
[CV 2/5] END max_depth=15, min_samples_leaf=7, min_samples_split=6;, score=0.603 total time=   3.3s
[CV 3/5] END max_depth=15, min_samples_leaf=7, min_samples_split=6;, score=0.643 total time=   3.2s
[CV 4/5] END max_depth=15, min_samples_leaf=7, min_samples_split=6;, score=0.627 total time=   3.2s
[CV 5/5] END max_depth=15, min_samples_leaf=7, min_samples_split=6;, score=0.682 total time=   3.3s
[CV 1/5] END max_depth=15, min_samples_leaf=16, min_samples_split=10;, score=0.545 total time=   2.7s
[CV 2/5] END max_depth=15, min_samples_leaf=16, min_samples_split=10;, score=0.595 total time=   2.8s
[CV 3/5] END max_depth=15, min_samples_leaf=16, min_samples_split=10;, score=0.593 total time=   2.7s
[CV 4/5] END max_depth=15, min_samples_leaf=16, min_samples_split=10;, score=0.602 total time=   2.8s
[CV 5/5] END max_depth=15, min_samples_leaf=16, min_samples_split=10;, score=0.640 total time=   2.8s
[CV 1/5] END max_depth=9, min_samples_leaf=5, min_samples_split=16;, score=0.566 total time=   3.0s
[CV 2/5] END max_depth=9, min_samples_leaf=5, min_samples_split=16;, score=0.603 total time=   3.1s
[CV 3/5] END max_depth=9, min_samples_leaf=5, min_samples_split=16;, score=0.651 total time=   3.0s
[CV 4/5] END max_depth=9, min_samples_leaf=5, min_samples_split=16;, score=0.614 total time=   3.4s
[CV 5/5] END max_depth=9, min_samples_leaf=5, min_samples_split=16;, score=0.686 total time=   3.1s
[CV 1/5] END max_depth=17, min_samples_leaf=16, min_samples_split=21;, score=0.537 total time=   2.8s
[CV 2/5] END max_depth=17, min_samples_leaf=16, min_samples_split=21;, score=0.599 total time=   2.7s
[CV 3/5] END max_depth=17, min_samples_leaf=16, min_samples_split=21;, score=0.598 total time=   2.8s
[CV 4/5] END max_depth=17, min_samples_leaf=16, min_samples_split=21;, score=0.598 total time=   2.7s
[CV 5/5] END max_depth=17, min_samples_leaf=16, min_samples_split=21;, score=0.632 total time=   2.8s
[CV 1/5] END max_depth=18, min_samples_leaf=14, min_samples_split=20;, score=0.529 total time=   3.0s
[CV 2/5] END max_depth=18, min_samples_leaf=14, min_samples_split=20;, score=0.587 total time=   2.9s
[CV 3/5] END max_depth=18, min_samples_leaf=14, min_samples_split=20;, score=0.602 total time=   2.9s
[CV 4/5] END max_depth=18, min_samples_leaf=14, min_samples_split=20;, score=0.598 total time=   2.8s
[CV 5/5] END max_depth=18, min_samples_leaf=14, min_samples_split=20;, score=0.669 total time=   2.9s
[CV 1/5] END max_depth=10, min_samples_leaf=16, min_samples_split=24;, score=0.525 total time=   2.7s
[CV 2/5] END max_depth=10, min_samples_leaf=16, min_samples_split=24;, score=0.599 total time=   2.7s
[CV 3/5] END max_depth=10, min_samples_leaf=16, min_samples_split=24;, score=0.614 total time=   2.7s
[CV 4/5] END max_depth=10, min_samples_leaf=16, min_samples_split=24;, score=0.602 total time=   2.6s
[CV 5/5] END max_depth=10, min_samples_leaf=16, min_samples_split=24;, score=0.632 total time=   2.7s
[CV 1/5] END max_depth=16, min_samples_leaf=7, min_samples_split=9;, score=0.570 total time=   3.5s
[CV 2/5] END max_depth=16, min_samples_leaf=7, min_samples_split=9;, score=0.583 total time=   3.4s
[CV 3/5] END max_depth=16, min_samples_leaf=7, min_samples_split=9;, score=0.631 total time=   3.3s
[CV 4/5] END max_depth=16, min_samples_leaf=7, min_samples_split=9;, score=0.622 total time=   3.3s
[CV 5/5] END max_depth=16, min_samples_leaf=7, min_samples_split=9;, score=0.674 total time=   3.2s
[CV 1/5] END max_depth=10, min_samples_leaf=11, min_samples_split=13;, score=0.550 total time=   2.9s
[CV 2/5] END max_depth=10, min_samples_leaf=11, min_samples_split=13;, score=0.591 total time=   2.9s
[CV 3/5] END max_depth=10, min_samples_leaf=11, min_samples_split=13;, score=0.598 total time=   2.9s
[CV 4/5] END max_depth=10, min_samples_leaf=11, min_samples_split=13;, score=0.577 total time=   2.9s
[CV 5/5] END max_depth=10, min_samples_leaf=11, min_samples_split=13;, score=0.640 total time=   2.9s
[CV 1/5] END max_depth=14, min_samples_leaf=22, min_samples_split=8;, score=0.517 total time=   2.6s
[CV 2/5] END max_depth=14, min_samples_leaf=22, min_samples_split=8;, score=0.570 total time=   3.2s
[CV 3/5] END max_depth=14, min_samples_leaf=22, min_samples_split=8;, score=0.585 total time=   2.7s
[CV 4/5] END max_depth=14, min_samples_leaf=22, min_samples_split=8;, score=0.602 total time=   3.1s
[CV 5/5] END max_depth=14, min_samples_leaf=22, min_samples_split=8;, score=0.657 total time=   2.8s
[CV 1/5] END max_depth=16, min_samples_leaf=18, min_samples_split=22;, score=0.525 total time=   3.0s
[CV 2/5] END max_depth=16, min_samples_leaf=18, min_samples_split=22;, score=0.587 total time=   2.8s
[CV 3/5] END max_depth=16, min_samples_leaf=18, min_samples_split=22;, score=0.618 total time=   2.7s
[CV 4/5] END max_depth=16, min_samples_leaf=18, min_samples_split=22;, score=0.573 total time=   2.7s
[CV 5/5] END max_depth=16, min_samples_leaf=18, min_samples_split=22;, score=0.620 total time=   2.9s
[CV 1/5] END max_depth=17, min_samples_leaf=13, min_samples_split=6;, score=0.550 total time=   2.9s
[CV 2/5] END max_depth=17, min_samples_leaf=13, min_samples_split=6;, score=0.579 total time=   3.0s
[CV 3/5] END max_depth=17, min_samples_leaf=13, min_samples_split=6;, score=0.568 total time=   2.9s
[CV 4/5] END max_depth=17, min_samples_leaf=13, min_samples_split=6;, score=0.598 total time=   2.9s
[CV 5/5] END max_depth=17, min_samples_leaf=13, min_samples_split=6;, score=0.665 total time=   2.9s
[CV 1/5] END max_depth=11, min_samples_leaf=19, min_samples_split=11;, score=0.541 total time=   2.7s
[CV 2/5] END max_depth=11, min_samples_leaf=19, min_samples_split=11;, score=0.599 total time=   2.7s
[CV 3/5] END max_depth=11, min_samples_leaf=19, min_samples_split=11;, score=0.610 total time=   2.7s
[CV 4/5] END max_depth=11, min_samples_leaf=19, min_samples_split=11;, score=0.568 total time=   2.6s
[CV 5/5] END max_depth=11, min_samples_leaf=19, min_samples_split=11;, score=0.636 total time=   2.7s
[CV 1/5] END max_depth=19, min_samples_leaf=12, min_samples_split=19;, score=0.545 total time=   3.2s
[CV 2/5] END max_depth=19, min_samples_leaf=12, min_samples_split=19;, score=0.616 total time=   3.0s
[CV 3/5] END max_depth=19, min_samples_leaf=12, min_samples_split=19;, score=0.627 total time=   3.0s
[CV 4/5] END max_depth=19, min_samples_leaf=12, min_samples_split=19;, score=0.593 total time=   3.0s
[CV 5/5] END max_depth=19, min_samples_leaf=12, min_samples_split=19;, score=0.628 total time=   2.8s
[CV 1/5] END max_depth=10, min_samples_leaf=18, min_samples_split=21;, score=0.517 total time=   2.7s
[CV 2/5] END max_depth=10, min_samples_leaf=18, min_samples_split=21;, score=0.591 total time=   2.7s
[CV 3/5] END max_depth=10, min_samples_leaf=18, min_samples_split=21;, score=0.614 total time=   2.7s
[CV 4/5] END max_depth=10, min_samples_leaf=18, min_samples_split=21;, score=0.589 total time=   2.6s
[CV 5/5] END max_depth=10, min_samples_leaf=18, min_samples_split=21;, score=0.636 total time=   2.6s
[CV 1/5] END max_depth=11, min_samples_leaf=22, min_samples_split=12;, score=0.521 total time=   2.6s
[CV 2/5] END max_depth=11, min_samples_leaf=22, min_samples_split=12;, score=0.579 total time=   2.5s
[CV 3/5] END max_depth=11, min_samples_leaf=22, min_samples_split=12;, score=0.589 total time=   2.6s
[CV 4/5] END max_depth=11, min_samples_leaf=22, min_samples_split=12;, score=0.606 total time=   2.6s
[CV 5/5] END max_depth=11, min_samples_leaf=22, min_samples_split=12;, score=0.640 total time=   2.6s
[CV 1/5] END max_depth=11, min_samples_leaf=6, min_samples_split=10;, score=0.541 total time=   3.2s
[CV 2/5] END max_depth=11, min_samples_leaf=6, min_samples_split=10;, score=0.595 total time=   3.2s
[CV 3/5] END max_depth=11, min_samples_leaf=6, min_samples_split=10;, score=0.631 total time=   3.2s
[CV 4/5] END max_depth=11, min_samples_leaf=6, min_samples_split=10;, score=0.618 total time=   3.2s
[CV 5/5] END max_depth=11, min_samples_leaf=6, min_samples_split=10;, score=0.678 total time=   3.2s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=20,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F83535EA50>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F8353B4190>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F8028B39D0>},
                   random_state=42, scoring='recall', verbose=3)

In [7]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(20)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
4,15,7,6,0.625016
6,9,5,16,0.624186
10,16,7,9,0.615912
19,11,6,10,0.612602
3,18,8,12,0.605130
1,18,12,11,0.602661
16,19,12,19,0.601835
8,18,14,20,0.596859
5,15,16,10,0.595202
9,10,16,24,0.594393
7,17,16,21,0.592723
14,17,13,6,0.591873
15,11,19,11,0.591057
11,10,11,13,0.591053
17,10,18,21,0.589424
2,17,23,15,0.589424
18,11,22,12,0.586938
12,14,22,8,0.586105
13,16,18,22,0.584455
0,14,24,19,0.580306

In [8]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 15, 'min_samples_leaf': 7, 'min_samples_split': 6}
Best CV score: 0.6250162888789822

In [9]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1434
           1       0.99      0.97      0.98      1208

    accuracy                           0.98      2642
   macro avg       0.98      0.98      0.98      2642
weighted avg       0.98      0.98      0.98      2642

#### Evaluación

In [10]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.86      0.80       180
           1       0.74      0.58      0.65       123

    accuracy                           0.75       303
   macro avg       0.74      0.72      0.72       303
weighted avg       0.75      0.75      0.74       303

#### Guardado

In [11]:
joblib.dump(best_model, f'./modelos/{dataset}/melspec_rf.pkl')

['./modelos/ciclos_f2_r/melspec_rf.pkl']

## Atributos de Audio

1. Resample y Filtro pasa bajos
2. Feature Extractor
    + MFCC (13)
    + ZCR
    + Short-Time Energy
    + SC
    + Spectral Roll-off
    + BER
    + Spectral Flatness

In [12]:
train_data = np.load(f'./dataset/{dataset}/train_features.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_features.npz')
X_test = test_data['X']
y_test = test_data['y']

In [13]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2642, 19), (2642,), (303, 19), (303,))

### Random Forest

#### Entrenamiento

In [14]:
rf = RandomForestClassifier(random_state=42, max_features=None, n_jobs=-1)

param_distributions = {
    'max_depth': randint(5, 20),
    'min_samples_split': randint(5, 25),
    'min_samples_leaf': randint(5, 25)
}

In [15]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='recall',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.504 total time=   0.4s
[CV 2/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.550 total time=   0.3s
[CV 3/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.519 total time=   0.3s
[CV 4/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.614 total time=   0.4s
[CV 5/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.570 total time=   0.3s
[CV 1/5] END max_depth=15, min_samples_leaf=12, min_samples_split=11;, score=0.574 total time=   0.4s
[CV 2/5] END max_depth=15, min_samples_leaf=12, min_samples_split=11;, score=0.583 total time=   0.4s
[CV 3/5] END max_depth=15, min_samples_leaf=12, min_samples_split=11;, score=0.573 total time=   0.4s
[CV 4/5] END max_depth=15, min_samples_leaf=12, min_samples_split=11;, score=0.676 total time=   0.4s
[CV 5/5] END max_depth=15, min_samples_leaf=12, min_samples_split=11;, score=0.669 total time=   0.3s
[CV 1/5] END max_depth=14, min_samples_leaf=23, min_samples_split=15;, score=0.512 total time=   0.3s
[CV 2/5] END max_depth=14, min_samples_leaf=23, min_samples_split=15;, score=0.566 total time=   0.3s
[CV 3/5] END max_depth=14, min_samples_leaf=23, min_samples_split=15;, score=0.527 total time=   0.3s
[CV 4/5] END max_depth=14, min_samples_leaf=23, min_samples_split=15;, score=0.627 total time=   0.3s
[CV 5/5] END max_depth=14, min_samples_leaf=23, min_samples_split=15;, score=0.579 total time=   0.3s
[CV 1/5] END max_depth=15, min_samples_leaf=8, min_samples_split=12;, score=0.583 total time=   0.4s
[CV 2/5] END max_depth=15, min_samples_leaf=8, min_samples_split=12;, score=0.603 total time=   0.4s
[CV 3/5] END max_depth=15, min_samples_leaf=8, min_samples_split=12;, score=0.614 total time=   0.4s
[CV 4/5] END max_depth=15, min_samples_leaf=8, min_samples_split=12;, score=0.705 total time=   0.4s
[CV 5/5] END max_depth=15, min_samples_leaf=8, min_samples_split=12;, score=0.674 total time=   0.4s
[CV 1/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.595 total time=   0.4s
[CV 2/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.599 total time=   0.4s
[CV 3/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.581 total time=   0.4s
[CV 4/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.672 total time=   0.4s
[CV 5/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.661 total time=   0.4s
[CV 1/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.541 total time=   0.4s
[CV 2/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.574 total time=   0.3s
[CV 3/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.539 total time=   0.4s
[CV 4/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.643 total time=   0.3s
[CV 5/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.628 total time=   0.3s
[CV 1/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.467 total time=   0.3s
[CV 2/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.521 total time=   0.3s
[CV 3/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.440 total time=   0.3s
[CV 4/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.515 total time=   0.3s
[CV 5/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.537 total time=   0.3s
[CV 1/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.545 total time=   0.5s
[CV 2/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.579 total time=   0.6s
[CV 3/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.556 total time=   0.6s
[CV 4/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.651 total time=   0.6s
[CV 5/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.624 total time=   0.7s
[CV 1/5] END max_depth=15, min_samples_leaf=14, min_samples_split=20;, score=0.566 total time=   0.6s
[CV 2/5] END max_depth=15, min_samples_leaf=14, min_samples_split=20;, score=0.587 total time=   0.6s
[CV 3/5] END max_depth=15, min_samples_leaf=14, min_samples_split=20;, score=0.556 total time=   0.6s
[CV 4/5] END max_depth=15, min_samples_leaf=14, min_samples_split=20;, score=0.672 total time=   0.6s
[CV 5/5] END max_depth=15, min_samples_leaf=14, min_samples_split=20;, score=0.649 total time=   0.6s
[CV 1/5] END max_depth=19, min_samples_leaf=19, min_samples_split=23;, score=0.537 total time=   0.6s
[CV 2/5] END max_depth=19, min_samples_leaf=19, min_samples_split=23;, score=0.574 total time=   0.6s
[CV 3/5] END max_depth=19, min_samples_leaf=19, min_samples_split=23;, score=0.544 total time=   0.6s
[CV 4/5] END max_depth=19, min_samples_leaf=19, min_samples_split=23;, score=0.631 total time=   0.6s
[CV 5/5] END max_depth=19, min_samples_leaf=19, min_samples_split=23;, score=0.612 total time=   0.6s
[CV 1/5] END max_depth=16, min_samples_leaf=24, min_samples_split=7;, score=0.512 total time=   0.5s
[CV 2/5] END max_depth=16, min_samples_leaf=24, min_samples_split=7;, score=0.566 total time=   0.5s
[CV 3/5] END max_depth=16, min_samples_leaf=24, min_samples_split=7;, score=0.523 total time=   0.6s
[CV 4/5] END max_depth=16, min_samples_leaf=24, min_samples_split=7;, score=0.622 total time=   0.5s
[CV 5/5] END max_depth=16, min_samples_leaf=24, min_samples_split=7;, score=0.574 total time=   0.5s
[CV 1/5] END max_depth=9, min_samples_leaf=23, min_samples_split=11;, score=0.496 total time=   0.5s
[CV 2/5] END max_depth=9, min_samples_leaf=23, min_samples_split=11;, score=0.537 total time=   0.5s
[CV 3/5] END max_depth=9, min_samples_leaf=23, min_samples_split=11;, score=0.485 total time=   0.5s
[CV 4/5] END max_depth=9, min_samples_leaf=23, min_samples_split=11;, score=0.593 total time=   0.5s
[CV 5/5] END max_depth=9, min_samples_leaf=23, min_samples_split=11;, score=0.545 total time=   0.5s
[CV 1/5] END max_depth=9, min_samples_leaf=13, min_samples_split=11;, score=0.517 total time=   0.6s
[CV 2/5] END max_depth=9, min_samples_leaf=13, min_samples_split=11;, score=0.550 total time=   0.6s
[CV 3/5] END max_depth=9, min_samples_leaf=13, min_samples_split=11;, score=0.502 total time=   0.7s
[CV 4/5] END max_depth=9, min_samples_leaf=13, min_samples_split=11;, score=0.602 total time=   0.6s
[CV 5/5] END max_depth=9, min_samples_leaf=13, min_samples_split=11;, score=0.612 total time=   0.6s
[CV 1/5] END max_depth=6, min_samples_leaf=8, min_samples_split=18;, score=0.467 total time=   0.6s
[CV 2/5] END max_depth=6, min_samples_leaf=8, min_samples_split=18;, score=0.529 total time=   0.6s
[CV 3/5] END max_depth=6, min_samples_leaf=8, min_samples_split=18;, score=0.432 total time=   0.5s
[CV 4/5] END max_depth=6, min_samples_leaf=8, min_samples_split=18;, score=0.510 total time=   0.6s
[CV 5/5] END max_depth=6, min_samples_leaf=8, min_samples_split=18;, score=0.521 total time=   0.9s
[CV 1/5] END max_depth=6, min_samples_leaf=13, min_samples_split=6;, score=0.450 total time=   0.6s
[CV 2/5] END max_depth=6, min_samples_leaf=13, min_samples_split=6;, score=0.512 total time=   0.6s
[CV 3/5] END max_depth=6, min_samples_leaf=13, min_samples_split=6;, score=0.427 total time=   0.6s
[CV 4/5] END max_depth=6, min_samples_leaf=13, min_samples_split=6;, score=0.494 total time=   0.6s
[CV 5/5] END max_depth=6, min_samples_leaf=13, min_samples_split=6;, score=0.521 total time=   0.6s
[CV 1/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.504 total time=   0.6s
[CV 2/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.521 total time=   0.6s
[CV 3/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.452 total time=   0.6s
[CV 4/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.556 total time=   0.7s
[CV 5/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.554 total time=   0.6s
[CV 1/5] END max_depth=16, min_samples_leaf=12, min_samples_split=19;, score=0.574 total time=   0.8s
[CV 2/5] END max_depth=16, min_samples_leaf=12, min_samples_split=19;, score=0.583 total time=   0.7s
[CV 3/5] END max_depth=16, min_samples_leaf=12, min_samples_split=19;, score=0.568 total time=   0.8s
[CV 4/5] END max_depth=16, min_samples_leaf=12, min_samples_split=19;, score=0.672 total time=   0.7s
[CV 5/5] END max_depth=16, min_samples_leaf=12, min_samples_split=19;, score=0.665 total time=   0.7s
[CV 1/5] END max_depth=7, min_samples_leaf=18, min_samples_split=21;, score=0.479 total time=   0.6s
[CV 2/5] END max_depth=7, min_samples_leaf=18, min_samples_split=21;, score=0.521 total time=   0.6s
[CV 3/5] END max_depth=7, min_samples_leaf=18, min_samples_split=21;, score=0.432 total time=   0.6s
[CV 4/5] END max_depth=7, min_samples_leaf=18, min_samples_split=21;, score=0.519 total time=   0.6s
[CV 5/5] END max_depth=7, min_samples_leaf=18, min_samples_split=21;, score=0.529 total time=   0.6s
[CV 1/5] END max_depth=8, min_samples_leaf=22, min_samples_split=12;, score=0.492 total time=   0.6s
[CV 2/5] END max_depth=8, min_samples_leaf=22, min_samples_split=12;, score=0.521 total time=   0.6s
[CV 3/5] END max_depth=8, min_samples_leaf=22, min_samples_split=12;, score=0.465 total time=   0.6s
[CV 4/5] END max_depth=8, min_samples_leaf=22, min_samples_split=12;, score=0.556 total time=   0.6s
[CV 5/5] END max_depth=8, min_samples_leaf=22, min_samples_split=12;, score=0.550 total time=   0.6s
[CV 1/5] END max_depth=8, min_samples_leaf=6, min_samples_split=10;, score=0.525 total time=   0.7s
[CV 2/5] END max_depth=8, min_samples_leaf=6, min_samples_split=10;, score=0.562 total time=   0.7s
[CV 3/5] END max_depth=8, min_samples_leaf=6, min_samples_split=10;, score=0.485 total time=   0.7s
[CV 4/5] END max_depth=8, min_samples_leaf=6, min_samples_split=10;, score=0.614 total time=   0.7s
[CV 5/5] END max_depth=8, min_samples_leaf=6, min_samples_split=10;, score=0.612 total time=   0.7s
[CV 1/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.537 total time=   0.7s
[CV 2/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.570 total time=   0.7s
[CV 3/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.519 total time=   0.7s
[CV 4/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.639 total time=   0.7s
[CV 5/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.616 total time=   0.7s
[CV 1/5] END max_depth=10, min_samples_leaf=22, min_samples_split=16;, score=0.504 total time=   0.7s
[CV 2/5] END max_depth=10, min_samples_leaf=22, min_samples_split=16;, score=0.558 total time=   0.7s
[CV 3/5] END max_depth=10, min_samples_leaf=22, min_samples_split=16;, score=0.506 total time=   0.7s
[CV 4/5] END max_depth=10, min_samples_leaf=22, min_samples_split=16;, score=0.606 total time=   0.6s
[CV 5/5] END max_depth=10, min_samples_leaf=22, min_samples_split=16;, score=0.558 total time=   0.6s
[CV 1/5] END max_depth=6, min_samples_leaf=14, min_samples_split=8;, score=0.459 total time=   0.6s
[CV 2/5] END max_depth=6, min_samples_leaf=14, min_samples_split=8;, score=0.517 total time=   0.5s
[CV 3/5] END max_depth=6, min_samples_leaf=14, min_samples_split=8;, score=0.432 total time=   0.6s
[CV 4/5] END max_depth=6, min_samples_leaf=14, min_samples_split=8;, score=0.502 total time=   0.6s
[CV 5/5] END max_depth=6, min_samples_leaf=14, min_samples_split=8;, score=0.517 total time=   0.7s
[CV 1/5] END max_depth=18, min_samples_leaf=20, min_samples_split=19;, score=0.525 total time=   0.7s
[CV 2/5] END max_depth=18, min_samples_leaf=20, min_samples_split=19;, score=0.570 total time=   0.7s
[CV 3/5] END max_depth=18, min_samples_leaf=20, min_samples_split=19;, score=0.544 total time=   0.7s
[CV 4/5] END max_depth=18, min_samples_leaf=20, min_samples_split=19;, score=0.643 total time=   0.7s
[CV 5/5] END max_depth=18, min_samples_leaf=20, min_samples_split=19;, score=0.612 total time=   0.6s
[CV 1/5] END max_depth=12, min_samples_leaf=18, min_samples_split=12;, score=0.541 total time=   0.7s
[CV 2/5] END max_depth=12, min_samples_leaf=18, min_samples_split=12;, score=0.562 total time=   0.7s
[CV 3/5] END max_depth=12, min_samples_leaf=18, min_samples_split=12;, score=0.544 total time=   0.7s
[CV 4/5] END max_depth=12, min_samples_leaf=18, min_samples_split=12;, score=0.635 total time=   0.7s
[CV 5/5] END max_depth=12, min_samples_leaf=18, min_samples_split=12;, score=0.632 total time=   0.7s
[CV 1/5] END max_depth=9, min_samples_leaf=20, min_samples_split=17;, score=0.504 total time=   0.7s
[CV 2/5] END max_depth=9, min_samples_leaf=20, min_samples_split=17;, score=0.541 total time=   0.6s
[CV 3/5] END max_depth=9, min_samples_leaf=20, min_samples_split=17;, score=0.490 total time=   0.7s
[CV 4/5] END max_depth=9, min_samples_leaf=20, min_samples_split=17;, score=0.581 total time=   0.7s
[CV 5/5] END max_depth=9, min_samples_leaf=20, min_samples_split=17;, score=0.570 total time=   0.7s
[CV 1/5] END max_depth=6, min_samples_leaf=19, min_samples_split=17;, score=0.459 total time=   0.6s
[CV 2/5] END max_depth=6, min_samples_leaf=19, min_samples_split=17;, score=0.512 total time=   0.6s
[CV 3/5] END max_depth=6, min_samples_leaf=19, min_samples_split=17;, score=0.419 total time=   0.6s
[CV 4/5] END max_depth=6, min_samples_leaf=19, min_samples_split=17;, score=0.477 total time=   0.6s
[CV 5/5] END max_depth=6, min_samples_leaf=19, min_samples_split=17;, score=0.508 total time=   0.5s
[CV 1/5] END max_depth=13, min_samples_leaf=19, min_samples_split=17;, score=0.541 total time=   0.7s
[CV 2/5] END max_depth=13, min_samples_leaf=19, min_samples_split=17;, score=0.570 total time=   0.6s
[CV 3/5] END max_depth=13, min_samples_leaf=19, min_samples_split=17;, score=0.544 total time=   0.7s
[CV 4/5] END max_depth=13, min_samples_leaf=19, min_samples_split=17;, score=0.610 total time=   0.7s
[CV 5/5] END max_depth=13, min_samples_leaf=19, min_samples_split=17;, score=0.612 total time=   0.6s
[CV 1/5] END max_depth=5, min_samples_leaf=11, min_samples_split=13;, score=0.426 total time=   0.6s
[CV 2/5] END max_depth=5, min_samples_leaf=11, min_samples_split=13;, score=0.471 total time=   0.5s
[CV 3/5] END max_depth=5, min_samples_leaf=11, min_samples_split=13;, score=0.402 total time=   0.5s
[CV 4/5] END max_depth=5, min_samples_leaf=11, min_samples_split=13;, score=0.461 total time=   0.5s
[CV 5/5] END max_depth=5, min_samples_leaf=11, min_samples_split=13;, score=0.504 total time=   0.6s
[CV 1/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.587 total time=   0.8s
[CV 2/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.595 total time=   0.8s
[CV 3/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.602 total time=   0.8s
[CV 4/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.680 total time=   0.9s
[CV 5/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.669 total time=   0.8s
[CV 1/5] END max_depth=12, min_samples_leaf=15, min_samples_split=23;, score=0.550 total time=   0.7s
[CV 2/5] END max_depth=12, min_samples_leaf=15, min_samples_split=23;, score=0.574 total time=   0.7s
[CV 3/5] END max_depth=12, min_samples_leaf=15, min_samples_split=23;, score=0.544 total time=   0.7s
[CV 4/5] END max_depth=12, min_samples_leaf=15, min_samples_split=23;, score=0.656 total time=   0.7s
[CV 5/5] END max_depth=12, min_samples_leaf=15, min_samples_split=23;, score=0.620 total time=   0.7s
[CV 1/5] END max_depth=5, min_samples_leaf=12, min_samples_split=7;, score=0.434 total time=   0.5s
[CV 2/5] END max_depth=5, min_samples_leaf=12, min_samples_split=7;, score=0.471 total time=   0.6s
[CV 3/5] END max_depth=5, min_samples_leaf=12, min_samples_split=7;, score=0.402 total time=   0.5s
[CV 4/5] END max_depth=5, min_samples_leaf=12, min_samples_split=7;, score=0.461 total time=   0.5s
[CV 5/5] END max_depth=5, min_samples_leaf=12, min_samples_split=7;, score=0.492 total time=   0.6s
[CV 1/5] END max_depth=7, min_samples_leaf=5, min_samples_split=9;, score=0.521 total time=   0.6s
[CV 2/5] END max_depth=7, min_samples_leaf=5, min_samples_split=9;, score=0.545 total time=   0.6s
[CV 3/5] END max_depth=7, min_samples_leaf=5, min_samples_split=9;, score=0.465 total time=   0.6s
[CV 4/5] END max_depth=7, min_samples_leaf=5, min_samples_split=9;, score=0.560 total time=   0.7s
[CV 5/5] END max_depth=7, min_samples_leaf=5, min_samples_split=9;, score=0.550 total time=   0.6s
[CV 1/5] END max_depth=14, min_samples_leaf=11, min_samples_split=13;, score=0.570 total time=   0.8s
[CV 2/5] END max_depth=14, min_samples_leaf=11, min_samples_split=13;, score=0.595 total time=   0.8s
[CV 3/5] END max_depth=14, min_samples_leaf=11, min_samples_split=13;, score=0.577 total time=   0.7s
[CV 4/5] END max_depth=14, min_samples_leaf=11, min_samples_split=13;, score=0.672 total time=   0.7s
[CV 5/5] END max_depth=14, min_samples_leaf=11, min_samples_split=13;, score=0.669 total time=   0.8s
[CV 1/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.570 total time=   0.7s
[CV 2/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.595 total time=   0.7s
[CV 3/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.581 total time=   0.7s
[CV 4/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.676 total time=   0.8s
[CV 5/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.661 total time=   0.8s
[CV 1/5] END max_depth=12, min_samples_leaf=16, min_samples_split=6;, score=0.541 total time=   0.7s
[CV 2/5] END max_depth=12, min_samples_leaf=16, min_samples_split=6;, score=0.574 total time=   0.8s
[CV 3/5] END max_depth=12, min_samples_leaf=16, min_samples_split=6;, score=0.539 total time=   0.8s
[CV 4/5] END max_depth=12, min_samples_leaf=16, min_samples_split=6;, score=0.643 total time=   0.7s
[CV 5/5] END max_depth=12, min_samples_leaf=16, min_samples_split=6;, score=0.628 total time=   0.6s
[CV 1/5] END max_depth=5, min_samples_leaf=20, min_samples_split=9;, score=0.426 total time=   0.5s
[CV 2/5] END max_depth=5, min_samples_leaf=20, min_samples_split=9;, score=0.463 total time=   0.5s
[CV 3/5] END max_depth=5, min_samples_leaf=20, min_samples_split=9;, score=0.407 total time=   0.3s
[CV 4/5] END max_depth=5, min_samples_leaf=20, min_samples_split=9;, score=0.452 total time=   0.3s
[CV 5/5] END max_depth=5, min_samples_leaf=20, min_samples_split=9;, score=0.483 total time=   0.3s
[CV 1/5] END max_depth=7, min_samples_leaf=16, min_samples_split=12;, score=0.488 total time=   0.3s
[CV 2/5] END max_depth=7, min_samples_leaf=16, min_samples_split=12;, score=0.508 total time=   0.3s
[CV 3/5] END max_depth=7, min_samples_leaf=16, min_samples_split=12;, score=0.452 total time=   0.4s
[CV 4/5] END max_depth=7, min_samples_leaf=16, min_samples_split=12;, score=0.531 total time=   0.6s
[CV 5/5] END max_depth=7, min_samples_leaf=16, min_samples_split=12;, score=0.529 total time=   0.6s
[CV 1/5] END max_depth=10, min_samples_leaf=7, min_samples_split=5;, score=0.562 total time=   0.8s
[CV 2/5] END max_depth=10, min_samples_leaf=7, min_samples_split=5;, score=0.583 total time=   0.9s
[CV 3/5] END max_depth=10, min_samples_leaf=7, min_samples_split=5;, score=0.531 total time=   1.0s
[CV 4/5] END max_depth=10, min_samples_leaf=7, min_samples_split=5;, score=0.656 total time=   0.8s
[CV 5/5] END max_depth=10, min_samples_leaf=7, min_samples_split=5;, score=0.636 total time=   1.7s
[CV 1/5] END max_depth=7, min_samples_leaf=9, min_samples_split=19;, score=0.500 total time=   0.9s
[CV 2/5] END max_depth=7, min_samples_leaf=9, min_samples_split=19;, score=0.533 total time=   0.6s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(max_features=None,
                                                    n_jobs=-1,
                                                    random_state=42),
                   n_iter=50,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F8352CF820>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F8353429F0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001F8352CE8B0>},
                   random_state=42, scoring='recall', verbose=3)

In [16]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(10)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
40,18,7,5,0.639923
3,15,8,12,0.635801
29,12,5,16,0.626679
4,12,7,6,0.621697
34,16,11,13,0.616742
33,14,11,13,0.616735
48,17,11,23,0.615908
1,15,12,11,0.615082
42,15,13,19,0.612596
16,16,12,19,0.612596

In [17]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 18, 'min_samples_leaf': 7, 'min_samples_split': 5}
Best CV score: 0.6399231850759577

In [18]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94      1434
           1       0.94      0.92      0.93      1208

    accuracy                           0.94      2642
   macro avg       0.94      0.94      0.94      2642
weighted avg       0.94      0.94      0.94      2642

#### Evaluación

In [19]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       180
           1       0.79      0.65      0.71       123

    accuracy                           0.79       303
   macro avg       0.79      0.77      0.77       303
weighted avg       0.79      0.79      0.78       303

#### Guardado

In [20]:
joblib.dump(best_model, f'./modelos/{dataset}/features_rf.pkl')

['./modelos/ciclos_f2_r/features_rf.pkl']