# Modelo

In [1]:
import numpy as np
import pandas as pd
import joblib
import os

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import randint, uniform, norm, loguniform

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report

from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, GridSearchCV

from config import SEED

Elegimos dataset

In [2]:
dataset = 'ciclos_r_hl256_rms'

## Espectrogramas

Se suelen usar Mel espectrogramas

In [3]:
train_data = np.load(f'./dataset/{dataset}/train_melspectrogram.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_melspectrogram.npz')
X_test = test_data['X']
y_test = test_data['y']

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((9843, 47616), (9843,), (1296, 47616), (1296,))

### Random Forest

#### Entrenamiento

In [36]:
rf = RandomForestClassifier(random_state=SEED, n_jobs=-1, max_features='sqrt')
param_distributions = {
    'max_depth': randint(8, 20),
    'min_samples_split': randint(5, 20),
    'min_samples_leaf': randint(5, 20)
}

In [37]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=30,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV 1/5] END max_depth=14, min_samples_leaf=8, min_samples_split=17;, score=0.697 total time=  51.4s
[CV 2/5] END max_depth=14, min_samples_leaf=8, min_samples_split=17;, score=0.713 total time=  34.6s
[CV 3/5] END max_depth=14, min_samples_leaf=8, min_samples_split=17;, score=0.687 total time=  45.2s
[CV 4/5] END max_depth=14, min_samples_leaf=8, min_samples_split=17;, score=0.692 total time=  29.7s
[CV 5/5] END max_depth=14, min_samples_leaf=8, min_samples_split=17;, score=0.673 total time=  28.0s
[CV 1/5] END max_depth=18, min_samples_leaf=12, min_samples_split=17;, score=0.701 total time=  28.4s
[CV 2/5] END max_depth=18, min_samples_leaf=12, min_samples_split=17;, score=0.720 total time=  30.0s
[CV 3/5] END max_depth=18, min_samples_leaf=12, min_samples_split=17;, score=0.683 total time=  27.7s
[CV 4/5] END max_depth=18, min_samples_leaf=12, min_samples_split=17;, score=0.682 total time=  27.7s
[CV 5/5] END max_depth=18, min_samples_leaf=12, min_samples_split=17;, score=0.676 total time=  28.0s
[CV 1/5] END max_depth=12, min_samples_leaf=11, min_samples_split=14;, score=0.693 total time=  25.5s
[CV 2/5] END max_depth=12, min_samples_leaf=11, min_samples_split=14;, score=0.711 total time=  26.0s
[CV 3/5] END max_depth=12, min_samples_leaf=11, min_samples_split=14;, score=0.679 total time=  26.4s
[CV 4/5] END max_depth=12, min_samples_leaf=11, min_samples_split=14;, score=0.690 total time=  25.2s
[CV 5/5] END max_depth=12, min_samples_leaf=11, min_samples_split=14;, score=0.674 total time=  25.2s
[CV 1/5] END max_depth=10, min_samples_leaf=11, min_samples_split=15;, score=0.693 total time=  23.0s
[CV 2/5] END max_depth=10, min_samples_leaf=11, min_samples_split=15;, score=0.704 total time=  23.3s
[CV 3/5] END max_depth=10, min_samples_leaf=11, min_samples_split=15;, score=0.677 total time=  23.9s
[CV 4/5] END max_depth=10, min_samples_leaf=11, min_samples_split=15;, score=0.681 total time=  23.6s
[CV 5/5] END max_depth=10, min_samples_leaf=11, min_samples_split=15;, score=0.678 total time=  24.1s
[CV 1/5] END max_depth=18, min_samples_leaf=12, min_samples_split=9;, score=0.701 total time=  28.1s
[CV 2/5] END max_depth=18, min_samples_leaf=12, min_samples_split=9;, score=0.720 total time=  28.9s
[CV 3/5] END max_depth=18, min_samples_leaf=12, min_samples_split=9;, score=0.683 total time=  27.3s
[CV 4/5] END max_depth=18, min_samples_leaf=12, min_samples_split=9;, score=0.682 total time=  27.9s
[CV 5/5] END max_depth=18, min_samples_leaf=12, min_samples_split=9;, score=0.676 total time=  27.9s
[CV 1/5] END max_depth=11, min_samples_leaf=12, min_samples_split=12;, score=0.689 total time=  23.8s
[CV 2/5] END max_depth=11, min_samples_leaf=12, min_samples_split=12;, score=0.705 total time=  24.6s
[CV 3/5] END max_depth=11, min_samples_leaf=12, min_samples_split=12;, score=0.685 total time=  25.1s
[CV 4/5] END max_depth=11, min_samples_leaf=12, min_samples_split=12;, score=0.684 total time=  23.8s
[CV 5/5] END max_depth=11, min_samples_leaf=12, min_samples_split=12;, score=0.677 total time=  24.8s
[CV 1/5] END max_depth=10, min_samples_leaf=10, min_samples_split=9;, score=0.691 total time=  24.2s
[CV 2/5] END max_depth=10, min_samples_leaf=10, min_samples_split=9;, score=0.704 total time=  24.4s
[CV 3/5] END max_depth=10, min_samples_leaf=10, min_samples_split=9;, score=0.675 total time=  23.7s
[CV 4/5] END max_depth=10, min_samples_leaf=10, min_samples_split=9;, score=0.679 total time=  23.0s
[CV 5/5] END max_depth=10, min_samples_leaf=10, min_samples_split=9;, score=0.674 total time=  25.2s
[CV 1/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.683 total time=  21.7s
[CV 2/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.697 total time=  22.1s
[CV 3/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.675 total time=  22.2s
[CV 4/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.680 total time=  21.9s
[CV 5/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.666 total time=  22.1s
[CV 1/5] END max_depth=13, min_samples_leaf=6, min_samples_split=16;, score=0.690 total time=  27.7s
[CV 2/5] END max_depth=13, min_samples_leaf=6, min_samples_split=16;, score=0.708 total time=  28.3s
[CV 3/5] END max_depth=13, min_samples_leaf=6, min_samples_split=16;, score=0.685 total time=  27.6s
[CV 4/5] END max_depth=13, min_samples_leaf=6, min_samples_split=16;, score=0.682 total time=  27.5s
[CV 5/5] END max_depth=13, min_samples_leaf=6, min_samples_split=16;, score=0.678 total time=  27.4s
[CV 1/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.694 total time=  26.3s
[CV 2/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.711 total time=  28.0s
[CV 3/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.683 total time=  26.3s
[CV 4/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.687 total time=  26.6s
[CV 5/5] END max_depth=12, min_samples_leaf=5, min_samples_split=16;, score=0.678 total time=  27.5s
[CV 1/5] END max_depth=17, min_samples_leaf=10, min_samples_split=17;, score=0.696 total time=  28.1s
[CV 2/5] END max_depth=17, min_samples_leaf=10, min_samples_split=17;, score=0.711 total time=  29.2s
[CV 3/5] END max_depth=17, min_samples_leaf=10, min_samples_split=17;, score=0.687 total time=  28.4s
[CV 4/5] END max_depth=17, min_samples_leaf=10, min_samples_split=17;, score=0.689 total time=  28.2s
[CV 5/5] END max_depth=17, min_samples_leaf=10, min_samples_split=17;, score=0.678 total time=  29.2s
[CV 1/5] END max_depth=19, min_samples_leaf=13, min_samples_split=5;, score=0.696 total time=  28.5s
[CV 2/5] END max_depth=19, min_samples_leaf=13, min_samples_split=5;, score=0.718 total time=  28.6s
[CV 3/5] END max_depth=19, min_samples_leaf=13, min_samples_split=5;, score=0.686 total time=  27.9s
[CV 4/5] END max_depth=19, min_samples_leaf=13, min_samples_split=5;, score=0.685 total time=  27.0s
[CV 5/5] END max_depth=19, min_samples_leaf=13, min_samples_split=5;, score=0.682 total time=  28.7s
[CV 1/5] END max_depth=18, min_samples_leaf=15, min_samples_split=19;, score=0.694 total time=  26.5s
[CV 2/5] END max_depth=18, min_samples_leaf=15, min_samples_split=19;, score=0.702 total time=  27.9s
[CV 3/5] END max_depth=18, min_samples_leaf=15, min_samples_split=19;, score=0.689 total time=  27.0s
[CV 4/5] END max_depth=18, min_samples_leaf=15, min_samples_split=19;, score=0.684 total time=  26.9s
[CV 5/5] END max_depth=18, min_samples_leaf=15, min_samples_split=19;, score=0.671 total time=  27.2s
[CV 1/5] END max_depth=17, min_samples_leaf=16, min_samples_split=16;, score=0.692 total time=  26.7s
[CV 2/5] END max_depth=17, min_samples_leaf=16, min_samples_split=16;, score=0.710 total time=  27.4s
[CV 3/5] END max_depth=17, min_samples_leaf=16, min_samples_split=16;, score=0.691 total time=  28.3s
[CV 4/5] END max_depth=17, min_samples_leaf=16, min_samples_split=16;, score=0.690 total time=  26.5s
[CV 5/5] END max_depth=17, min_samples_leaf=16, min_samples_split=16;, score=0.677 total time=  26.5s
[CV 1/5] END max_depth=10, min_samples_leaf=16, min_samples_split=11;, score=0.687 total time=  23.5s
[CV 2/5] END max_depth=10, min_samples_leaf=16, min_samples_split=11;, score=0.702 total time=  23.1s
[CV 3/5] END max_depth=10, min_samples_leaf=16, min_samples_split=11;, score=0.673 total time=  23.0s
[CV 4/5] END max_depth=10, min_samples_leaf=16, min_samples_split=11;, score=0.675 total time=  22.9s
[CV 5/5] END max_depth=10, min_samples_leaf=16, min_samples_split=11;, score=0.671 total time=  22.9s
[CV 1/5] END max_depth=11, min_samples_leaf=13, min_samples_split=7;, score=0.691 total time=  23.8s
[CV 2/5] END max_depth=11, min_samples_leaf=13, min_samples_split=7;, score=0.702 total time=  25.0s
[CV 3/5] END max_depth=11, min_samples_leaf=13, min_samples_split=7;, score=0.680 total time=  24.1s
[CV 4/5] END max_depth=11, min_samples_leaf=13, min_samples_split=7;, score=0.677 total time=  24.0s
[CV 5/5] END max_depth=11, min_samples_leaf=13, min_samples_split=7;, score=0.677 total time=  22.7s
[CV 1/5] END max_depth=12, min_samples_leaf=7, min_samples_split=11;, score=0.691 total time=  25.6s
[CV 2/5] END max_depth=12, min_samples_leaf=7, min_samples_split=11;, score=0.708 total time=  24.9s
[CV 3/5] END max_depth=12, min_samples_leaf=7, min_samples_split=11;, score=0.682 total time=  24.1s
[CV 4/5] END max_depth=12, min_samples_leaf=7, min_samples_split=11;, score=0.691 total time=  24.3s
[CV 5/5] END max_depth=12, min_samples_leaf=7, min_samples_split=11;, score=0.676 total time=  24.0s
[CV 1/5] END max_depth=12, min_samples_leaf=13, min_samples_split=11;, score=0.688 total time=  23.3s
[CV 2/5] END max_depth=12, min_samples_leaf=13, min_samples_split=11;, score=0.705 total time=  25.8s
[CV 3/5] END max_depth=12, min_samples_leaf=13, min_samples_split=11;, score=0.681 total time=  31.7s
[CV 4/5] END max_depth=12, min_samples_leaf=13, min_samples_split=11;, score=0.684 total time=  24.3s
[CV 5/5] END max_depth=12, min_samples_leaf=13, min_samples_split=11;, score=0.674 total time=  23.1s
[CV 1/5] END max_depth=9, min_samples_leaf=8, min_samples_split=13;, score=0.683 total time=  20.6s
[CV 2/5] END max_depth=9, min_samples_leaf=8, min_samples_split=13;, score=0.703 total time=  25.9s
[CV 3/5] END max_depth=9, min_samples_leaf=8, min_samples_split=13;, score=0.669 total time=  21.5s
[CV 4/5] END max_depth=9, min_samples_leaf=8, min_samples_split=13;, score=0.674 total time=  22.7s
[CV 5/5] END max_depth=9, min_samples_leaf=8, min_samples_split=13;, score=0.672 total time=  22.5s
[CV 1/5] END max_depth=19, min_samples_leaf=18, min_samples_split=6;, score=0.696 total time=  28.1s
[CV 2/5] END max_depth=19, min_samples_leaf=18, min_samples_split=6;, score=0.706 total time=  27.9s
[CV 3/5] END max_depth=19, min_samples_leaf=18, min_samples_split=6;, score=0.682 total time=  27.2s
[CV 4/5] END max_depth=19, min_samples_leaf=18, min_samples_split=6;, score=0.691 total time=  26.6s
[CV 5/5] END max_depth=19, min_samples_leaf=18, min_samples_split=6;, score=0.679 total time=  27.8s
[CV 1/5] END max_depth=17, min_samples_leaf=13, min_samples_split=14;, score=0.691 total time=  27.7s
[CV 2/5] END max_depth=17, min_samples_leaf=13, min_samples_split=14;, score=0.715 total time=  28.7s
[CV 3/5] END max_depth=17, min_samples_leaf=13, min_samples_split=14;, score=0.684 total time=  27.2s
[CV 4/5] END max_depth=17, min_samples_leaf=13, min_samples_split=14;, score=0.689 total time=  26.3s
[CV 5/5] END max_depth=17, min_samples_leaf=13, min_samples_split=14;, score=0.679 total time=  27.6s
[CV 1/5] END max_depth=12, min_samples_leaf=6, min_samples_split=8;, score=0.703 total time=  28.1s
[CV 2/5] END max_depth=12, min_samples_leaf=6, min_samples_split=8;, score=0.704 total time=  27.0s
[CV 3/5] END max_depth=12, min_samples_leaf=6, min_samples_split=8;, score=0.683 total time=  26.2s
[CV 4/5] END max_depth=12, min_samples_leaf=6, min_samples_split=8;, score=0.689 total time=  25.7s
[CV 5/5] END max_depth=12, min_samples_leaf=6, min_samples_split=8;, score=0.680 total time=  25.8s
[CV 1/5] END max_depth=19, min_samples_leaf=19, min_samples_split=16;, score=0.695 total time=  26.1s
[CV 2/5] END max_depth=19, min_samples_leaf=19, min_samples_split=16;, score=0.700 total time=  27.3s
[CV 3/5] END max_depth=19, min_samples_leaf=19, min_samples_split=16;, score=0.682 total time=  26.1s
[CV 4/5] END max_depth=19, min_samples_leaf=19, min_samples_split=16;, score=0.685 total time=  26.2s
[CV 5/5] END max_depth=19, min_samples_leaf=19, min_samples_split=16;, score=0.673 total time=  27.0s
[CV 1/5] END max_depth=14, min_samples_leaf=16, min_samples_split=17;, score=0.691 total time=  23.5s
[CV 2/5] END max_depth=14, min_samples_leaf=16, min_samples_split=17;, score=0.711 total time=  24.2s
[CV 3/5] END max_depth=14, min_samples_leaf=16, min_samples_split=17;, score=0.690 total time=  24.7s
[CV 4/5] END max_depth=14, min_samples_leaf=16, min_samples_split=17;, score=0.691 total time=  24.4s
[CV 5/5] END max_depth=14, min_samples_leaf=16, min_samples_split=17;, score=0.677 total time=  27.1s
[CV 1/5] END max_depth=15, min_samples_leaf=19, min_samples_split=7;, score=0.691 total time=  26.1s
[CV 2/5] END max_depth=15, min_samples_leaf=19, min_samples_split=7;, score=0.703 total time=  26.2s
[CV 3/5] END max_depth=15, min_samples_leaf=19, min_samples_split=7;, score=0.676 total time=  24.9s
[CV 4/5] END max_depth=15, min_samples_leaf=19, min_samples_split=7;, score=0.685 total time=  24.8s
[CV 5/5] END max_depth=15, min_samples_leaf=19, min_samples_split=7;, score=0.675 total time=  25.4s
[CV 1/5] END max_depth=8, min_samples_leaf=8, min_samples_split=6;, score=0.683 total time=  21.4s
[CV 2/5] END max_depth=8, min_samples_leaf=8, min_samples_split=6;, score=0.701 total time=  19.8s
[CV 3/5] END max_depth=8, min_samples_leaf=8, min_samples_split=6;, score=0.669 total time=  20.5s
[CV 4/5] END max_depth=8, min_samples_leaf=8, min_samples_split=6;, score=0.671 total time=  19.7s
[CV 5/5] END max_depth=8, min_samples_leaf=8, min_samples_split=6;, score=0.662 total time=  20.2s
[CV 1/5] END max_depth=15, min_samples_leaf=8, min_samples_split=6;, score=0.696 total time=  28.3s
[CV 2/5] END max_depth=15, min_samples_leaf=8, min_samples_split=6;, score=0.720 total time=  29.2s
[CV 3/5] END max_depth=15, min_samples_leaf=8, min_samples_split=6;, score=0.694 total time=  29.0s
[CV 4/5] END max_depth=15, min_samples_leaf=8, min_samples_split=6;, score=0.691 total time=  26.6s
[CV 5/5] END max_depth=15, min_samples_leaf=8, min_samples_split=6;, score=0.681 total time=  27.2s
[CV 1/5] END max_depth=13, min_samples_leaf=10, min_samples_split=14;, score=0.697 total time=  24.3s
[CV 2/5] END max_depth=13, min_samples_leaf=10, min_samples_split=14;, score=0.710 total time=  25.5s
[CV 3/5] END max_depth=13, min_samples_leaf=10, min_samples_split=14;, score=0.681 total time=  24.5s
[CV 4/5] END max_depth=13, min_samples_leaf=10, min_samples_split=14;, score=0.692 total time=  23.8s
[CV 5/5] END max_depth=13, min_samples_leaf=10, min_samples_split=14;, score=0.677 total time=  25.0s
[CV 1/5] END max_depth=11, min_samples_leaf=10, min_samples_split=17;, score=0.694 total time=  24.3s
[CV 2/5] END max_depth=11, min_samples_leaf=10, min_samples_split=17;, score=0.710 total time=  25.9s
[CV 3/5] END max_depth=11, min_samples_leaf=10, min_samples_split=17;, score=0.679 total time=  25.9s
[CV 4/5] END max_depth=11, min_samples_leaf=10, min_samples_split=17;, score=0.685 total time=  24.7s
[CV 5/5] END max_depth=11, min_samples_leaf=10, min_samples_split=17;, score=0.679 total time=  25.2s
[CV 1/5] END max_depth=9, min_samples_leaf=14, min_samples_split=16;, score=0.685 total time=  21.7s
[CV 2/5] END max_depth=9, min_samples_leaf=14, min_samples_split=16;, score=0.699 total time=  21.9s
[CV 3/5] END max_depth=9, min_samples_leaf=14, min_samples_split=16;, score=0.672 total time=  21.6s
[CV 4/5] END max_depth=9, min_samples_leaf=14, min_samples_split=16;, score=0.677 total time=  21.3s
[CV 5/5] END max_depth=9, min_samples_leaf=14, min_samples_split=16;, score=0.670 total time=  22.3s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=30,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023FBD8BB770>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023FBD4474D0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023FBD4475D0>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [38]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(10)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
26,15,8,6,0.696177
11,19,13,5,0.693338
0,14,8,17,0.692352
4,18,12,9,0.692094
1,18,12,17,0.692094
10,17,10,17,0.691971
13,17,16,16,0.691943
23,14,16,17,0.691930
21,12,6,8,0.691654
20,17,13,14,0.691394

In [39]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 15, 'min_samples_leaf': 8, 'min_samples_split': 6}
Best CV score: 0.6961768197200706

In [40]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97      5024
           1       0.98      0.96      0.97      4819

    accuracy                           0.97      9843
   macro avg       0.97      0.97      0.97      9843
weighted avg       0.97      0.97      0.97      9843

#### Evaluación

In [41]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.63      0.66       663
           1       0.64      0.70      0.67       633

    accuracy                           0.67      1296
   macro avg       0.67      0.67      0.66      1296
weighted avg       0.67      0.67      0.66      1296

#### Guardado

In [42]:
os.makedirs(f'./modelos/{dataset}', exist_ok=True)

joblib.dump(best_model, f'./modelos/{dataset}/melspec_rf.pkl')

['./modelos/ciclos_r_hl256_rms/melspec_rf.pkl']

### Gradient Boost

In [5]:
gbc = GradientBoostingClassifier(
    n_estimators=1000,
    n_iter_no_change=10,
    max_features='sqrt',
    random_state=SEED
    )

In [51]:
param_grid = {
    'learning_rate': [0.03, 0.05, 0.07, 0.1]
}

rnd_search = GridSearchCV(
    estimator=gbc,
    param_grid=param_grid,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END ................learning_rate=0.03;, score=0.690 total time= 2.6min
[CV 2/5] END ................learning_rate=0.03;, score=0.695 total time=  47.2s
[CV 3/5] END ................learning_rate=0.03;, score=0.647 total time=  22.4s
[CV 4/5] END ................learning_rate=0.03;, score=0.647 total time=  43.1s
[CV 5/5] END ................learning_rate=0.03;, score=0.661 total time= 1.0min
[CV 1/5] END ................learning_rate=0.05;, score=0.681 total time= 1.1min
[CV 2/5] END ................learning_rate=0.05;, score=0.694 total time=  35.2s
[CV 3/5] END ................learning_rate=0.05;, score=0.659 total time=  27.8s
[CV 4/5] END ................learning_rate=0.05;, score=0.673 total time=  54.8s
[CV 5/5] END ................learning_rate=0.05;, score=0.668 total time=  43.8s
[CV 1/5] END ................learning_rate=0.07;, score=0.680 total time= 1.1min
[CV 2/5] END ................learning_rate=0.07;, score=0.696 total time=  46.3s
[CV 3/5] END ................learning_rate=0.07;, score=0.655 total time=  22.9s
[CV 4/5] END ................learning_rate=0.07;, score=0.659 total time=  38.9s
[CV 5/5] END ................learning_rate=0.07;, score=0.665 total time=  31.9s
[CV 1/5] END .................learning_rate=0.1;, score=0.677 total time=  43.1s
[CV 2/5] END .................learning_rate=0.1;, score=0.701 total time=  43.5s
[CV 3/5] END .................learning_rate=0.1;, score=0.650 total time=  17.9s
[CV 4/5] END .................learning_rate=0.1;, score=0.657 total time=  28.5s
[CV 5/5] END .................learning_rate=0.1;, score=0.675 total time=  39.3s

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=GradientBoostingClassifier(max_features='sqrt',
                                                  n_estimators=1000,
                                                  n_iter_no_change=10,
                                                  random_state=42),
             param_grid={'learning_rate': [0.03, 0.05, 0.07, 0.1]},
             scoring='roc_auc', verbose=3)

In [52]:
pd.DataFrame(rnd_search.cv_results_)[['param_learning_rate', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

   param_learning_rate  mean_test_score
1                 0.05         0.675030
3                 0.10         0.671997
2                 0.07         0.670785
0                 0.03         0.667886

In [53]:
best_model = rnd_search.best_estimator_

In [7]:
best_model.n_estimators_

106

In [8]:
predict_train = best_model.predict(X_train)
print(classification_report(y_train, predict_train))

              precision    recall  f1-score   support

           0       0.70      0.67      0.68      5024
           1       0.67      0.69      0.68      4819

    accuracy                           0.68      9843
   macro avg       0.68      0.68      0.68      9843
weighted avg       0.68      0.68      0.68      9843

In [9]:
predict_test = best_model.predict(X_test)
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.68      0.62      0.65       663
           1       0.64      0.70      0.67       633

    accuracy                           0.66      1296
   macro avg       0.66      0.66      0.66      1296
weighted avg       0.66      0.66      0.66      1296

In [11]:
joblib.dump(best_model, f'./modelos/{dataset}/melspec_gbc.pkl')

['./modelos/ciclos_r_hl256_rms/melspec_gbc.pkl']

## Features de Audio

In [58]:
train_data = np.load(f'./dataset/{dataset}/train_features.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_features.npz')
X_test = test_data['X']
y_test = test_data['y']

In [59]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((9843, 46), (9843,), (1296, 46), (1296,))

### Random Forest

#### Entrenamiento

In [63]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

param_distributions = {
    'max_depth': randint(13, 20),
    'min_samples_split': randint(15, 30),
    'min_samples_leaf': randint(5, 15),
    'max_features': ['sqrt', 'log2', None]
}

In [64]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.726 total time=   0.7s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.752 total time=   0.7s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.735 total time=   0.7s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.743 total time=   0.7s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=27;, score=0.733 total time=   0.7s
[CV 1/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.727 total time=   4.4s
[CV 2/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.754 total time=   4.8s
[CV 3/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.739 total time=   6.3s
[CV 4/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.743 total time=   8.1s
[CV 5/5] END max_depth=17, max_features=None, min_samples_leaf=14, min_samples_split=17;, score=0.739 total time=   7.9s
[CV 1/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.730 total time=   7.7s
[CV 2/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.756 total time=   8.0s
[CV 3/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.740 total time=   7.4s
[CV 4/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.745 total time=   7.8s
[CV 5/5] END max_depth=19, max_features=None, min_samples_leaf=12, min_samples_split=19;, score=0.743 total time=   7.9s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.729 total time=   7.5s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.757 total time=   7.8s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.742 total time=   7.5s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.747 total time=   8.0s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=10, min_samples_split=19;, score=0.743 total time=   8.3s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.722 total time=   0.8s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.745 total time=   0.9s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.731 total time=   0.9s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.742 total time=   0.9s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=16;, score=0.723 total time=   0.9s
[CV 1/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.730 total time=   1.2s
[CV 2/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.757 total time=   1.1s
[CV 3/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.748 total time=   1.2s
[CV 4/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.751 total time=   1.2s
[CV 5/5] END max_depth=16, max_features=sqrt, min_samples_leaf=5, min_samples_split=26;, score=0.735 total time=   1.2s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.718 total time=   0.9s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.743 total time=   0.9s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.734 total time=   0.9s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.737 total time=   0.9s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=13, min_samples_split=15;, score=0.723 total time=   0.9s
[CV 1/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.726 total time=   7.5s
[CV 2/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.753 total time=   7.8s
[CV 3/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.737 total time=   7.3s
[CV 4/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.741 total time=   7.5s
[CV 5/5] END max_depth=15, max_features=None, min_samples_leaf=14, min_samples_split=26;, score=0.738 total time=   7.6s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.731 total time=   7.9s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.756 total time=   8.1s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.741 total time=   7.8s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.746 total time=   8.1s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=26;, score=0.747 total time=   8.3s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.729 total time=   1.2s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.763 total time=   1.2s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.742 total time=   1.2s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.754 total time=   1.2s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=7, min_samples_split=19;, score=0.736 total time=   1.2s
[CV 1/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.730 total time=   7.7s
[CV 2/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.757 total time=   7.8s
[CV 3/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.741 total time=   7.5s
[CV 4/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.744 total time=   7.8s
[CV 5/5] END max_depth=15, max_features=None, min_samples_leaf=9, min_samples_split=23;, score=0.742 total time=   8.4s
[CV 1/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.727 total time=   1.1s
[CV 2/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.754 total time=   1.2s
[CV 3/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.745 total time=   1.1s
[CV 4/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.742 total time=   1.0s
[CV 5/5] END max_depth=19, max_features=log2, min_samples_leaf=8, min_samples_split=23;, score=0.734 total time=   1.1s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.720 total time=   1.0s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.755 total time=   1.1s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.747 total time=   1.0s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.749 total time=   1.0s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.735 total time=   1.0s
[CV 1/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.720 total time=   0.9s
[CV 2/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.748 total time=   0.9s
[CV 3/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.741 total time=   0.9s
[CV 4/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.739 total time=   0.9s
[CV 5/5] END max_depth=13, max_features=log2, min_samples_leaf=9, min_samples_split=16;, score=0.728 total time=   0.9s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.726 total time=   7.7s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.755 total time=   8.0s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.739 total time=   8.3s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.743 total time=   8.0s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=11, min_samples_split=26;, score=0.737 total time=   8.0s
[CV 1/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.732 total time=   8.1s
[CV 2/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.757 total time=   8.2s
[CV 3/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.741 total time=   8.0s
[CV 4/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.747 total time=   8.2s
[CV 5/5] END max_depth=17, max_features=None, min_samples_leaf=7, min_samples_split=28;, score=0.745 total time=   8.2s
[CV 1/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.714 total time=   0.9s
[CV 2/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.748 total time=   0.9s
[CV 3/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.731 total time=   0.9s
[CV 4/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.735 total time=   0.9s
[CV 5/5] END max_depth=13, max_features=log2, min_samples_leaf=12, min_samples_split=18;, score=0.724 total time=   0.9s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.722 total time=   0.9s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.745 total time=   1.0s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.731 total time=   1.0s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.742 total time=   0.9s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=10, min_samples_split=20;, score=0.723 total time=   0.9s
[CV 1/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.727 total time=   0.9s
[CV 2/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.751 total time=   0.9s
[CV 3/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.741 total time=   0.9s
[CV 4/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.740 total time=   1.0s
[CV 5/5] END max_depth=14, max_features=log2, min_samples_leaf=6, min_samples_split=24;, score=0.731 total time=   0.9s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.718 total time=   0.9s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.745 total time=   0.9s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.740 total time=   0.9s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.736 total time=   0.9s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=14, min_samples_split=28;, score=0.734 total time=   0.9s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.722 total time=   0.9s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.745 total time=   0.9s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.738 total time=   0.9s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.741 total time=   0.9s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=12, min_samples_split=28;, score=0.726 total time=   1.0s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.726 total time=   1.2s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.751 total time=   1.1s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.738 total time=   1.1s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.746 total time=   1.1s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=19;, score=0.732 total time=   1.1s
[CV 1/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.724 total time=   1.0s
[CV 2/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.752 total time=   1.0s
[CV 3/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.741 total time=   1.0s
[CV 4/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.743 total time=   1.0s
[CV 5/5] END max_depth=17, max_features=log2, min_samples_leaf=9, min_samples_split=22;, score=0.729 total time=   1.0s
[CV 1/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.720 total time=   1.1s
[CV 2/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.744 total time=   1.1s
[CV 3/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.734 total time=   1.1s
[CV 4/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.738 total time=   1.1s
[CV 5/5] END max_depth=14, max_features=sqrt, min_samples_leaf=13, min_samples_split=27;, score=0.728 total time=   1.1s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.732 total time=   1.2s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.761 total time=   1.3s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.742 total time=   1.2s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.755 total time=   1.2s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=5, min_samples_split=23;, score=0.737 total time=   1.2s
[CV 1/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.726 total time=   1.1s
[CV 2/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.751 total time=   1.2s
[CV 3/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.738 total time=   1.1s
[CV 4/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.746 total time=   1.2s
[CV 5/5] END max_depth=19, max_features=sqrt, min_samples_leaf=12, min_samples_split=15;, score=0.732 total time=   1.1s
[CV 1/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.736 total time=   8.1s
[CV 2/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.761 total time=   8.2s
[CV 3/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.743 total time=   8.1s
[CV 4/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.750 total time=   8.4s
[CV 5/5] END max_depth=16, max_features=None, min_samples_leaf=7, min_samples_split=15;, score=0.751 total time=   8.2s
[CV 1/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.730 total time=   7.9s
[CV 2/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.759 total time=   8.5s
[CV 3/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.743 total time=   8.3s
[CV 4/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.746 total time=   8.1s
[CV 5/5] END max_depth=15, max_features=None, min_samples_leaf=5, min_samples_split=25;, score=0.748 total time=   8.2s
[CV 1/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.725 total time=   0.9s
[CV 2/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.751 total time=   0.9s
[CV 3/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.737 total time=   0.9s
[CV 4/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.747 total time=   1.0s
[CV 5/5] END max_depth=17, max_features=log2, min_samples_leaf=11, min_samples_split=24;, score=0.728 total time=   1.0s
[CV 1/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.723 total time=   7.2s
[CV 2/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.751 total time=   7.2s
[CV 3/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.735 total time=   6.9s
[CV 4/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.740 total time=   7.3s
[CV 5/5] END max_depth=13, max_features=None, min_samples_leaf=13, min_samples_split=22;, score=0.737 total time=   7.2s
[CV 1/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.726 total time=   0.9s
[CV 2/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.757 total time=   1.0s
[CV 3/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.746 total time=   1.0s
[CV 4/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.747 total time=   1.0s
[CV 5/5] END max_depth=16, max_features=log2, min_samples_leaf=5, min_samples_split=21;, score=0.737 total time=   1.0s
[CV 1/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.727 total time=   0.9s
[CV 2/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.751 total time=   1.0s
[CV 3/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.732 total time=   0.9s
[CV 4/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.742 total time=   0.9s
[CV 5/5] END max_depth=19, max_features=log2, min_samples_leaf=12, min_samples_split=19;, score=0.724 total time=   1.0s
[CV 1/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.727 total time=   1.0s
[CV 2/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.756 total time=   1.0s
[CV 3/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.747 total time=   1.0s
[CV 4/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.744 total time=   1.1s
[CV 5/5] END max_depth=15, max_features=log2, min_samples_leaf=7, min_samples_split=15;, score=0.733 total time=   1.0s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=50,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023FC6DF3620>,
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023FC6DF3AF0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023FC6DF38C0>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [65]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
41,19,7,20,0.748294
26,16,7,15,0.748172
24,19,5,23,0.745377
27,15,5,25,0.745104
9,19,7,19,0.744867
15,17,7,28,0.744537
40,19,8,27,0.744339
8,16,7,26,0.744286
5,16,5,26,0.744102
3,16,10,19,0.743674
33,15,7,15,0.743408
10,15,9,23,0.742858
2,19,12,19,0.742662
30,16,5,21,0.742390
37,17,11,15,0.742078
43,18,9,20,0.741840
32,15,7,15,0.741465
12,16,6,24,0.741131
49,15,9,15,0.740920
11,19,8,23,0.740596
35,18,13,29,0.740528
1,17,14,17,0.740380
39,17,11,27,0.740171
14,16,11,26,0.739837
7,15,14,26,0.739312
38,16,8,28,0.739164
25,19,12,15,0.738637
21,19,12,19,0.738637
47,18,8,27,0.738629
22,17,9,22,0.737969
48,13,11,20,0.737826
0,19,12,27,0.737818
18,14,6,24,0.737727
28,17,11,24,0.737540
29,13,13,22,0.737470
45,16,11,28,0.735831
34,17,11,29,0.735666
31,19,12,19,0.735176
13,13,9,16,0.735098
36,19,14,26,0.735017
19,16,14,28,0.734412
42,16,14,27,0.734412
44,16,14,21,0.734412
20,16,12,28,0.734221
4,14,10,16,0.732583
17,14,10,20,0.732583
23,14,13,27,0.732582
46,13,13,25,0.731395
6,14,13,15,0.730786
16,13,12,18,0.730403

In [66]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 19, 'max_features': None, 'min_samples_leaf': 7, 'min_samples_split': 20}
Best CV score: 0.7482936466228021

In [67]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      5024
           1       0.96      0.95      0.95      4819

    accuracy                           0.95      9843
   macro avg       0.95      0.95      0.95      9843
weighted avg       0.95      0.95      0.95      9843

#### Evaluación

In [68]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.78      0.77       663
           1       0.77      0.75      0.76       633

    accuracy                           0.76      1296
   macro avg       0.76      0.76      0.76      1296
weighted avg       0.76      0.76      0.76      1296

#### Guardado

In [69]:
joblib.dump(best_model, f'./modelos/{dataset}/features_rf.pkl')

['./modelos/ciclos_r_hl256_rms/features_rf.pkl']

### Gradient Boosting

In [71]:
gbc = GradientBoostingClassifier(
    n_estimators=1000,
    n_iter_no_change=10,
    random_state=SEED
    )

In [80]:
param_grid = {
    'learning_rate': [0.1, 0.15, 0.2]
}

rnd_search = GridSearchCV(
    estimator=gbc,
    param_grid=param_grid,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV 1/5] END .................learning_rate=0.1;, score=0.699 total time=  27.4s
[CV 2/5] END .................learning_rate=0.1;, score=0.710 total time=  19.9s
[CV 3/5] END .................learning_rate=0.1;, score=0.709 total time=  22.9s
[CV 4/5] END .................learning_rate=0.1;, score=0.711 total time=  19.3s
[CV 5/5] END .................learning_rate=0.1;, score=0.694 total time=  13.2s
[CV 1/5] END ................learning_rate=0.15;, score=0.686 total time=  12.7s
[CV 2/5] END ................learning_rate=0.15;, score=0.706 total time=   9.0s
[CV 3/5] END ................learning_rate=0.15;, score=0.677 total time=   4.8s
[CV 4/5] END ................learning_rate=0.15;, score=0.709 total time=  14.7s
[CV 5/5] END ................learning_rate=0.15;, score=0.704 total time=  16.9s
[CV 1/5] END .................learning_rate=0.2;, score=0.662 total time=   3.9s
[CV 2/5] END .................learning_rate=0.2;, score=0.706 total time=   8.7s
[CV 3/5] END .................learning_rate=0.2;, score=0.695 total time=   7.9s
[CV 4/5] END .................learning_rate=0.2;, score=0.714 total time=  10.7s
[CV 5/5] END .................learning_rate=0.2;, score=0.700 total time=  11.8s

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=GradientBoostingClassifier(n_estimators=1000,
                                                  n_iter_no_change=10,
                                                  random_state=42),
             param_grid={'learning_rate': [0.1, 0.15, 0.2]}, scoring='roc_auc',
             verbose=3)

In [81]:
pd.DataFrame(rnd_search.cv_results_)[['param_learning_rate', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

   param_learning_rate  mean_test_score
0                 0.10         0.704778
1                 0.15         0.696589
2                 0.20         0.695239

In [82]:
best_model = rnd_search.best_estimator_

In [83]:
best_model.n_estimators_

156

In [84]:
predict_train = best_model.predict(X_train)
print(classification_report(y_train, predict_train))

              precision    recall  f1-score   support

           0       0.75      0.73      0.74      5024
           1       0.73      0.75      0.74      4819

    accuracy                           0.74      9843
   macro avg       0.74      0.74      0.74      9843
weighted avg       0.74      0.74      0.74      9843

In [85]:
predict_test = best_model.predict(X_test)
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.72      0.69      0.70       663
           1       0.68      0.71      0.70       633

    accuracy                           0.70      1296
   macro avg       0.70      0.70      0.70      1296
weighted avg       0.70      0.70      0.70      1296

In [86]:
joblib.dump(best_model, f'./modelos/{dataset}/features_gbc.pkl')

['./modelos/ciclos_r_hl256_rms/features_gbc.pkl']