# Modelo

In [1]:
import numpy as np
import pandas as pd
import joblib
import os

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import randint, uniform, norm, loguniform

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report

from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, GridSearchCV

from config import SEED

Elegimos dataset

In [2]:
dataset = 'ciclos_c_r_hl256'

## Espectrogramas

Se suelen usar Mel espectrogramas

Traigo los consjuntos de entrenamiento y testeo. (TODO: buscar una manera más eficiente de guardarlos)

In [3]:
train_data = np.load(f'./dataset/{dataset}/train_melspectrogram.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_melspectrogram.npz')
X_test = test_data['X']
y_test = test_data['y']

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((9843, 47616), (9843,), (1296, 47616), (1296,))

### Random Forest

#### Entrenamiento

In [5]:
rf = RandomForestClassifier(random_state=SEED, n_jobs=-1, max_features='log2')

param_distributions = {
    'max_depth': randint(5, 10),
    'min_samples_split': randint(10, 25),
    'min_samples_leaf': randint(10, 25)
}

In [8]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=20,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END max_depth=8, min_samples_leaf=22, min_samples_split=24;, score=0.659 total time=  21.4s
[CV 2/5] END max_depth=8, min_samples_leaf=22, min_samples_split=24;, score=0.677 total time=  11.4s
[CV 3/5] END max_depth=8, min_samples_leaf=22, min_samples_split=24;, score=0.648 total time=   6.7s
[CV 4/5] END max_depth=8, min_samples_leaf=22, min_samples_split=24;, score=0.653 total time=   6.5s
[CV 5/5] END max_depth=8, min_samples_leaf=22, min_samples_split=24;, score=0.638 total time=   6.8s
[CV 1/5] END max_depth=7, min_samples_leaf=17, min_samples_split=22;, score=0.661 total time=   6.6s
[CV 2/5] END max_depth=7, min_samples_leaf=17, min_samples_split=22;, score=0.682 total time=   6.8s
[CV 3/5] END max_depth=7, min_samples_leaf=17, min_samples_split=22;, score=0.645 total time=   6.4s
[CV 4/5] END max_depth=7, min_samples_leaf=17, min_samples_split=22;, score=0.646 total time=   6.5s
[CV 5/5] END max_depth=7, min_samples_leaf=17, min_samples_split=22;, score=0.641 total time=   6.6s
[CV 1/5] END max_depth=9, min_samples_leaf=16, min_samples_split=19;, score=0.663 total time=   6.3s
[CV 2/5] END max_depth=9, min_samples_leaf=16, min_samples_split=19;, score=0.688 total time=   6.9s
[CV 3/5] END max_depth=9, min_samples_leaf=16, min_samples_split=19;, score=0.660 total time=   6.4s
[CV 4/5] END max_depth=9, min_samples_leaf=16, min_samples_split=19;, score=0.656 total time=   6.6s
[CV 5/5] END max_depth=9, min_samples_leaf=16, min_samples_split=19;, score=0.650 total time=   6.6s
[CV 1/5] END max_depth=7, min_samples_leaf=16, min_samples_split=20;, score=0.659 total time=   6.1s
[CV 2/5] END max_depth=7, min_samples_leaf=16, min_samples_split=20;, score=0.681 total time=   6.4s
[CV 3/5] END max_depth=7, min_samples_leaf=16, min_samples_split=20;, score=0.645 total time=   5.5s
[CV 4/5] END max_depth=7, min_samples_leaf=16, min_samples_split=20;, score=0.644 total time=   5.7s
[CV 5/5] END max_depth=7, min_samples_leaf=16, min_samples_split=20;, score=0.641 total time=   5.6s
[CV 1/5] END max_depth=7, min_samples_leaf=17, min_samples_split=14;, score=0.661 total time=   5.6s
[CV 2/5] END max_depth=7, min_samples_leaf=17, min_samples_split=14;, score=0.682 total time=   6.1s
[CV 3/5] END max_depth=7, min_samples_leaf=17, min_samples_split=14;, score=0.645 total time=   5.8s
[CV 4/5] END max_depth=7, min_samples_leaf=17, min_samples_split=14;, score=0.646 total time=   5.7s
[CV 5/5] END max_depth=7, min_samples_leaf=17, min_samples_split=14;, score=0.641 total time=   5.6s
[CV 1/5] END max_depth=8, min_samples_leaf=17, min_samples_split=17;, score=0.661 total time=   6.7s
[CV 2/5] END max_depth=8, min_samples_leaf=17, min_samples_split=17;, score=0.681 total time=   6.5s
[CV 3/5] END max_depth=8, min_samples_leaf=17, min_samples_split=17;, score=0.646 total time=   6.7s
[CV 4/5] END max_depth=8, min_samples_leaf=17, min_samples_split=17;, score=0.652 total time=   7.3s
[CV 5/5] END max_depth=8, min_samples_leaf=17, min_samples_split=17;, score=0.641 total time=   7.0s
[CV 1/5] END max_depth=7, min_samples_leaf=15, min_samples_split=14;, score=0.658 total time=   6.1s
[CV 2/5] END max_depth=7, min_samples_leaf=15, min_samples_split=14;, score=0.682 total time=   6.6s
[CV 3/5] END max_depth=7, min_samples_leaf=15, min_samples_split=14;, score=0.643 total time=   6.4s
[CV 4/5] END max_depth=7, min_samples_leaf=15, min_samples_split=14;, score=0.643 total time=   6.6s
[CV 5/5] END max_depth=7, min_samples_leaf=15, min_samples_split=14;, score=0.638 total time=   6.7s
[CV 1/5] END max_depth=6, min_samples_leaf=17, min_samples_split=21;, score=0.645 total time=   5.9s
[CV 2/5] END max_depth=6, min_samples_leaf=17, min_samples_split=21;, score=0.674 total time=   5.8s
[CV 3/5] END max_depth=6, min_samples_leaf=17, min_samples_split=21;, score=0.639 total time=   6.0s
[CV 4/5] END max_depth=6, min_samples_leaf=17, min_samples_split=21;, score=0.640 total time=   5.7s
[CV 5/5] END max_depth=6, min_samples_leaf=17, min_samples_split=21;, score=0.634 total time=   5.8s
[CV 1/5] END max_depth=6, min_samples_leaf=21, min_samples_split=14;, score=0.648 total time=   5.7s
[CV 2/5] END max_depth=6, min_samples_leaf=21, min_samples_split=14;, score=0.675 total time=   6.4s
[CV 3/5] END max_depth=6, min_samples_leaf=21, min_samples_split=14;, score=0.641 total time=   6.0s
[CV 4/5] END max_depth=6, min_samples_leaf=21, min_samples_split=14;, score=0.641 total time=   6.1s
[CV 5/5] END max_depth=6, min_samples_leaf=21, min_samples_split=14;, score=0.635 total time=   5.8s
[CV 1/5] END max_depth=5, min_samples_leaf=21, min_samples_split=19;, score=0.639 total time=   5.1s
[CV 2/5] END max_depth=5, min_samples_leaf=21, min_samples_split=19;, score=0.667 total time=   5.1s
[CV 3/5] END max_depth=5, min_samples_leaf=21, min_samples_split=19;, score=0.633 total time=   5.0s
[CV 4/5] END max_depth=5, min_samples_leaf=21, min_samples_split=19;, score=0.630 total time=   5.0s
[CV 5/5] END max_depth=5, min_samples_leaf=21, min_samples_split=19;, score=0.625 total time=   5.0s
[CV 1/5] END max_depth=9, min_samples_leaf=21, min_samples_split=18;, score=0.662 total time=   5.4s
[CV 2/5] END max_depth=9, min_samples_leaf=21, min_samples_split=18;, score=0.687 total time=   5.6s
[CV 3/5] END max_depth=9, min_samples_leaf=21, min_samples_split=18;, score=0.655 total time=   5.6s
[CV 4/5] END max_depth=9, min_samples_leaf=21, min_samples_split=18;, score=0.656 total time=   6.8s
[CV 5/5] END max_depth=9, min_samples_leaf=21, min_samples_split=18;, score=0.643 total time=   6.4s
[CV 1/5] END max_depth=5, min_samples_leaf=20, min_samples_split=20;, score=0.639 total time=   5.6s
[CV 2/5] END max_depth=5, min_samples_leaf=20, min_samples_split=20;, score=0.668 total time=   5.6s
[CV 3/5] END max_depth=5, min_samples_leaf=20, min_samples_split=20;, score=0.634 total time=   5.1s
[CV 4/5] END max_depth=5, min_samples_leaf=20, min_samples_split=20;, score=0.631 total time=   5.0s
[CV 5/5] END max_depth=5, min_samples_leaf=20, min_samples_split=20;, score=0.625 total time=   5.2s
[CV 1/5] END max_depth=6, min_samples_leaf=21, min_samples_split=21;, score=0.648 total time=   5.2s
[CV 2/5] END max_depth=6, min_samples_leaf=21, min_samples_split=21;, score=0.675 total time=   5.1s
[CV 3/5] END max_depth=6, min_samples_leaf=21, min_samples_split=21;, score=0.641 total time=   5.2s
[CV 4/5] END max_depth=6, min_samples_leaf=21, min_samples_split=21;, score=0.641 total time=   5.1s
[CV 5/5] END max_depth=6, min_samples_leaf=21, min_samples_split=21;, score=0.635 total time=   5.5s
[CV 1/5] END max_depth=7, min_samples_leaf=21, min_samples_split=16;, score=0.657 total time=   5.3s
[CV 2/5] END max_depth=7, min_samples_leaf=21, min_samples_split=16;, score=0.682 total time=   5.4s
[CV 3/5] END max_depth=7, min_samples_leaf=21, min_samples_split=16;, score=0.648 total time=   5.3s
[CV 4/5] END max_depth=7, min_samples_leaf=21, min_samples_split=16;, score=0.646 total time=   5.5s
[CV 5/5] END max_depth=7, min_samples_leaf=21, min_samples_split=16;, score=0.638 total time=   5.2s
[CV 1/5] END max_depth=8, min_samples_leaf=18, min_samples_split=12;, score=0.656 total time=   5.7s
[CV 2/5] END max_depth=8, min_samples_leaf=18, min_samples_split=12;, score=0.681 total time=   6.4s
[CV 3/5] END max_depth=8, min_samples_leaf=18, min_samples_split=12;, score=0.652 total time=   6.1s
[CV 4/5] END max_depth=8, min_samples_leaf=18, min_samples_split=12;, score=0.653 total time=   6.8s
[CV 5/5] END max_depth=8, min_samples_leaf=18, min_samples_split=12;, score=0.642 total time=   6.6s
[CV 1/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.668 total time=   6.1s
[CV 2/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.689 total time=   6.3s
[CV 3/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.656 total time=   5.6s
[CV 4/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.658 total time=   5.6s
[CV 5/5] END max_depth=9, min_samples_leaf=12, min_samples_split=16;, score=0.648 total time=   5.5s
[CV 1/5] END max_depth=9, min_samples_leaf=18, min_samples_split=16;, score=0.662 total time=   5.6s
[CV 2/5] END max_depth=9, min_samples_leaf=18, min_samples_split=16;, score=0.687 total time=   5.7s
[CV 3/5] END max_depth=9, min_samples_leaf=18, min_samples_split=16;, score=0.652 total time=   5.6s
[CV 4/5] END max_depth=9, min_samples_leaf=18, min_samples_split=16;, score=0.659 total time=   5.6s
[CV 5/5] END max_depth=9, min_samples_leaf=18, min_samples_split=16;, score=0.644 total time=   5.4s
[CV 1/5] END max_depth=6, min_samples_leaf=13, min_samples_split=18;, score=0.649 total time=   5.1s
[CV 2/5] END max_depth=6, min_samples_leaf=13, min_samples_split=18;, score=0.674 total time=   5.1s
[CV 3/5] END max_depth=6, min_samples_leaf=13, min_samples_split=18;, score=0.644 total time=   5.4s
[CV 4/5] END max_depth=6, min_samples_leaf=13, min_samples_split=18;, score=0.637 total time=   5.5s
[CV 5/5] END max_depth=6, min_samples_leaf=13, min_samples_split=18;, score=0.634 total time=   5.1s
[CV 1/5] END max_depth=8, min_samples_leaf=23, min_samples_split=11;, score=0.658 total time=   5.3s
[CV 2/5] END max_depth=8, min_samples_leaf=23, min_samples_split=11;, score=0.679 total time=   5.4s
[CV 3/5] END max_depth=8, min_samples_leaf=23, min_samples_split=11;, score=0.651 total time=   5.3s
[CV 4/5] END max_depth=8, min_samples_leaf=23, min_samples_split=11;, score=0.652 total time=   5.4s
[CV 5/5] END max_depth=8, min_samples_leaf=23, min_samples_split=11;, score=0.641 total time=   5.4s
[CV 1/5] END max_depth=6, min_samples_leaf=18, min_samples_split=19;, score=0.647 total time=   5.4s
[CV 2/5] END max_depth=6, min_samples_leaf=18, min_samples_split=19;, score=0.674 total time=   6.2s
[CV 3/5] END max_depth=6, min_samples_leaf=18, min_samples_split=19;, score=0.641 total time=   6.1s
[CV 4/5] END max_depth=6, min_samples_leaf=18, min_samples_split=19;, score=0.641 total time=   5.9s
[CV 5/5] END max_depth=6, min_samples_leaf=18, min_samples_split=19;, score=0.632 total time=   5.5s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(max_features='log2',
                                                    n_jobs=-1,
                                                    random_state=42),
                   n_iter=20,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E86C92BA0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E86CEC690>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E86CEC410>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [9]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(20)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
15,9,12,16,0.663876
2,9,16,19,0.663331
16,9,18,16,0.660860
10,9,21,18,0.660850
14,8,18,12,0.657120
18,8,23,11,0.656213
5,8,17,17,0.656118
0,8,22,24,0.655069
4,7,17,14,0.655029
1,7,17,22,0.655029
13,7,21,16,0.654337
3,7,16,20,0.654042
6,7,15,14,0.652542
12,6,21,21,0.647952
8,6,21,14,0.647952
17,6,13,18,0.647643
19,6,18,19,0.646878
7,6,17,21,0.646662
11,5,20,20,0.639281
9,5,21,19,0.638904

In [10]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 9, 'min_samples_leaf': 12, 'min_samples_split': 16}
Best CV score: 0.6638763726097423

In [11]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.73      0.75      5024
           1       0.73      0.78      0.75      4819

    accuracy                           0.75      9843
   macro avg       0.75      0.75      0.75      9843
weighted avg       0.75      0.75      0.75      9843

#### Evaluación

In [12]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.57      0.62       663
           1       0.62      0.73      0.67       633

    accuracy                           0.65      1296
   macro avg       0.65      0.65      0.65      1296
weighted avg       0.65      0.65      0.64      1296

#### Guardado

In [13]:
os.makedirs(f'./modelos/{dataset}', exist_ok=True)

joblib.dump(best_model, f'./modelos/{dataset}/melspec_rf.pkl')

['./modelos/ciclos_c_r_hl256/melspec_rf.pkl']

### Gradient Boost

In [19]:
gbc = GradientBoostingClassifier(
    n_estimators=500,
    learning_rate=0.01,
    subsample=0.8,
    n_iter_no_change=10,
    max_features='log2',
    max_depth=5,
    random_state=SEED
    )

In [20]:
gbc.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.01, max_depth=5, max_features='log2',
                           n_estimators=500, n_iter_no_change=10,
                           random_state=42, subsample=0.8)

In [21]:
gbc.n_estimators_

313

In [22]:
predict_train = gbc.predict(X_train)
print(classification_report(y_train, predict_train))

              precision    recall  f1-score   support

           0       0.73      0.70      0.72      5024
           1       0.70      0.74      0.72      4819

    accuracy                           0.72      9843
   macro avg       0.72      0.72      0.72      9843
weighted avg       0.72      0.72      0.72      9843

In [23]:
predict_test = gbc.predict(X_test)
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.68      0.59      0.63       663
           1       0.62      0.71      0.66       633

    accuracy                           0.64      1296
   macro avg       0.65      0.65      0.64      1296
weighted avg       0.65      0.64      0.64      1296

In [24]:
joblib.dump(gbc, f'./modelos/{dataset}/melspec_gbc.pkl')

['./modelos/ciclos_c_r_hl256/melspec_gbc.pkl']

## Features de Audio

In [25]:
train_data = np.load(f'./dataset/{dataset}/train_features.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/{dataset}/test_features.npz')
X_test = test_data['X']
y_test = test_data['y']

In [26]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((9843, 46), (9843,), (1296, 46), (1296,))

### Random Forest

#### Entrenamiento

In [35]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

param_distributions = {
    'max_depth': randint(10, 20),
    'min_samples_split': randint(10, 25),
    'min_samples_leaf': randint(10, 20)
}

In [36]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.728 total time=   0.8s
[CV 2/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.769 total time=   0.8s
[CV 3/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.760 total time=   0.8s
[CV 4/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.753 total time=   0.8s
[CV 5/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.742 total time=   0.9s
[CV 1/5] END max_depth=17, min_samples_leaf=14, min_samples_split=16;, score=0.729 total time=   0.8s
[CV 2/5] END max_depth=17, min_samples_leaf=14, min_samples_split=16;, score=0.768 total time=   0.8s
[CV 3/5] END max_depth=17, min_samples_leaf=14, min_samples_split=16;, score=0.753 total time=   0.8s
[CV 4/5] END max_depth=17, min_samples_leaf=14, min_samples_split=16;, score=0.755 total time=   0.8s
[CV 5/5] END max_depth=17, min_samples_leaf=14, min_samples_split=16;, score=0.737 total time=   0.8s
[CV 1/5] END max_depth=19, min_samples_leaf=12, min_samples_split=16;, score=0.732 total time=   0.8s
[CV 2/5] END max_depth=19, min_samples_leaf=12, min_samples_split=16;, score=0.770 total time=   0.8s
[CV 3/5] END max_depth=19, min_samples_leaf=12, min_samples_split=16;, score=0.761 total time=   0.8s
[CV 4/5] END max_depth=19, min_samples_leaf=12, min_samples_split=16;, score=0.756 total time=   0.8s
[CV 5/5] END max_depth=19, min_samples_leaf=12, min_samples_split=16;, score=0.744 total time=   0.9s
[CV 1/5] END max_depth=17, min_samples_leaf=14, min_samples_split=13;, score=0.729 total time=   0.8s
[CV 2/5] END max_depth=17, min_samples_leaf=14, min_samples_split=13;, score=0.768 total time=   0.8s
[CV 3/5] END max_depth=17, min_samples_leaf=14, min_samples_split=13;, score=0.753 total time=   0.8s
[CV 4/5] END max_depth=17, min_samples_leaf=14, min_samples_split=13;, score=0.755 total time=   0.8s
[CV 5/5] END max_depth=17, min_samples_leaf=14, min_samples_split=13;, score=0.737 total time=   0.8s
[CV 1/5] END max_depth=17, min_samples_leaf=17, min_samples_split=12;, score=0.726 total time=   0.8s
[CV 2/5] END max_depth=17, min_samples_leaf=17, min_samples_split=12;, score=0.753 total time=   0.8s
[CV 3/5] END max_depth=17, min_samples_leaf=17, min_samples_split=12;, score=0.752 total time=   0.8s
[CV 4/5] END max_depth=17, min_samples_leaf=17, min_samples_split=12;, score=0.749 total time=   0.8s
[CV 5/5] END max_depth=17, min_samples_leaf=17, min_samples_split=12;, score=0.740 total time=   0.8s
[CV 1/5] END max_depth=15, min_samples_leaf=14, min_samples_split=11;, score=0.727 total time=   0.8s
[CV 2/5] END max_depth=15, min_samples_leaf=14, min_samples_split=11;, score=0.764 total time=   0.8s
[CV 3/5] END max_depth=15, min_samples_leaf=14, min_samples_split=11;, score=0.751 total time=   0.8s
[CV 4/5] END max_depth=15, min_samples_leaf=14, min_samples_split=11;, score=0.754 total time=   0.8s
[CV 5/5] END max_depth=15, min_samples_leaf=14, min_samples_split=11;, score=0.742 total time=   0.8s
[CV 1/5] END max_depth=17, min_samples_leaf=15, min_samples_split=11;, score=0.724 total time=   0.8s
[CV 2/5] END max_depth=17, min_samples_leaf=15, min_samples_split=11;, score=0.763 total time=   0.8s
[CV 3/5] END max_depth=17, min_samples_leaf=15, min_samples_split=11;, score=0.752 total time=   0.8s
[CV 4/5] END max_depth=17, min_samples_leaf=15, min_samples_split=11;, score=0.751 total time=   0.8s
[CV 5/5] END max_depth=17, min_samples_leaf=15, min_samples_split=11;, score=0.741 total time=   0.8s
[CV 1/5] END max_depth=14, min_samples_leaf=10, min_samples_split=21;, score=0.726 total time=   0.8s
[CV 2/5] END max_depth=14, min_samples_leaf=10, min_samples_split=21;, score=0.771 total time=   0.8s
[CV 3/5] END max_depth=14, min_samples_leaf=10, min_samples_split=21;, score=0.757 total time=   0.8s
[CV 4/5] END max_depth=14, min_samples_leaf=10, min_samples_split=21;, score=0.762 total time=   0.8s
[CV 5/5] END max_depth=14, min_samples_leaf=10, min_samples_split=21;, score=0.740 total time=   0.8s
[CV 1/5] END max_depth=19, min_samples_leaf=15, min_samples_split=22;, score=0.725 total time=   0.8s
[CV 2/5] END max_depth=19, min_samples_leaf=15, min_samples_split=22;, score=0.762 total time=   0.8s
[CV 3/5] END max_depth=19, min_samples_leaf=15, min_samples_split=22;, score=0.754 total time=   0.8s
[CV 4/5] END max_depth=19, min_samples_leaf=15, min_samples_split=22;, score=0.751 total time=   0.8s
[CV 5/5] END max_depth=19, min_samples_leaf=15, min_samples_split=22;, score=0.739 total time=   0.8s
[CV 1/5] END max_depth=18, min_samples_leaf=10, min_samples_split=20;, score=0.736 total time=   0.8s
[CV 2/5] END max_depth=18, min_samples_leaf=10, min_samples_split=20;, score=0.774 total time=   0.9s
[CV 3/5] END max_depth=18, min_samples_leaf=10, min_samples_split=20;, score=0.757 total time=   0.9s
[CV 4/5] END max_depth=18, min_samples_leaf=10, min_samples_split=20;, score=0.759 total time=   0.9s
[CV 5/5] END max_depth=18, min_samples_leaf=10, min_samples_split=20;, score=0.746 total time=   0.9s
[CV 1/5] END max_depth=19, min_samples_leaf=12, min_samples_split=21;, score=0.732 total time=   0.8s
[CV 2/5] END max_depth=19, min_samples_leaf=12, min_samples_split=21;, score=0.770 total time=   0.9s
[CV 3/5] END max_depth=19, min_samples_leaf=12, min_samples_split=21;, score=0.761 total time=   0.9s
[CV 4/5] END max_depth=19, min_samples_leaf=12, min_samples_split=21;, score=0.756 total time=   0.9s
[CV 5/5] END max_depth=19, min_samples_leaf=12, min_samples_split=21;, score=0.744 total time=   0.9s
[CV 1/5] END max_depth=16, min_samples_leaf=13, min_samples_split=18;, score=0.728 total time=   0.9s
[CV 2/5] END max_depth=16, min_samples_leaf=13, min_samples_split=18;, score=0.769 total time=   0.9s
[CV 3/5] END max_depth=16, min_samples_leaf=13, min_samples_split=18;, score=0.760 total time=   0.9s
[CV 4/5] END max_depth=16, min_samples_leaf=13, min_samples_split=18;, score=0.753 total time=   0.8s
[CV 5/5] END max_depth=16, min_samples_leaf=13, min_samples_split=18;, score=0.742 total time=   0.9s
[CV 1/5] END max_depth=12, min_samples_leaf=14, min_samples_split=12;, score=0.723 total time=   0.8s
[CV 2/5] END max_depth=12, min_samples_leaf=14, min_samples_split=12;, score=0.757 total time=   0.8s
[CV 3/5] END max_depth=12, min_samples_leaf=14, min_samples_split=12;, score=0.747 total time=   0.8s
[CV 4/5] END max_depth=12, min_samples_leaf=14, min_samples_split=12;, score=0.750 total time=   0.7s
[CV 5/5] END max_depth=12, min_samples_leaf=14, min_samples_split=12;, score=0.732 total time=   0.9s
[CV 1/5] END max_depth=16, min_samples_leaf=14, min_samples_split=18;, score=0.726 total time=   0.9s
[CV 2/5] END max_depth=16, min_samples_leaf=14, min_samples_split=18;, score=0.763 total time=   0.9s
[CV 3/5] END max_depth=16, min_samples_leaf=14, min_samples_split=18;, score=0.754 total time=   0.8s
[CV 4/5] END max_depth=16, min_samples_leaf=14, min_samples_split=18;, score=0.753 total time=   0.8s
[CV 5/5] END max_depth=16, min_samples_leaf=14, min_samples_split=18;, score=0.738 total time=   0.8s
[CV 1/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.733 total time=   0.8s
[CV 2/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.769 total time=   0.9s
[CV 3/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.758 total time=   0.9s
[CV 4/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.754 total time=   0.9s
[CV 5/5] END max_depth=16, min_samples_leaf=11, min_samples_split=13;, score=0.739 total time=   0.9s
[CV 1/5] END max_depth=18, min_samples_leaf=11, min_samples_split=19;, score=0.733 total time=   0.9s
[CV 2/5] END max_depth=18, min_samples_leaf=11, min_samples_split=19;, score=0.766 total time=   0.9s
[CV 3/5] END max_depth=18, min_samples_leaf=11, min_samples_split=19;, score=0.757 total time=   0.9s
[CV 4/5] END max_depth=18, min_samples_leaf=11, min_samples_split=19;, score=0.756 total time=   0.9s
[CV 5/5] END max_depth=18, min_samples_leaf=11, min_samples_split=19;, score=0.746 total time=   0.9s
[CV 1/5] END max_depth=18, min_samples_leaf=19, min_samples_split=14;, score=0.719 total time=   0.8s
[CV 2/5] END max_depth=18, min_samples_leaf=19, min_samples_split=14;, score=0.756 total time=   0.8s
[CV 3/5] END max_depth=18, min_samples_leaf=19, min_samples_split=14;, score=0.750 total time=   0.8s
[CV 4/5] END max_depth=18, min_samples_leaf=19, min_samples_split=14;, score=0.746 total time=   0.8s
[CV 5/5] END max_depth=18, min_samples_leaf=19, min_samples_split=14;, score=0.728 total time=   0.8s
[CV 1/5] END max_depth=11, min_samples_leaf=13, min_samples_split=21;, score=0.721 total time=   0.7s
[CV 2/5] END max_depth=11, min_samples_leaf=13, min_samples_split=21;, score=0.752 total time=   0.7s
[CV 3/5] END max_depth=11, min_samples_leaf=13, min_samples_split=21;, score=0.748 total time=   0.7s
[CV 4/5] END max_depth=11, min_samples_leaf=13, min_samples_split=21;, score=0.745 total time=   0.7s
[CV 5/5] END max_depth=11, min_samples_leaf=13, min_samples_split=21;, score=0.733 total time=   0.8s
[CV 1/5] END max_depth=16, min_samples_leaf=17, min_samples_split=24;, score=0.726 total time=   0.8s
[CV 2/5] END max_depth=16, min_samples_leaf=17, min_samples_split=24;, score=0.758 total time=   0.8s
[CV 3/5] END max_depth=16, min_samples_leaf=17, min_samples_split=24;, score=0.753 total time=   0.8s
[CV 4/5] END max_depth=16, min_samples_leaf=17, min_samples_split=24;, score=0.747 total time=   0.8s
[CV 5/5] END max_depth=16, min_samples_leaf=17, min_samples_split=24;, score=0.740 total time=   0.8s
[CV 1/5] END max_depth=12, min_samples_leaf=10, min_samples_split=13;, score=0.725 total time=   0.8s
[CV 2/5] END max_depth=12, min_samples_leaf=10, min_samples_split=13;, score=0.766 total time=   0.8s
[CV 3/5] END max_depth=12, min_samples_leaf=10, min_samples_split=13;, score=0.752 total time=   0.8s
[CV 4/5] END max_depth=12, min_samples_leaf=10, min_samples_split=13;, score=0.750 total time=   0.8s
[CV 5/5] END max_depth=12, min_samples_leaf=10, min_samples_split=13;, score=0.736 total time=   0.9s
[CV 1/5] END max_depth=11, min_samples_leaf=17, min_samples_split=13;, score=0.716 total time=   0.9s
[CV 2/5] END max_depth=11, min_samples_leaf=17, min_samples_split=13;, score=0.754 total time=   0.9s
[CV 3/5] END max_depth=11, min_samples_leaf=17, min_samples_split=13;, score=0.745 total time=   0.9s
[CV 4/5] END max_depth=11, min_samples_leaf=17, min_samples_split=13;, score=0.737 total time=   0.9s
[CV 5/5] END max_depth=11, min_samples_leaf=17, min_samples_split=13;, score=0.727 total time=   0.9s
[CV 1/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.711 total time=   0.9s
[CV 2/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.755 total time=   0.9s
[CV 3/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.749 total time=   0.9s
[CV 4/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.740 total time=   0.9s
[CV 5/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.728 total time=   0.9s
[CV 1/5] END max_depth=19, min_samples_leaf=13, min_samples_split=15;, score=0.731 total time=   1.0s
[CV 2/5] END max_depth=19, min_samples_leaf=13, min_samples_split=15;, score=0.771 total time=   1.1s
[CV 3/5] END max_depth=19, min_samples_leaf=13, min_samples_split=15;, score=0.757 total time=   1.0s
[CV 4/5] END max_depth=19, min_samples_leaf=13, min_samples_split=15;, score=0.753 total time=   1.0s
[CV 5/5] END max_depth=19, min_samples_leaf=13, min_samples_split=15;, score=0.740 total time=   1.0s
[CV 1/5] END max_depth=11, min_samples_leaf=19, min_samples_split=21;, score=0.711 total time=   0.9s
[CV 2/5] END max_depth=11, min_samples_leaf=19, min_samples_split=21;, score=0.745 total time=   0.9s
[CV 3/5] END max_depth=11, min_samples_leaf=19, min_samples_split=21;, score=0.740 total time=   0.9s
[CV 4/5] END max_depth=11, min_samples_leaf=19, min_samples_split=21;, score=0.737 total time=   0.9s
[CV 5/5] END max_depth=11, min_samples_leaf=19, min_samples_split=21;, score=0.721 total time=   0.9s
[CV 1/5] END max_depth=11, min_samples_leaf=19, min_samples_split=23;, score=0.711 total time=   0.9s
[CV 2/5] END max_depth=11, min_samples_leaf=19, min_samples_split=23;, score=0.745 total time=   0.9s
[CV 3/5] END max_depth=11, min_samples_leaf=19, min_samples_split=23;, score=0.740 total time=   0.9s
[CV 4/5] END max_depth=11, min_samples_leaf=19, min_samples_split=23;, score=0.737 total time=   0.9s
[CV 5/5] END max_depth=11, min_samples_leaf=19, min_samples_split=23;, score=0.721 total time=   0.9s
[CV 1/5] END max_depth=13, min_samples_leaf=17, min_samples_split=23;, score=0.717 total time=   0.9s
[CV 2/5] END max_depth=13, min_samples_leaf=17, min_samples_split=23;, score=0.754 total time=   1.0s
[CV 3/5] END max_depth=13, min_samples_leaf=17, min_samples_split=23;, score=0.747 total time=   1.0s
[CV 4/5] END max_depth=13, min_samples_leaf=17, min_samples_split=23;, score=0.745 total time=   0.9s
[CV 5/5] END max_depth=13, min_samples_leaf=17, min_samples_split=23;, score=0.731 total time=   1.0s
[CV 1/5] END max_depth=16, min_samples_leaf=18, min_samples_split=23;, score=0.722 total time=   0.9s
[CV 2/5] END max_depth=16, min_samples_leaf=18, min_samples_split=23;, score=0.760 total time=   1.0s
[CV 3/5] END max_depth=16, min_samples_leaf=18, min_samples_split=23;, score=0.752 total time=   1.0s
[CV 4/5] END max_depth=16, min_samples_leaf=18, min_samples_split=23;, score=0.747 total time=   1.0s
[CV 5/5] END max_depth=16, min_samples_leaf=18, min_samples_split=23;, score=0.729 total time=   1.0s
[CV 1/5] END max_depth=17, min_samples_leaf=14, min_samples_split=22;, score=0.729 total time=   1.0s
[CV 2/5] END max_depth=17, min_samples_leaf=14, min_samples_split=22;, score=0.768 total time=   1.0s
[CV 3/5] END max_depth=17, min_samples_leaf=14, min_samples_split=22;, score=0.753 total time=   1.0s
[CV 4/5] END max_depth=17, min_samples_leaf=14, min_samples_split=22;, score=0.755 total time=   1.0s
[CV 5/5] END max_depth=17, min_samples_leaf=14, min_samples_split=22;, score=0.737 total time=   1.0s
[CV 1/5] END max_depth=11, min_samples_leaf=14, min_samples_split=17;, score=0.718 total time=   0.9s
[CV 2/5] END max_depth=11, min_samples_leaf=14, min_samples_split=17;, score=0.755 total time=   0.9s
[CV 3/5] END max_depth=11, min_samples_leaf=14, min_samples_split=17;, score=0.746 total time=   0.9s
[CV 4/5] END max_depth=11, min_samples_leaf=14, min_samples_split=17;, score=0.742 total time=   0.9s
[CV 5/5] END max_depth=11, min_samples_leaf=14, min_samples_split=17;, score=0.729 total time=   0.9s
[CV 1/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.722 total time=   0.9s
[CV 2/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.763 total time=   1.0s
[CV 3/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.750 total time=   0.9s
[CV 4/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.747 total time=   1.0s
[CV 5/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.732 total time=   1.0s
[CV 1/5] END max_depth=18, min_samples_leaf=10, min_samples_split=18;, score=0.736 total time=   1.0s
[CV 2/5] END max_depth=18, min_samples_leaf=10, min_samples_split=18;, score=0.774 total time=   1.0s
[CV 3/5] END max_depth=18, min_samples_leaf=10, min_samples_split=18;, score=0.757 total time=   1.1s
[CV 4/5] END max_depth=18, min_samples_leaf=10, min_samples_split=18;, score=0.759 total time=   1.0s
[CV 5/5] END max_depth=18, min_samples_leaf=10, min_samples_split=18;, score=0.746 total time=   1.1s
[CV 1/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.722 total time=   0.9s
[CV 2/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.760 total time=   1.0s
[CV 3/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.752 total time=   1.0s
[CV 4/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.747 total time=   0.9s
[CV 5/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.729 total time=   1.0s
[CV 1/5] END max_depth=10, min_samples_leaf=17, min_samples_split=17;, score=0.712 total time=   0.8s
[CV 2/5] END max_depth=10, min_samples_leaf=17, min_samples_split=17;, score=0.749 total time=   0.8s
[CV 3/5] END max_depth=10, min_samples_leaf=17, min_samples_split=17;, score=0.741 total time=   0.8s
[CV 4/5] END max_depth=10, min_samples_leaf=17, min_samples_split=17;, score=0.737 total time=   0.8s
[CV 5/5] END max_depth=10, min_samples_leaf=17, min_samples_split=17;, score=0.721 total time=   0.9s
[CV 1/5] END max_depth=12, min_samples_leaf=10, min_samples_split=17;, score=0.725 total time=   1.0s
[CV 2/5] END max_depth=12, min_samples_leaf=10, min_samples_split=17;, score=0.766 total time=   1.0s
[CV 3/5] END max_depth=12, min_samples_leaf=10, min_samples_split=17;, score=0.752 total time=   1.4s
[CV 4/5] END max_depth=12, min_samples_leaf=10, min_samples_split=17;, score=0.750 total time=   1.6s
[CV 5/5] END max_depth=12, min_samples_leaf=10, min_samples_split=17;, score=0.736 total time=   1.3s
[CV 1/5] END max_depth=12, min_samples_leaf=12, min_samples_split=10;, score=0.719 total time=   1.9s
[CV 2/5] END max_depth=12, min_samples_leaf=12, min_samples_split=10;, score=0.762 total time=   2.3s
[CV 3/5] END max_depth=12, min_samples_leaf=12, min_samples_split=10;, score=0.748 total time=   1.6s
[CV 4/5] END max_depth=12, min_samples_leaf=12, min_samples_split=10;, score=0.748 total time=   1.6s
[CV 5/5] END max_depth=12, min_samples_leaf=12, min_samples_split=10;, score=0.735 total time=   1.6s
[CV 1/5] END max_depth=14, min_samples_leaf=19, min_samples_split=16;, score=0.719 total time=   1.5s
[CV 2/5] END max_depth=14, min_samples_leaf=19, min_samples_split=16;, score=0.755 total time=   1.6s
[CV 3/5] END max_depth=14, min_samples_leaf=19, min_samples_split=16;, score=0.747 total time=   1.7s
[CV 4/5] END max_depth=14, min_samples_leaf=19, min_samples_split=16;, score=0.747 total time=   1.6s
[CV 5/5] END max_depth=14, min_samples_leaf=19, min_samples_split=16;, score=0.731 total time=   1.6s
[CV 1/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.722 total time=   1.5s
[CV 2/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.763 total time=   1.6s
[CV 3/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.750 total time=   1.8s
[CV 4/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.747 total time=   2.0s
[CV 5/5] END max_depth=19, min_samples_leaf=18, min_samples_split=21;, score=0.732 total time=   2.0s
[CV 1/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.722 total time=   1.6s
[CV 2/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.760 total time=   1.7s
[CV 3/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.752 total time=   1.6s
[CV 4/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.747 total time=   1.5s
[CV 5/5] END max_depth=16, min_samples_leaf=18, min_samples_split=17;, score=0.729 total time=   0.8s
[CV 1/5] END max_depth=11, min_samples_leaf=10, min_samples_split=16;, score=0.718 total time=   0.8s
[CV 2/5] END max_depth=11, min_samples_leaf=10, min_samples_split=16;, score=0.763 total time=   0.8s
[CV 3/5] END max_depth=11, min_samples_leaf=10, min_samples_split=16;, score=0.758 total time=   0.8s
[CV 4/5] END max_depth=11, min_samples_leaf=10, min_samples_split=16;, score=0.744 total time=   0.8s
[CV 5/5] END max_depth=11, min_samples_leaf=10, min_samples_split=16;, score=0.735 total time=   0.8s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=50,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E86C57F00>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020EA66A5050>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E86C57350>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [37]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)#.head(20)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
9,18,10,20,0.754584
30,18,10,18,0.754584
10,19,12,21,0.752476
2,19,12,16,0.752476
15,18,11,19,0.751596
7,14,10,21,0.751265
14,16,11,13,0.750659
22,19,13,15,0.750539
11,16,13,18,0.750439
0,16,13,22,0.750439
1,17,14,16,0.748545
27,17,14,22,0.748545
3,17,14,13,0.748545
5,15,14,11,0.747895
42,14,12,10,0.747418
13,16,14,18,0.746626
6,17,15,11,0.746302
8,19,15,22,0.746042
47,13,13,23,0.745829
41,12,10,12,0.745804
33,12,10,17,0.745804
19,12,10,13,0.745804
39,16,17,14,0.744721
18,16,17,24,0.744721
4,17,17,12,0.743834
38,11,10,16,0.743687
29,19,18,21,0.742755
36,19,18,21,0.742755
34,12,12,10,0.742585
48,14,16,16,0.742481
49,13,16,20,0.741848
12,12,14,12,0.741810
31,16,18,17,0.741803
44,16,18,24,0.741803
37,16,18,17,0.741803
26,16,18,23,0.741803
45,19,19,21,0.740684
16,18,19,14,0.739898
17,11,13,21,0.739746
43,14,19,16,0.739645
35,14,19,16,0.739645
46,12,16,10,0.739412
25,13,17,23,0.738738
40,12,17,15,0.738638
28,11,14,17,0.737810
21,11,15,15,0.736539
20,11,17,13,0.735655
32,10,17,17,0.731998
23,11,19,21,0.730946
24,11,19,23,0.730946

In [38]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 18, 'min_samples_leaf': 10, 'min_samples_split': 20}
Best CV score: 0.7545835216748022

In [39]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.92      0.92      5024
           1       0.92      0.91      0.91      4819

    accuracy                           0.92      9843
   macro avg       0.92      0.92      0.92      9843
weighted avg       0.92      0.92      0.92      9843

#### Evaluación

In [40]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.77      0.76       663
           1       0.75      0.74      0.74       633

    accuracy                           0.75      1296
   macro avg       0.75      0.75      0.75      1296
weighted avg       0.75      0.75      0.75      1296

#### Guardado

In [41]:
joblib.dump(best_model, f'./modelos/{dataset}/features_rf.pkl')

['./modelos/ciclos_c_r_hl256/features_rf.pkl']