# Modelo

Para ver como cambia la performance del modelo con el tratamiento de los datos primero hay que tener un modelo de partida que optimizar.

In [1]:
import numpy as np
import pandas as pd
import os
import joblib

from scipy.stats import randint, uniform, norm, loguniform

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import recall_score, classification_report, confusion_matrix, roc_auc_score

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, StratifiedKFold, RandomizedSearchCV

from transformers import AudioFilterResampler, SpectralSubtractor, MelSpectrogramTransformer, SpectrogramPadder, FlattenTransformer, FeatureExtractor

from config import TEST_SIZE, SEED

## Espectrogramas

Se suelen usar Mel espectrogramas

Traigo los consjuntos de entrenamiento y testeo. (TODO: buscar una manera más eficiente de guardarlos)

In [2]:
train_df = pd.read_csv('./dataset/ciclos/filtrado/train_melspectrogram.csv')
test_df = pd.read_csv('./dataset/ciclos/filtrado/test_melspectrogram.csv')

X_train = train_df.drop(columns=['label'])
y_train = train_df['label']
X_test = test_df.drop(columns=['label'])
y_test = test_df['label']

### Random Forest

#### Entrenamiento

In [11]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

param_distributions = {
    'max_depth': randint(10, 15),
    'min_samples_split': randint(5, 25),
    'min_samples_leaf': randint(5, 25)
}

Fine-tuning

El score elegido es auc-roc, podría ser recall o f1.

In [12]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=20,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END max_depth=13, min_samples_leaf=19, min_samples_split=15;, score=0.758 total time=   3.6s
[CV 2/5] END max_depth=13, min_samples_leaf=19, min_samples_split=15;, score=0.746 total time=   3.5s
[CV 3/5] END max_depth=13, min_samples_leaf=19, min_samples_split=15;, score=0.748 total time=   3.5s
[CV 4/5] END max_depth=13, min_samples_leaf=19, min_samples_split=15;, score=0.756 total time=   3.5s
[CV 5/5] END max_depth=13, min_samples_leaf=19, min_samples_split=15;, score=0.775 total time=   3.4s
[CV 1/5] END max_depth=14, min_samples_leaf=11, min_samples_split=23;, score=0.765 total time=   3.8s
[CV 2/5] END max_depth=14, min_samples_leaf=11, min_samples_split=23;, score=0.758 total time=   3.8s
[CV 3/5] END max_depth=14, min_samples_leaf=11, min_samples_split=23;, score=0.747 total time=   3.9s
[CV 4/5] END max_depth=14, min_samples_leaf=11, min_samples_split=23;, score=0.768 total time=   4.0s
[CV 5/5] END max_depth=14, min_samples_leaf=11, min_samples_split=23;, score=0.785 total time=   3.8s
[CV 1/5] END max_depth=12, min_samples_leaf=15, min_samples_split=8;, score=0.759 total time=   3.6s
[CV 2/5] END max_depth=12, min_samples_leaf=15, min_samples_split=8;, score=0.750 total time=   3.6s
[CV 3/5] END max_depth=12, min_samples_leaf=15, min_samples_split=8;, score=0.748 total time=   3.7s
[CV 4/5] END max_depth=12, min_samples_leaf=15, min_samples_split=8;, score=0.758 total time=   3.6s
[CV 5/5] END max_depth=12, min_samples_leaf=15, min_samples_split=8;, score=0.782 total time=   3.6s
[CV 1/5] END max_depth=12, min_samples_leaf=6, min_samples_split=16;, score=0.761 total time=   4.0s
[CV 2/5] END max_depth=12, min_samples_leaf=6, min_samples_split=16;, score=0.755 total time=   3.9s
[CV 3/5] END max_depth=12, min_samples_leaf=6, min_samples_split=16;, score=0.765 total time=   3.9s
[CV 4/5] END max_depth=12, min_samples_leaf=6, min_samples_split=16;, score=0.768 total time=   3.9s
[CV 5/5] END max_depth=12, min_samples_leaf=6, min_samples_split=16;, score=0.792 total time=   3.9s
[CV 1/5] END max_depth=11, min_samples_leaf=5, min_samples_split=16;, score=0.764 total time=   3.9s
[CV 2/5] END max_depth=11, min_samples_leaf=5, min_samples_split=16;, score=0.757 total time=   3.9s
[CV 3/5] END max_depth=11, min_samples_leaf=5, min_samples_split=16;, score=0.753 total time=   3.9s
[CV 4/5] END max_depth=11, min_samples_leaf=5, min_samples_split=16;, score=0.770 total time=   3.7s
[CV 5/5] END max_depth=11, min_samples_leaf=5, min_samples_split=16;, score=0.788 total time=   3.9s
[CV 1/5] END max_depth=11, min_samples_leaf=16, min_samples_split=21;, score=0.758 total time=   3.5s
[CV 2/5] END max_depth=11, min_samples_leaf=16, min_samples_split=21;, score=0.753 total time=   3.5s
[CV 3/5] END max_depth=11, min_samples_leaf=16, min_samples_split=21;, score=0.754 total time=   3.5s
[CV 4/5] END max_depth=11, min_samples_leaf=16, min_samples_split=21;, score=0.756 total time=   3.6s
[CV 5/5] END max_depth=11, min_samples_leaf=16, min_samples_split=21;, score=0.781 total time=   3.7s
[CV 1/5] END max_depth=12, min_samples_leaf=14, min_samples_split=20;, score=0.762 total time=   3.7s
[CV 2/5] END max_depth=12, min_samples_leaf=14, min_samples_split=20;, score=0.749 total time=   3.8s
[CV 3/5] END max_depth=12, min_samples_leaf=14, min_samples_split=20;, score=0.756 total time=   3.8s
[CV 4/5] END max_depth=12, min_samples_leaf=14, min_samples_split=20;, score=0.764 total time=   3.8s
[CV 5/5] END max_depth=12, min_samples_leaf=14, min_samples_split=20;, score=0.777 total time=   3.8s
[CV 1/5] END max_depth=12, min_samples_leaf=16, min_samples_split=24;, score=0.759 total time=   3.6s
[CV 2/5] END max_depth=12, min_samples_leaf=16, min_samples_split=24;, score=0.751 total time=   3.5s
[CV 3/5] END max_depth=12, min_samples_leaf=16, min_samples_split=24;, score=0.750 total time=   3.7s
[CV 4/5] END max_depth=12, min_samples_leaf=16, min_samples_split=24;, score=0.759 total time=   3.7s
[CV 5/5] END max_depth=12, min_samples_leaf=16, min_samples_split=24;, score=0.782 total time=   3.6s
[CV 1/5] END max_depth=10, min_samples_leaf=7, min_samples_split=9;, score=0.755 total time=   3.6s
[CV 2/5] END max_depth=10, min_samples_leaf=7, min_samples_split=9;, score=0.748 total time=   3.6s
[CV 3/5] END max_depth=10, min_samples_leaf=7, min_samples_split=9;, score=0.755 total time=   3.6s
[CV 4/5] END max_depth=10, min_samples_leaf=7, min_samples_split=9;, score=0.766 total time=   3.9s
[CV 5/5] END max_depth=10, min_samples_leaf=7, min_samples_split=9;, score=0.779 total time=   3.7s
[CV 1/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.756 total time=   3.8s
[CV 2/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.760 total time=   3.7s
[CV 3/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.751 total time=   4.6s
[CV 4/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.764 total time=   4.6s
[CV 5/5] END max_depth=12, min_samples_leaf=11, min_samples_split=13;, score=0.775 total time=   4.3s
[CV 1/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.764 total time=   4.4s
[CV 2/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.754 total time=   4.5s
[CV 3/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.759 total time=   4.4s
[CV 4/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.759 total time=   4.3s
[CV 5/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.784 total time=   4.0s
[CV 1/5] END max_depth=11, min_samples_leaf=13, min_samples_split=6;, score=0.753 total time=   3.7s
[CV 2/5] END max_depth=11, min_samples_leaf=13, min_samples_split=6;, score=0.752 total time=   3.6s
[CV 3/5] END max_depth=11, min_samples_leaf=13, min_samples_split=6;, score=0.747 total time=   3.6s
[CV 4/5] END max_depth=11, min_samples_leaf=13, min_samples_split=6;, score=0.762 total time=   3.6s
[CV 5/5] END max_depth=11, min_samples_leaf=13, min_samples_split=6;, score=0.781 total time=   3.7s
[CV 1/5] END max_depth=13, min_samples_leaf=19, min_samples_split=11;, score=0.758 total time=   3.5s
[CV 2/5] END max_depth=13, min_samples_leaf=19, min_samples_split=11;, score=0.746 total time=   3.4s
[CV 3/5] END max_depth=13, min_samples_leaf=19, min_samples_split=11;, score=0.748 total time=   3.6s
[CV 4/5] END max_depth=13, min_samples_leaf=19, min_samples_split=11;, score=0.756 total time=   3.6s
[CV 5/5] END max_depth=13, min_samples_leaf=19, min_samples_split=11;, score=0.775 total time=   3.6s
[CV 1/5] END max_depth=13, min_samples_leaf=12, min_samples_split=19;, score=0.770 total time=   4.4s
[CV 2/5] END max_depth=13, min_samples_leaf=12, min_samples_split=19;, score=0.759 total time=   4.4s
[CV 3/5] END max_depth=13, min_samples_leaf=12, min_samples_split=19;, score=0.755 total time=   4.5s
[CV 4/5] END max_depth=13, min_samples_leaf=12, min_samples_split=19;, score=0.761 total time=   4.5s
[CV 5/5] END max_depth=13, min_samples_leaf=12, min_samples_split=19;, score=0.784 total time=   4.3s
[CV 1/5] END max_depth=12, min_samples_leaf=18, min_samples_split=21;, score=0.757 total time=   4.0s
[CV 2/5] END max_depth=12, min_samples_leaf=18, min_samples_split=21;, score=0.751 total time=   4.0s
[CV 3/5] END max_depth=12, min_samples_leaf=18, min_samples_split=21;, score=0.753 total time=   4.0s
[CV 4/5] END max_depth=12, min_samples_leaf=18, min_samples_split=21;, score=0.756 total time=   4.0s
[CV 5/5] END max_depth=12, min_samples_leaf=18, min_samples_split=21;, score=0.780 total time=   4.0s
[CV 1/5] END max_depth=13, min_samples_leaf=22, min_samples_split=12;, score=0.757 total time=   3.9s
[CV 2/5] END max_depth=13, min_samples_leaf=22, min_samples_split=12;, score=0.742 total time=   4.0s
[CV 3/5] END max_depth=13, min_samples_leaf=22, min_samples_split=12;, score=0.748 total time=   4.0s
[CV 4/5] END max_depth=13, min_samples_leaf=22, min_samples_split=12;, score=0.753 total time=   4.0s
[CV 5/5] END max_depth=13, min_samples_leaf=22, min_samples_split=12;, score=0.769 total time=   4.0s
[CV 1/5] END max_depth=13, min_samples_leaf=6, min_samples_split=10;, score=0.768 total time=   4.7s
[CV 2/5] END max_depth=13, min_samples_leaf=6, min_samples_split=10;, score=0.760 total time=   4.3s
[CV 3/5] END max_depth=13, min_samples_leaf=6, min_samples_split=10;, score=0.770 total time=   4.1s
[CV 4/5] END max_depth=13, min_samples_leaf=6, min_samples_split=10;, score=0.770 total time=   4.3s
[CV 5/5] END max_depth=13, min_samples_leaf=6, min_samples_split=10;, score=0.784 total time=   4.1s
[CV 1/5] END max_depth=11, min_samples_leaf=8, min_samples_split=22;, score=0.760 total time=   3.9s
[CV 2/5] END max_depth=11, min_samples_leaf=8, min_samples_split=22;, score=0.752 total time=   3.7s
[CV 3/5] END max_depth=11, min_samples_leaf=8, min_samples_split=22;, score=0.753 total time=   3.8s
[CV 4/5] END max_depth=11, min_samples_leaf=8, min_samples_split=22;, score=0.760 total time=   3.7s
[CV 5/5] END max_depth=11, min_samples_leaf=8, min_samples_split=22;, score=0.780 total time=   4.1s
[CV 1/5] END max_depth=11, min_samples_leaf=16, min_samples_split=6;, score=0.758 total time=   5.1s
[CV 2/5] END max_depth=11, min_samples_leaf=16, min_samples_split=6;, score=0.753 total time=   4.3s
[CV 3/5] END max_depth=11, min_samples_leaf=16, min_samples_split=6;, score=0.754 total time=   3.5s
[CV 4/5] END max_depth=11, min_samples_leaf=16, min_samples_split=6;, score=0.756 total time=   3.6s
[CV 5/5] END max_depth=11, min_samples_leaf=16, min_samples_split=6;, score=0.781 total time=   3.6s
[CV 1/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.764 total time=   4.6s
[CV 2/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.754 total time=   4.5s
[CV 3/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.759 total time=   4.5s
[CV 4/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.759 total time=   4.7s
[CV 5/5] END max_depth=11, min_samples_leaf=8, min_samples_split=18;, score=0.784 total time=   5.0s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=20,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000242B608F820>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000242B223C5F0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000242B608F100>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [13]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
16,13,6,10,0.770400
3,12,6,16,0.768028
4,11,5,16,0.766585
13,13,12,19,0.765789
1,14,11,23,0.764985
10,11,8,18,0.764096
19,11,8,18,0.764096
6,12,14,20,0.761439
9,12,11,13,0.761349
17,11,8,22,0.760926
8,10,7,9,0.760798
18,11,16,6,0.760337
5,11,16,21,0.760337
7,12,16,24,0.760305
14,12,18,21,0.759433
2,12,15,8,0.759412
11,11,13,6,0.758891
0,13,19,15,0.756559
12,13,19,11,0.756559
15,13,22,12,0.753847

In [14]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 13, 'min_samples_leaf': 6, 'min_samples_split': 10}
Best CV score: 0.7704003319553864

#### Evaluación

In [15]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))
print('AUC-ROC: ', round(roc_auc_score(y_test, y_pred), 2))
print('Recall: ', round(recall_score(y_test, y_pred), 2))

              precision    recall  f1-score   support

           0       0.72      0.57      0.64       429
           1       0.68      0.81      0.74       493

    accuracy                           0.70       922
   macro avg       0.70      0.69      0.69       922
weighted avg       0.70      0.70      0.69       922

AUC-ROC:  0.69
Recall:  0.81

#### Guardado

In [16]:
df_paths = pd.read_csv('./dataset/ciclos/filtrado/train.csv')
paths = ['./dataset/ciclos/' + f for f in df_paths['cycle_wav_file']]
y_train = df_paths['label'].values

In [17]:
# pipeline con la que se creo el dataset
pipeline_proc = Pipeline([
    ('filter_resample', AudioFilterResampler()),
    ('melspec', MelSpectrogramTransformer()),
    ('pad', SpectrogramPadder()),
    ('flatten', FlattenTransformer()),
    ('scaler', StandardScaler())
])

pipeline_final = Pipeline([
    ('preproc', pipeline_proc),
    ('rf', best_model)
])

pipeline_final.fit(paths, y_train)

Pipeline(steps=[('preproc',
                 Pipeline(steps=[('filter_resample', AudioFilterResampler()),
                                 ('melspec', MelSpectrogramTransformer()),
                                 ('pad', SpectrogramPadder()),
                                 ('flatten', FlattenTransformer()),
                                 ('scaler', StandardScaler())])),
                ('rf',
                 RandomForestClassifier(max_depth=13, min_samples_leaf=6,
                                        min_samples_split=10, n_jobs=-1,
                                        random_state=42))])

Guardo el modelo

In [19]:
joblib.dump(pipeline_final, './modelos/melspec_rf.pkl')

['./modelos/melspec_rf.pkl']

#### Evaluación en audios propios

Tengo grabaciones que fueron divididas en ciclos con el segmentador. El audio "respiración4_ciclo5" tiene una sibilancia clara, los demás ciclos de ese audio podrían ser positivos también pero no logro escuchar una sibilancia tan clara.

In [21]:
model = joblib.load('./modelos/melspec_rf.pkl')

In [ ]:
path = './audios_propios/ciclos_energy_based'
files = os.listdir(path)

df_audios_propios = pd.DataFrame(files, columns=['cycle_wav_file'])

df_audios_propios['label'] = np.where(df_audios_propios['cycle_wav_file'].str.contains('respiracion4_ciclo_5'), 1, 0)

df_audios_propios # audios de validacion

              cycle_wav_file  label
0   respiracion1_ciclo_1.wav      0
1   respiracion1_ciclo_2.wav      0
2   respiracion1_ciclo_3.wav      0
3   respiracion1_ciclo_4.wav      0
4   respiracion1_ciclo_5.wav      0
5   respiracion1_ciclo_6.wav      0
6   respiracion1_ciclo_7.wav      0
7   respiracion2_ciclo_1.wav      0
8   respiracion2_ciclo_2.wav      0
9   respiracion2_ciclo_3.wav      0
10  respiracion2_ciclo_4.wav      0
11  respiracion2_ciclo_5.wav      0
12  respiracion2_ciclo_6.wav      0
13  respiracion3_ciclo_1.wav      0
14  respiracion3_ciclo_2.wav      0
15  respiracion3_ciclo_3.wav      0
16  respiracion3_ciclo_4.wav      0
17  respiracion3_ciclo_5.wav      0
18  respiracion3_ciclo_6.wav      0
19  respiracion4_ciclo_1.wav      0
20  respiracion4_ciclo_2.wav      0
21  respiracion4_ciclo_3.wav      0
22  respiracion4_ciclo_4.wav      0
23  respiracion4_ciclo_5.wav      1
24  respiracion4_ciclo_6.wav      0
25  respiracion4_ciclo_7.wav      0
26  respiracion5_ciclo_1.wav      0
27  respiracion5_ciclo_2.wav      0
28  respiracion5_ciclo_3.wav      0
29  respiracion5_ciclo_4.wav      0
30  respiracion5_ciclo_5.wav      0
31  respiracion5_ciclo_6.wav      0
32  respiracion6_ciclo_1.wav      0
33  respiracion6_ciclo_2.wav      0
34  respiracion6_ciclo_3.wav      0
35  respiracion6_ciclo_4.wav      0
36  respiracion6_ciclo_5.wav      0
37  respiracion6_ciclo_6.wav      0
38  respiracion6_ciclo_7.wav      0
39  respiracion7_ciclo_1.wav      0
40  respiracion7_ciclo_2.wav      0
41  respiracion7_ciclo_3.wav      0
42  respiracion7_ciclo_4.wav      0
43  respiracion7_ciclo_5.wav      0
44  respiracion8_ciclo_1.wav      0
45  respiracion8_ciclo_2.wav      0
46  respiracion8_ciclo_3.wav      0
47  respiracion8_ciclo_4.wav      0
48  respiracion8_ciclo_5.wav      0

In [31]:
archivos = df_audios_propios['cycle_wav_file'].tolist()

X_propios_paths = [os.path.join(path, f) for f in archivos]
y_propios = df_audios_propios['label'].values

Predecimos

In [33]:
y_propios_pred = model.predict(X_propios_paths)
y_propios_proba_pred = model.predict_proba(X_propios_paths)[:, 1]

In [34]:
print(classification_report(y_propios, y_propios_pred))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97        48
           1       0.25      1.00      0.40         1

    accuracy                           0.94        49
   macro avg       0.62      0.97      0.68        49
weighted avg       0.98      0.94      0.96        49

In [35]:
df_audios_propios['predicted'] = y_propios_pred
df_audios_propios['probability'] = y_propios_proba_pred.round(2)
df_audios_propios

              cycle_wav_file  label  predicted  probability
0   respiracion1_ciclo_1.wav      0          0         0.41
1   respiracion1_ciclo_2.wav      0          0         0.14
2   respiracion1_ciclo_3.wav      0          0         0.36
3   respiracion1_ciclo_4.wav      0          0         0.08
4   respiracion1_ciclo_5.wav      0          0         0.30
5   respiracion1_ciclo_6.wav      0          0         0.31
6   respiracion1_ciclo_7.wav      0          0         0.30
7   respiracion2_ciclo_1.wav      0          0         0.18
8   respiracion2_ciclo_2.wav      0          0         0.32
9   respiracion2_ciclo_3.wav      0          0         0.35
10  respiracion2_ciclo_4.wav      0          0         0.27
11  respiracion2_ciclo_5.wav      0          0         0.32
12  respiracion2_ciclo_6.wav      0          0         0.24
13  respiracion3_ciclo_1.wav      0          0         0.22
14  respiracion3_ciclo_2.wav      0          0         0.12
15  respiracion3_ciclo_3.wav      0          0         0.22
16  respiracion3_ciclo_4.wav      0          0         0.18
17  respiracion3_ciclo_5.wav      0          0         0.14
18  respiracion3_ciclo_6.wav      0          0         0.13
19  respiracion4_ciclo_1.wav      0          0         0.44
20  respiracion4_ciclo_2.wav      0          1         0.60
21  respiracion4_ciclo_3.wav      0          0         0.32
22  respiracion4_ciclo_4.wav      0          1         0.57
23  respiracion4_ciclo_5.wav      1          1         0.53
24  respiracion4_ciclo_6.wav      0          1         0.52
25  respiracion4_ciclo_7.wav      0          0         0.36
26  respiracion5_ciclo_1.wav      0          0         0.34
27  respiracion5_ciclo_2.wav      0          0         0.18
28  respiracion5_ciclo_3.wav      0          0         0.10
29  respiracion5_ciclo_4.wav      0          0         0.19
30  respiracion5_ciclo_5.wav      0          0         0.41
31  respiracion5_ciclo_6.wav      0          0         0.14
32  respiracion6_ciclo_1.wav      0          0         0.35
33  respiracion6_ciclo_2.wav      0          0         0.15
34  respiracion6_ciclo_3.wav      0          0         0.07
35  respiracion6_ciclo_4.wav      0          0         0.09
36  respiracion6_ciclo_5.wav      0          0         0.48
37  respiracion6_ciclo_6.wav      0          0         0.09
38  respiracion6_ciclo_7.wav      0          0         0.09
39  respiracion7_ciclo_1.wav      0          0         0.49
40  respiracion7_ciclo_2.wav      0          0         0.31
41  respiracion7_ciclo_3.wav      0          0         0.35
42  respiracion7_ciclo_4.wav      0          0         0.36
43  respiracion7_ciclo_5.wav      0          0         0.24
44  respiracion8_ciclo_1.wav      0          0         0.34
45  respiracion8_ciclo_2.wav      0          0         0.34
46  respiracion8_ciclo_3.wav      0          0         0.32
47  respiracion8_ciclo_4.wav      0          0         0.30
48  respiracion8_ciclo_5.wav      0          0         0.24

Parece prometedor, varios ciclos del audio 4 fueron clasificados como anormales.

## Atributos de Audio

1. Resample y Filtro pasa bajos
2. Feature Extractor
    + MFCC
    + ZCR
    + Short-Time Energy
    + SC
    + Spectral Roll-off
    + BER
    + Spectral Flatness
3. Scaler

In [36]:
train_df = pd.read_csv('./dataset/ciclos/filtrado/train_features.csv')
test_df = pd.read_csv('./dataset/ciclos/filtrado/test_features.csv')

X_train = train_df.drop(columns=['label'])
y_train = train_df['label']
X_test = test_df.drop(columns=['label'])
y_test = test_df['label']

### Random Forest

#### Entrenamiento

In [37]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

param_distributions = {
    'max_depth': randint(5, 15),
    'min_samples_split': randint(5, 25),
    'min_samples_leaf': randint(5, 25)
}

In [38]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=20,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.761 total time=   0.4s
[CV 2/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.753 total time=   0.3s
[CV 3/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.780 total time=   0.3s
[CV 4/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.777 total time=   0.4s
[CV 5/5] END max_depth=11, min_samples_leaf=24, min_samples_split=19;, score=0.804 total time=   0.3s
[CV 1/5] END max_depth=12, min_samples_leaf=11, min_samples_split=23;, score=0.791 total time=   0.3s
[CV 2/5] END max_depth=12, min_samples_leaf=11, min_samples_split=23;, score=0.786 total time=   0.3s
[CV 3/5] END max_depth=12, min_samples_leaf=11, min_samples_split=23;, score=0.810 total time=   0.3s
[CV 4/5] END max_depth=12, min_samples_leaf=11, min_samples_split=23;, score=0.803 total time=   0.3s
[CV 5/5] END max_depth=12, min_samples_leaf=11, min_samples_split=23;, score=0.827 total time=   0.3s
[CV 1/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.784 total time=   0.3s
[CV 2/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.774 total time=   0.3s
[CV 3/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.794 total time=   0.3s
[CV 4/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.796 total time=   0.3s
[CV 5/5] END max_depth=11, min_samples_leaf=15, min_samples_split=15;, score=0.821 total time=   0.3s
[CV 1/5] END max_depth=12, min_samples_leaf=8, min_samples_split=12;, score=0.798 total time=   0.4s
[CV 2/5] END max_depth=12, min_samples_leaf=8, min_samples_split=12;, score=0.802 total time=   0.3s
[CV 3/5] END max_depth=12, min_samples_leaf=8, min_samples_split=12;, score=0.825 total time=   0.3s
[CV 4/5] END max_depth=12, min_samples_leaf=8, min_samples_split=12;, score=0.815 total time=   0.3s
[CV 5/5] END max_depth=12, min_samples_leaf=8, min_samples_split=12;, score=0.831 total time=   0.3s
[CV 1/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.804 total time=   0.3s
[CV 2/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.803 total time=   0.3s
[CV 3/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.821 total time=   0.3s
[CV 4/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.817 total time=   0.3s
[CV 5/5] END max_depth=12, min_samples_leaf=7, min_samples_split=6;, score=0.846 total time=   0.3s
[CV 1/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.786 total time=   0.3s
[CV 2/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.775 total time=   0.3s
[CV 3/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.795 total time=   0.3s
[CV 4/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.797 total time=   0.3s
[CV 5/5] END max_depth=12, min_samples_leaf=16, min_samples_split=10;, score=0.823 total time=   0.3s
[CV 1/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.750 total time=   0.3s
[CV 2/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.738 total time=   0.3s
[CV 3/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.750 total time=   0.3s
[CV 4/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.745 total time=   0.3s
[CV 5/5] END max_depth=6, min_samples_leaf=5, min_samples_split=16;, score=0.784 total time=   0.3s
[CV 1/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.787 total time=   0.3s
[CV 2/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.783 total time=   0.3s
[CV 3/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.799 total time=   0.3s
[CV 4/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.807 total time=   0.3s
[CV 5/5] END max_depth=14, min_samples_leaf=16, min_samples_split=21;, score=0.828 total time=   0.3s
[CV 1/5] END max_depth=14, min_samples_leaf=20, min_samples_split=19;, score=0.771 total time=   0.4s
[CV 2/5] END max_depth=14, min_samples_leaf=20, min_samples_split=19;, score=0.769 total time=   0.4s
[CV 3/5] END max_depth=14, min_samples_leaf=20, min_samples_split=19;, score=0.788 total time=   0.3s
[CV 4/5] END max_depth=14, min_samples_leaf=20, min_samples_split=19;, score=0.794 total time=   0.3s
[CV 5/5] END max_depth=14, min_samples_leaf=20, min_samples_split=19;, score=0.817 total time=   0.3s
[CV 1/5] END max_depth=7, min_samples_leaf=16, min_samples_split=24;, score=0.755 total time=   0.3s
[CV 2/5] END max_depth=7, min_samples_leaf=16, min_samples_split=24;, score=0.742 total time=   0.3s
[CV 3/5] END max_depth=7, min_samples_leaf=16, min_samples_split=24;, score=0.757 total time=   0.3s
[CV 4/5] END max_depth=7, min_samples_leaf=16, min_samples_split=24;, score=0.762 total time=   0.3s
[CV 5/5] END max_depth=7, min_samples_leaf=16, min_samples_split=24;, score=0.788 total time=   0.3s
[CV 1/5] END max_depth=13, min_samples_leaf=7, min_samples_split=9;, score=0.808 total time=   0.3s
[CV 2/5] END max_depth=13, min_samples_leaf=7, min_samples_split=9;, score=0.806 total time=   0.3s
[CV 3/5] END max_depth=13, min_samples_leaf=7, min_samples_split=9;, score=0.824 total time=   0.3s
[CV 4/5] END max_depth=13, min_samples_leaf=7, min_samples_split=9;, score=0.827 total time=   0.3s
[CV 5/5] END max_depth=13, min_samples_leaf=7, min_samples_split=9;, score=0.847 total time=   0.3s
[CV 1/5] END max_depth=7, min_samples_leaf=11, min_samples_split=13;, score=0.759 total time=   0.3s
[CV 2/5] END max_depth=7, min_samples_leaf=11, min_samples_split=13;, score=0.747 total time=   0.3s
[CV 3/5] END max_depth=7, min_samples_leaf=11, min_samples_split=13;, score=0.765 total time=   0.3s
[CV 4/5] END max_depth=7, min_samples_leaf=11, min_samples_split=13;, score=0.768 total time=   0.3s
[CV 5/5] END max_depth=7, min_samples_leaf=11, min_samples_split=13;, score=0.794 total time=   0.3s
[CV 1/5] END max_depth=11, min_samples_leaf=22, min_samples_split=8;, score=0.766 total time=   0.3s
[CV 2/5] END max_depth=11, min_samples_leaf=22, min_samples_split=8;, score=0.761 total time=   0.3s
[CV 3/5] END max_depth=11, min_samples_leaf=22, min_samples_split=8;, score=0.782 total time=   0.3s
[CV 4/5] END max_depth=11, min_samples_leaf=22, min_samples_split=8;, score=0.779 total time=   0.4s
[CV 5/5] END max_depth=11, min_samples_leaf=22, min_samples_split=8;, score=0.805 total time=   0.3s
[CV 1/5] END max_depth=13, min_samples_leaf=18, min_samples_split=22;, score=0.778 total time=   0.3s
[CV 2/5] END max_depth=13, min_samples_leaf=18, min_samples_split=22;, score=0.772 total time=   0.3s
[CV 3/5] END max_depth=13, min_samples_leaf=18, min_samples_split=22;, score=0.789 total time=   0.3s
[CV 4/5] END max_depth=13, min_samples_leaf=18, min_samples_split=22;, score=0.801 total time=   0.3s
[CV 5/5] END max_depth=13, min_samples_leaf=18, min_samples_split=22;, score=0.815 total time=   0.3s
[CV 1/5] END max_depth=14, min_samples_leaf=13, min_samples_split=6;, score=0.790 total time=   0.3s
[CV 2/5] END max_depth=14, min_samples_leaf=13, min_samples_split=6;, score=0.786 total time=   0.3s
[CV 3/5] END max_depth=14, min_samples_leaf=13, min_samples_split=6;, score=0.814 total time=   0.3s
[CV 4/5] END max_depth=14, min_samples_leaf=13, min_samples_split=6;, score=0.806 total time=   0.3s
[CV 5/5] END max_depth=14, min_samples_leaf=13, min_samples_split=6;, score=0.834 total time=   0.3s
[CV 1/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.759 total time=   0.3s
[CV 2/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.755 total time=   0.3s
[CV 3/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.766 total time=   0.3s
[CV 4/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.768 total time=   0.3s
[CV 5/5] END max_depth=8, min_samples_leaf=19, min_samples_split=11;, score=0.798 total time=   0.3s
[CV 1/5] END max_depth=12, min_samples_leaf=19, min_samples_split=7;, score=0.778 total time=   0.3s
[CV 2/5] END max_depth=12, min_samples_leaf=19, min_samples_split=7;, score=0.773 total time=   0.3s
[CV 3/5] END max_depth=12, min_samples_leaf=19, min_samples_split=7;, score=0.784 total time=   0.3s
[CV 4/5] END max_depth=12, min_samples_leaf=19, min_samples_split=7;, score=0.793 total time=   0.3s
[CV 5/5] END max_depth=12, min_samples_leaf=19, min_samples_split=7;, score=0.813 total time=   0.3s
[CV 1/5] END max_depth=5, min_samples_leaf=8, min_samples_split=22;, score=0.733 total time=   0.3s
[CV 2/5] END max_depth=5, min_samples_leaf=8, min_samples_split=22;, score=0.723 total time=   0.3s
[CV 3/5] END max_depth=5, min_samples_leaf=8, min_samples_split=22;, score=0.726 total time=   0.3s
[CV 4/5] END max_depth=5, min_samples_leaf=8, min_samples_split=22;, score=0.723 total time=   0.3s
[CV 5/5] END max_depth=5, min_samples_leaf=8, min_samples_split=22;, score=0.758 total time=   0.3s
[CV 1/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.798 total time=   0.3s
[CV 2/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.802 total time=   0.3s
[CV 3/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.825 total time=   0.3s
[CV 4/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.815 total time=   0.3s
[CV 5/5] END max_depth=12, min_samples_leaf=8, min_samples_split=6;, score=0.831 total time=   0.3s
[CV 1/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.777 total time=   0.3s
[CV 2/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.776 total time=   0.3s
[CV 3/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.787 total time=   0.3s
[CV 4/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.792 total time=   0.3s
[CV 5/5] END max_depth=10, min_samples_leaf=14, min_samples_split=8;, score=0.819 total time=   0.3s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=20,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000242654FD260>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000024256600550>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000242654FF8A0>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [39]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
10,13,7,9,0.822435
4,12,7,6,0.818298
3,12,8,12,0.814077
18,12,8,6,0.814077
14,14,13,6,0.806131
1,12,11,23,0.803380
7,14,16,21,0.800697
5,12,16,10,0.795304
2,11,15,15,0.793739
13,13,18,22,0.790979
19,10,14,8,0.790074
16,12,19,7,0.788330
8,14,20,19,0.787753
12,11,22,8,0.778871
0,11,24,19,0.775035
15,8,19,11,0.769328
11,7,11,13,0.766756
9,7,16,24,0.760792
6,6,5,16,0.753422
17,5,8,22,0.732701

In [40]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 13, 'min_samples_leaf': 7, 'min_samples_split': 9}
Best CV score: 0.8224354783261132

#### Evaluación

In [41]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))
print('AUC-ROC: ', round(roc_auc_score(y_test, y_pred), 2))
print('Recall: ', round(recall_score(y_test, y_pred), 2))

              precision    recall  f1-score   support

           0       0.78      0.64      0.70       429
           1       0.73      0.84      0.78       493

    accuracy                           0.75       922
   macro avg       0.75      0.74      0.74       922
weighted avg       0.75      0.75      0.75       922

AUC-ROC:  0.74
Recall:  0.84

#### Guardado

In [42]:
df_paths = pd.read_csv('./dataset/ciclos/filtrado/train.csv')
paths = ['./dataset/ciclos/' + f for f in df_paths['cycle_wav_file']]
y_train = df_paths['label'].values

In [43]:
# pipeline con la que se creo el dataset
pipeline_feature_extraction = Pipeline([
    ('filter_resample', AudioFilterResampler()),
    ('feature_extractor', FeatureExtractor()),
    ('scaler', StandardScaler())
])

pipeline_final = Pipeline([
    ('feature_extraction', pipeline_feature_extraction),
    ('rf', best_model)
])

pipeline_final.fit(paths, y_train)

Pipeline(steps=[('feature_extraction',
                 Pipeline(steps=[('filter_resample', AudioFilterResampler()),
                                 ('feature_extractor', FeatureExtractor()),
                                 ('scaler', StandardScaler())])),
                ('rf',
                 RandomForestClassifier(max_depth=13, min_samples_leaf=7,
                                        min_samples_split=9, n_jobs=-1,
                                        random_state=42))])

Guardo el modelo

In [44]:
joblib.dump(pipeline_final, './modelos/features_rf.pkl')

['./modelos/features_rf.pkl']

#### Validación

In [45]:
modelo = joblib.load('./modelos/features_rf.pkl')

In [46]:
y_propios_pred = modelo.predict(X_propios_paths)
y_propios_proba_pred = modelo.predict_proba(X_propios_paths)[:, 1]

In [47]:
print(classification_report(y_propios, y_propios_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        48
           1       0.00      0.00      0.00         1

    accuracy                           0.98        49
   macro avg       0.49      0.50      0.49        49
weighted avg       0.96      0.98      0.97        49

c:\Users\nazar\Clasificador-Respiracion\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\nazar\Clasificador-Respiracion\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\nazar\Clasificador-Respiracion\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [48]:
df_audios_propios['predicted'] = y_propios_pred
df_audios_propios['probability'] = y_propios_proba_pred.round(2)
df_audios_propios

              cycle_wav_file  label  predicted  probability
0   respiracion1_ciclo_1.wav      0          0         0.31
1   respiracion1_ciclo_2.wav      0          0         0.34
2   respiracion1_ciclo_3.wav      0          0         0.30
3   respiracion1_ciclo_4.wav      0          0         0.24
4   respiracion1_ciclo_5.wav      0          0         0.38
5   respiracion1_ciclo_6.wav      0          0         0.26
6   respiracion1_ciclo_7.wav      0          0         0.31
7   respiracion2_ciclo_1.wav      0          0         0.25
8   respiracion2_ciclo_2.wav      0          0         0.28
9   respiracion2_ciclo_3.wav      0          0         0.33
10  respiracion2_ciclo_4.wav      0          0         0.35
11  respiracion2_ciclo_5.wav      0          0         0.28
12  respiracion2_ciclo_6.wav      0          0         0.20
13  respiracion3_ciclo_1.wav      0          0         0.22
14  respiracion3_ciclo_2.wav      0          0         0.23
15  respiracion3_ciclo_3.wav      0          0         0.24
16  respiracion3_ciclo_4.wav      0          0         0.24
17  respiracion3_ciclo_5.wav      0          0         0.27
18  respiracion3_ciclo_6.wav      0          0         0.24
19  respiracion4_ciclo_1.wav      0          0         0.24
20  respiracion4_ciclo_2.wav      0          0         0.26
21  respiracion4_ciclo_3.wav      0          0         0.22
22  respiracion4_ciclo_4.wav      0          0         0.34
23  respiracion4_ciclo_5.wav      1          0         0.37
24  respiracion4_ciclo_6.wav      0          0         0.40
25  respiracion4_ciclo_7.wav      0          0         0.25
26  respiracion5_ciclo_1.wav      0          0         0.16
27  respiracion5_ciclo_2.wav      0          0         0.19
28  respiracion5_ciclo_3.wav      0          0         0.25
29  respiracion5_ciclo_4.wav      0          0         0.19
30  respiracion5_ciclo_5.wav      0          0         0.23
31  respiracion5_ciclo_6.wav      0          0         0.20
32  respiracion6_ciclo_1.wav      0          0         0.20
33  respiracion6_ciclo_2.wav      0          0         0.28
34  respiracion6_ciclo_3.wav      0          0         0.29
35  respiracion6_ciclo_4.wav      0          0         0.30
36  respiracion6_ciclo_5.wav      0          0         0.29
37  respiracion6_ciclo_6.wav      0          0         0.27
38  respiracion6_ciclo_7.wav      0          0         0.26
39  respiracion7_ciclo_1.wav      0          0         0.25
40  respiracion7_ciclo_2.wav      0          0         0.20
41  respiracion7_ciclo_3.wav      0          0         0.20
42  respiracion7_ciclo_4.wav      0          0         0.22
43  respiracion7_ciclo_5.wav      0          0         0.22
44  respiracion8_ciclo_1.wav      0          0         0.23
45  respiracion8_ciclo_2.wav      0          0         0.28
46  respiracion8_ciclo_3.wav      0          0         0.23
47  respiracion8_ciclo_4.wav      0          0         0.20
48  respiracion8_ciclo_5.wav      0          0         0.20